using System.Text;
using System.Text.Json.Nodes;
using TiaMcp.BuildCommon;
using Xunit;

namespace TiaMcp.SourceContracts.Tests;

public sealed class EngineSourcesTests : IDisposable
{
    private readonly OfflineFixtures scratch = new("engine-sources-test-");
    public EngineSourcesTests()
    {
        var fixture = JsonNode.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "Vectors/engine-source.json")))!;
        Add("Original.cs", fixture["source"]!.GetValue<string>());
    }
    public void Dispose() => scratch.Dispose();
    private string Add(string relative, string text)
    {
        var path = Path.Combine(scratch.DirectoryPath, "src/Engine", relative);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, text, new UTF8Encoding(true));
        return path;
    }
    private EngineSources Sources() => new(scratch.DirectoryPath);

    [Fact]
    public void MemberSurvivesMoveAndPreservesUtf8()
    {
        var before = Sources().Member("Read", signature: "string text");
        var moved = Path.Combine(scratch.DirectoryPath, "src/Engine/Services/Nested/Renamed.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(moved)!);
        File.Move(Path.Combine(scratch.DirectoryPath, "src/Engine/Original.cs"), moved);
        Assert.Equal(before, Sources().Member("Read", signature: "string text"));
        Assert.EndsWith("return text;\n    }", before);
        Add("Utf8.cs", "class Utf8 { public string Label() => \"中文\"; }");
        Assert.Contains("中文", Sources().Member("Label"));
    }

    [Fact]
    public void MissingAndAmbiguousMembersFail()
    {
        var sources = Sources();
        foreach (var name in new[] { "Missing", "Decoy", "Read" }) Assert.Throws<ArgumentException>(() => sources.Member(name));
        Add("Duplicate.cs", "class Other { public string Tool() => \"duplicate\"; }");
        Assert.Throws<ArgumentException>(() => Sources().Member("Tool"));
    }

    [Fact]
    public void OverloadsOwnerAndToolAttribute()
    {
        var sources = Sources();
        Assert.Equal("public string Read(int count) => count.ToString();", sources.Member("Read", signature: "int count", owner: "Service"));
        Assert.Equal("public void Read() { }", sources.Member("Read", owner: "Nested"));
        Assert.Equal("=> Read(1);", sources.Member("Tool", tool: true, bodyOnly: true));
        Assert.Throws<ArgumentException>(() => sources.Member("Tool", tool: false));
        const string source = "try { Call(); } catch { if (true) { Log(\"}\"); } throw; } Later();";
        Assert.Equal("{ if (true) { Log(\"}\"); } throw; }", EngineSources.BlockAfter(source, "catch"));
        Assert.Throws<ArgumentException>(() => EngineSources.BlockAfter(source, "absent"));
    }

    [Fact]
    public void GeneratedAndBuildSourcesAreExcluded()
    {
        foreach (var path in new[] { "bin/Bad.cs", "obj-v20/Bad.cs", "Generated/Bad.cs", "Other.g.cs" }) Add(path, "class Bad { public void Tool() { } }");
        Add("Auto.cs", "// <auto-generated/>\nclass Bad { public void Tool() { } }");
        Add("AutoUnicode.cs", "// " + string.Concat(Enumerable.Repeat("😀", 1500)) + " <auto-generated/>\nclass Bad { public void Tool() { } }");
        Assert.Contains("=> Read(1);", Sources().Member("Tool"));
    }

    [Fact]
    public void PartialTypesAndPreprocessorBraces()
    {
        Add("Branch.cs", "partial class Branch {\npublic void Conditional() {\n#if ONE\n    if (true) {\n#else\n    if (false) {\n#endif\n    }\n}\n}");
        Add("Elsewhere.cs", "partial class Branch { public void Second() { } }");
        var sources = Sources();
        Assert.Contains("#else", sources.Member("Conditional"));
        Assert.Equal(2, sources.TypeText("Branch").Split("class Branch").Length - 1);
        Assert.Throws<ArgumentException>(() => sources.TypeText("Missing"));
        Add("Order/Part.cs", "partial class Ordered { /* first */ }");
        Add("Order.cs", "partial class Ordered { /* second */ }");
        Assert.Equal("class Ordered { /* first */ }\nclass Ordered { /* second */ }", Sources().TypeText("Ordered"));
    }

    [Fact]
    public void ToolLookupSkipsMigrationForwarders()
    {
        Add("Forwarders.cs", "class McpServer { public static string Forward() => Other.Forward(); } class Kernel { public string Forward() => EngineServices.Get().Forward(); } class Other { public string Forward() { return \"body\"; } }");
        Assert.Equal("public string Forward() { return \"body\"; }", Sources().Member("Forward", tool: false));
    }
    [Fact]
    public void SharedAndHostSourcesParticipateInMoveIndependentLookup()
    {
        foreach (var folder in new[] { "src/Shared", "src/Shared/Host" })
        {
            var directory = Directory.CreateDirectory(Path.Combine(scratch.DirectoryPath, folder)).FullName;
            var name = folder.EndsWith("Host", StringComparison.Ordinal) ? "HostMember" : "SharedMember";
            File.WriteAllText(Path.Combine(directory, name + ".cs"), "class " + name + " { public void " + name + "Call() { } }");
            Assert.Contains("public void " + name + "Call()", Sources().Member(name + "Call"));
        }
    }
}
