using System;
using System.Collections.Generic;

namespace TiaOpenness.Gui.Localization;

/// <summary>
/// Every visible string, in both languages.
///
/// The two languages are held as one table of triples rather than two parallel files: a key
/// cannot exist in English and be missing in Chinese, because there is only one place to add
/// it. <c>StringsTests</c> checks the rest - no duplicates, nothing blank, and the same
/// <c>{0}</c> placeholders on both sides.
/// </summary>
internal static class Strings
{
    /// <summary>key, English, Chinese.</summary>
    internal static readonly (string Key, string En, string Zh)[] Catalogue =
    [
        ("Config.ListSeparator", ", ", "、"),
        ("Config.ClientSaveError", "{0}: {1}", "{0}：{1}"),
        ("Config.UpdateSize", "({0})", "（{0}）"),
        ("Config.ReasonSeparator", "; ", "；"),
        ("Config.Eyebrow", "ENGINEERING LINK CONSOLE", "工程连接控制台"),
        ("Config.RemoteTitle", "Connect TIA and AI on one page", "一页连接 TIA 与 AI"),
        ("Config.LocalTitle", "Same machine, one pass", "同机连接，一次配置"),
        ("Config.RemoteSubtitle", "The machine with TIA Portal runs an HTTP service. AI clients connect over the network; both sides use one shared secret.", "安装 TIA Portal 的电脑运行 HTTP 服务；AI 客户端通过网络连接，两端使用同一密钥。"),
        ("Config.LocalSubtitle", "TIA Portal and the AI client share one PC. The client starts the engine on demand over stdio.", "TIA Portal 与 AI 客户端在同一台电脑，客户端通过 stdio 按需启动引擎。"),
        ("Config.RemoteMode", "VM ↔ Host", "虚拟机 ↔ 宿主机"),
        ("Config.LocalMode", "Same machine", "同一台电脑"),
        ("Config.RemoteNote", "The TIA machine runs an HTTP service; AI clients connect over the network with a shared secret.", "TIA 电脑运行 HTTP 服务；AI 客户端通过网络和共享密钥连接。"),
        ("Config.LocalNote", "TIA and the AI client share one PC; the client starts the engine on demand over stdio.", "TIA 与 AI 客户端在同一台电脑，通过 stdio 按需启动引擎。"),
        ("Config.Installation", "TIA installation", "TIA 安装"),
        ("Config.Version", "Version", "版本"),
        ("Config.InstallPath", "Install path · without Bin", "安装路径 · 不含 Bin"),
        ("Config.Browse", "Browse", "浏览"),
        ("Config.Detect", "Auto-detect", "自动检测"),
        ("Config.Detected", "Detected", "已检测到"),
        ("Config.NotDetected", "Not detected", "未检测到"),
        ("Config.HttpService", "HTTP service", "HTTP 服务"),
        ("Config.LocalEngine", "Local engine", "本地引擎"),
        ("Config.Ip", "VM IPv4", "虚拟机 IPv4"),
        ("Config.Port", "Port", "端口"),
        ("Config.Network", "Network permission", "网络权限"),
        ("Config.Start", "Start service", "启动服务"),
        ("Config.Stop", "Stop", "停止"),
        ("Config.LocalEngineNote", "The AI client starts the local engine on demand.", "AI 客户端按需启动本地引擎。"),
        ("Config.LocalActionsNote", "No network service or secret required.", "无需网络服务或密钥。"),
        ("Config.AiClients", "AI clients · ", "AI 客户端 · "),
        ("Config.ClientNote", "Writes MCP connection info only", "仅写入 MCP 连接信息"),
        ("Config.Secret", "Shared secret", "共享密钥"),
        ("Config.Generate", "Generate", "生成"),
        ("Config.Show", "Show", "显示"),
        ("Config.Test", "Test connection", "测试连接"),
        ("Config.Write", "Write client config", "写入客户端配置"),
        ("Config.Summary", "Summary", "连接摘要"),
        ("Config.Clients", "Clients", "客户端"),
        ("Config.Service", "Service", "服务"),
        ("Config.Address", "Address", "地址"),
        ("Config.Transport", "Transport", "传输方式"),
        ("Config.Log", "Activity log", "活动日志"),
        ("Config.Idle", "idle", "空闲"),
        ("Config.Running", "running", "运行中"),
        ("Config.Local", "local", "本地"),
        ("Config.NoSelection", "None selected", "未选择"),
        ("Config.Selected", "{0} selected", "已选 {0} 个"),
        ("Config.NoAddress", "Address not set", "未填写地址"),
        ("Config.LocalAddress", "stdio · local", "stdio · 本地"),
        ("Config.LastTest", "Last test · {0}", "上次测试 · {0}"),
        ("Config.TestNotRun", "Not run. TIA project connection not yet verified.", "尚未测试。尚未验证 TIA 工程连接。"),
        ("Config.TestFailed", "Failed. See activity log.", "失败，请查看活动日志。"),
        ("Config.InitialTest", "Last test · Not run. TIA project connection not yet verified.", "上次测试 · 尚未测试。尚未验证 TIA 工程连接。"),
        ("Config.Entries", "{0} entries", "{0} 条记录"),
        ("Config.Entry", "{0} entry", "{0} 条记录"),
        ("Config.EmptyLog", "0 entries", "0 条记录"),
        ("Config.Light", "Light", "浅色"),
        ("Config.Dark", "Dark", "深色"),
        ("Config.Auto", "Auto", "跟随系统"),
        ("Config.SaveBoth", "Save both configurations", "保存两端配置"),
        ("Config.Minimize", "Minimize", "最小化"),
        ("Config.Maximize", "Maximize / restore", "最大化 / 还原"),
        ("Config.Close", "Close", "关闭"),
        ("Config.Update", "_Update", "更新(_U)"),
        ("Config.UnknownEngine", "Engine version unknown", "引擎版本未知"),
        ("Config.NotChecked", "Not checked yet", "尚未检查"),
        ("Config.CheckUpdate", "_Check for Updates", "检查更新(_C)"),
        ("Config.RunUpdate", "Update _Engine…", "更新引擎…(_R)"),
        ("Config.Releases", "Open _GitHub Releases", "打开 GitHub Releases(_G)"),
        ("Config.ClientHelp", "Selected Client _Instructions", "所选客户端的使用说明(_I)"),
        ("Config.ProjectPage", "Open _Project Page", "打开项目主页(_P)"),
        ("Config.About", "_About", "关于(_A)"),
        ("Config.NeedsAttention", "Needs attention", "需要处理"),
        ("Config.Saved", "Saved", "已保存"),
        ("Config.Testing", "Testing…", "正在测试…"),
        ("Config.ConnectionOk", "Connection OK", "连接正常"),
        ("Config.ConfiguringNetwork", "Configuring network…", "配置网络…"),
        ("Config.NetworkConfigured", "Network configured", "网络已配置"),
        ("Config.ServiceStopped", "Service stopped", "服务已停止"),
        ("Config.ServiceRunning", "Service process running", "服务进程运行中"),
        ("Config.ClientsConfigured", "{0} clients configured", "已配置 {0} 个客户端"),
        ("Config.SelectRelease", "Select a runnable TIA Portal version.", "请选择可运行的 TIA Portal 版本。"),
        ("Config.ClientListSeparator", ", ", "，"),
        ("Config.ClientDetection", "Client detection: {0} (✓ = detected on this PC; undetected clients can still be configured)", "客户端检测：{0}（✓ = 本机检测到；未检测到的仍可写入）"),
        ("Config.ClientInstructionsCaption", "Client instructions", "客户端使用说明"),
        ("Config.BrowseTiaDescription", "Select the Portal V{0} installation directory, without Bin", "选择 Portal V{0} 安装目录，不带 Bin"),
        ("Config.UnknownInstalledEngine", "Unknown (outside the delivery bundle)", "未知（不在交付包里）"),
        ("Config.AboutDetails", "TIA Portal · MCP Bridge Configurator {0}\nEngine: {1}\nDirectory: {2}\n\nUse “Update → Update engine…”; scripts\\operations\\Update-Engine.ps1 performs the update after the engine stops.", "TIA Portal · MCP Bridge 配置器 {0}\n引擎：{1}\n目录：{2}\n\n更新走菜单“更新 → 更新引擎…”，由 scripts\\operations\\Update-Engine.ps1 在引擎停止后完成。"),
        ("Config.AboutCaption", "About", "关于"),
        ("Config.Ready", "Ready. Configure the service and clients on one page, using the same secret on both sides.", "就绪。服务与客户端配置在同一页完成，两端使用同一密钥。"),
        ("Config.ChooseClients", "Select one or more clients. Saving writes their configuration automatically.", "选择一个或多个客户端，保存后将自动写入对应配置。"),
        ("Config.ClientInstructionsDetected", "{0}: {1} (Detected: {2})", "{0}：{1}（已检测到：{2}）"),
        ("Config.ClientInstructionsNotDetected", "{0}: {1} (Not detected: {2})", "{0}：{1}（未检测到：{2}）"),
        ("Config.HttpListenFailed", "HTTP listener failed ({0}): {1}. For access denied, click “Network permission”; if the port is in use, stop the old MCP or use another port.", "HTTP 监听失败（{0}）：{1}。拒绝访问时点击“网络权限”；端口占用时停止旧 MCP 或更换端口。"),
        ("Config.Unauthorized", "Authentication failed (401): check that both sides use the same shared secret.", "鉴权失败（401）：请检查两端连接密钥是否一致。"),
        ("Config.ConnectionFailed", "Connection failed: {0} Check the VM service, IP, port and firewall.", "连接失败：{0} 请检查虚拟机服务、IP、端口和防火墙。"),
        ("Config.TiaDetected", "Auto-detected V{0} installation directory ({1}): {2}", "已自动检测到 V{0} 安装目录（{1}）：{2}"),
        ("Config.TiaNotDetected", "Not auto-detected: {0}. Use “Browse” to select the Portal V{1} installation root manually.", "未自动检测到：{0}。请用“浏览”手动选择 Portal V{1} 安装根目录。"),
        ("Config.SavedReleaseMismatch", "The TIA version in the saved configuration does not match.", "已保存配置中的 TIA 版本不匹配。"),
        ("Config.ServerLoaded", "Loaded V{0} service configuration.", "已载入 V{0} 服务配置。"),
        ("Config.ClientConnectionSaved", "Client connection details were encrypted and saved for the current Windows user.", "客户端侧连接信息已按当前 Windows 用户加密保存。"),
        ("Config.ServerSaved", "Service configuration saved. Next: Network permission → Start service.", "服务端配置已保存。下一步：网络权限 → 启动服务。"),
        ("Config.ClientOnlySaved", "This PC failed service validation; only client details were saved: {0}", "本机未通过服务端校验，只保存了客户端侧信息：{0}"),
        ("Config.SelectClientsFirst", "Select one or more AI clients first.", "请先选择一个或多个 AI 客户端。"),
        ("Config.WriteClientsPrompt", "Exit the selected clients first to avoid concurrent configuration writes.\nOther settings will be preserved and the original files backed up:\n\n", "请先退出所选客户端，避免配置同时写入。\n将保留其它设置并备份原文件：\n\n"),
        ("Config.WriteClientsContinue", "\n\nClient configurations store the secret in their own format. Do not share files or backups. Continue?", "\n\n客户端配置按其格式保存密钥，请勿分享文件或备份。继续？"),
        ("Config.ClientSaved", "{0} saved: {1}", "{0} 已保存：{1}"),
        ("Config.RestartClients", "Restart the configured clients and use {0} to read the project tree. Do not let multiple AIs modify the same project at the same time.", "重启已配置的客户端，使用 {0} 读取工程树。不要让多个 AI 同时修改同一工程。"),
        ("Config.SomeClientsNotSaved", "Some clients were not saved; successful changes were retained:\n{0}", "部分客户端未保存，其它成功项已保留：\n{0}"),
        ("Config.EngineOutsideBundle", "Engine version unknown: this is not an extracted delivery bundle (manifest\\delivery.json is missing)", "引擎版本未知：这里不是解压后的交付包（没有 manifest\\delivery.json）"),
        ("Config.InstalledEngine", "Engine {0} ({1})", "引擎 {0}（{1}）"),
        ("Config.SourceRepositoryUpdate", "Source repository (.git present): do not update here; publish with scripts\\build\\Release.ps1", "源码仓库（有 .git）：不在这里更新，发布走 scripts\\build\\Release.ps1"),
        ("Config.CheckingUpdate", "Checking GitHub for the latest version…", "正在检查 GitHub 最新版本…"),
        ("Config.UpdateAvailable", "Update to {0}{1} · Stop the engine first, then click “Update engine…” below", "可更新到 {0}{1} · 先停引擎，再点下面的“更新引擎…”"),
        ("Config.UpdateMenuAvailable", "Update · New version {0}(_U)", "更新 · 有新版本 {0}(_U)"),
        ("Config.UpdateAvailableLog", "Update check: {0} → {1}{2}; use “Update → Update engine…” ({3})", "检查更新：{0} → {1}{2}，菜单“更新 → 更新引擎…”执行（{3}）"),
        ("Config.UpToDate", "Up to date ({0})", "已是最新（{0}）"),
        ("Config.UpToDateLog", "Update check: {0} is up to date ({1})", "检查更新：{0} 已是最新（{1}）"),
        ("Config.CannotCheckUpdate", "Cannot check: {0}", "无法检查：{0}"),
        ("Config.UpdateCheckFailed", "Update check failed: {0}", "检查更新失败：{0}"),
        ("Config.FinishOperationsBeforeUpdate", "Finish project operations and disconnect the TIA session before updating the software.", "请先完成工程操作并断开 TIA 会话，再更新软件。"),
        ("Config.CannotUpdateSource", "This is a source repository; do not update here.", "这是源码仓库，不在这里更新。"),
        ("Config.StopServiceBeforeUpdate", "Click “Stop” to end the MCP started by this window before updating.", "先点“停止”结束本窗口启动的 MCP，再更新。"),
        ("Config.EnginesStillRunning", "Engines are still running; the updater will refuse: {0}. Stop them before updating (an AI client may have started them; close that session).", "引擎仍在运行，更新器会拒绝：{0}。请先停止它（可能是某个 AI 客户端启动的：关闭那个会话），再更新。"),
        ("Config.UpdaterMissing", "Updater not found: {0}. Download the complete delivery bundle again from GitHub Releases.", "找不到更新器 {0}。请从 GitHub Releases 重新下载完整交付包。"),
        ("Config.LatestVersion", "the latest version", "最新版"),
        ("Config.RunUpdatePrompt", "This application will close. A new PowerShell window will update\n{0}\nto {1}: download the ZIP and .sha256, verify SHA-256, back up to .previous, and replace runtime and manifest. This application reopens automatically when finished; on failure the window keeps the error details, and -Rollback restores the previous version.\n\nContinue?", "将关闭本程序，在新的 PowerShell 窗口里把\n{0}\n更新到 {1}：下载 ZIP 与 .sha256、校验 SHA-256、备份到 .previous、替换 runtime 与 manifest。完成后自动重新打开本程序；失败时该窗口保留错误信息，-Rollback 可换回上一版。\n\n继续？"),
        ("Config.RunUpdateCaption", "Update engine", "更新引擎"),
        ("Config.UpdaterStarted", "The updater has started in a new window. This application will close.", "更新器已在新窗口启动，本程序即将关闭。"),
        ("Config.NetworkPrompt", "Authorize this HTTP address for the current user and allow the local subnet to access this port.\nWindows will ask for administrator permission next. Continue?", "为当前用户授权此 HTTP 地址，并放行本地子网到此端口。\n接下来会出现 Windows 管理员权限提示，继续？"),
        ("Config.NetworkIncomplete", "Network configuration did not finish. Check the errors in the administrator window.", "网络配置未完成，请查看管理员窗口中的错误信息。"),
        ("Config.NetworkReady", "Network permissions configured. You can now start the service.", "网络权限配置完成。现在可以启动服务。"),
        ("Config.ServiceAlreadyStarted", "This window has already started MCP.", "此窗口已经启动 MCP。"),
        ("Config.ServiceExited", "MCP exited with code: {0}", "MCP 已退出，退出码：{0}"),
        ("Config.ServiceNotStarted", "The MCP process did not start.", "MCP 进程未启动。"),
        ("Config.CheckListening", "Check the log for the listening message and test the connection from the host. Keep this window open.", "请检查日志中的 listening 提示，并在宿主机测试连接。保持此窗口打开。"),
        ("Config.StopServicePrompt", "This will stop the MCP started by this window and disconnect clients.\nMake sure no project operations are running. Continue?", "将停止本窗口启动的 MCP，中断客户端连接。\n请确认没有正在执行的工程操作。继续？"),
        ("Config.StopServiceCaption", "Stop MCP", "停止 MCP"),
        ("Config.WaitBeforeClosing", "Configuration is in progress. Wait before closing.", "正在处理配置，请稍候再关闭。"),
        ("Desktop.Engineering", "Engineering", "工程操作"),
        ("Desktop.Configuration", "MCP & clients", "MCP 与客户端"),
        ("Connection.OpennessVersion", "Openness API version (blank: automatic)", "Openness API 版本（留空自动选择）"),
        ("Glass.Disconnected", "Not connected", "未连接"),
        ("Glass.Connected", "●  Connected", "●  已连接"),
        ("Glass.Software", "PLC software", "PLC 软件"),
        ("Glass.Transfer", "Export · Import", "导出 · 导入"),
        ("Glass.Vci", "VCI workspace", "VCI 工作区"),
        ("Glass.Git", "Git diff", "Git 差异"),
        ("Glass.Bound", "Bound", "已绑定"),
        ("Glass.SelectAll", "Select all", "全选"),
        ("Glass.Clear", "Clear", "清空"),
        ("Glass.Name", "NAME", "名称"),
        ("Glass.Type", "TYPE", "类型"),
        ("Glass.Number", "NO.", "编号"),
        ("Glass.Language", "LANG", "语言"),
        ("Glass.Group", "GROUP PATH", "组路径"),
        ("Glass.Consistent", "CONSISTENT", "一致性"),
        ("Glass.KnowHow", "KNOW-HOW", "专有技术"),
        ("Glass.ExportXml", "Export · SimaticML XML", "导出 · SimaticML XML"),
        ("Glass.ImportXml", "Import XML…", "导入 XML…"),
        ("Glass.CompileSoftware", "Compile PLC software", "编译 PLC 软件"),
        ("Glass.Errors", "errors", "个错误"),
        ("Glass.Warnings", "warnings", "条警告"),
        ("Glass.Inspection", "Inspection", "审查结果"),
        ("Glass.ReadStatus", "Read status", "读取状态"),
        ("Glass.NewWorkspace", "New workspace", "新建工作区"),
        ("Glass.Mapping", "Object mapping", "对象映射"),
        ("Glass.WholeProject", "Whole project", "整个项目"),
        ("Glass.PreviewMapping", "Preview mapping", "预览映射"),
        ("Glass.RunMapping", "Run mapping", "执行映射"),
        ("Glass.Sync", "Sync", "同步"),
        ("Glass.NotGitPush", "Not a git push", "并非 Git 推送"),
        ("Glass.ToWorkspace", "To workspace", "到工作区"),
        ("Glass.ToProject", "To project", "到项目"),
        ("Glass.PreviewSync", "Preview sync", "预览同步"),
        ("Glass.RunSync", "Run sync", "执行同步"),
        ("Glass.MappedObjects", "Mapped objects", "已映射对象"),
        ("Glass.File", "FILE", "文件"),
        ("Glass.LocalDiff", "Local git diff", "本地 Git 差异"),
        ("Glass.WorkingTree", "Working tree", "工作树"),
        ("Glass.DiffScope", "Staged, unstaged and untracked changes. No branches, commits or GitHub sync here.", "包含暂存、未暂存和未跟踪的改动。此处不管理分支、提交或 GitHub 同步。"),
        ("Glass.NamingPattern", "Naming rule (regular expression)", "命名规则（正则表达式）"),
        ("Tab.Blocks", "Blocks", "程序块"),
        ("Tab.VersionControl", "Version control", "版本控制"),
        ("Glass.Mapped", "mapped", "已映射"),
        ("Glass.Unsupported", "unsupported", "不支持"),
        ("Glass.Failed", "failed", "失败"),
        ("Glass.All", "All", "全部"),
        ("Glass.Differ", "Differ", "差异"),
        ("Glass.Missing", "Missing", "缺失"),
        ("Glass.InspectFile", "Select this VCI object to inspect its local Git diff", "选择此 VCI 对象以查看本地 Git 差异"),
        // ---- shell -----------------------------------------------------------------
        ("App.Title",                  "TIA Portal Workbench", "TIA Portal 工作台"),
        ("Badge.NoVersion",            "TIA —", "TIA —"),
        ("Badge.Version",              "TIA {0}", "TIA {0}"),
        ("Theme.Light",                "Light", "浅色"),
        ("Theme.Dark",                 "Dark", "深色"),
        ("Theme.Auto",                 "Auto", "自动"),
        ("Theme.Switch",               "Appearance", "外观"),
        ("Lang.Switch",                "Language", "语言"),

        // ---- header actions --------------------------------------------------------
        ("Toolbar.Mock",               "Mock", "模拟"),
        ("Toolbar.Mock.Tip",           "Run against a synthetic project; no TIA Portal needed",
                                       "使用合成项目运行,无需安装 TIA Portal"),
        ("Toolbar.Headless",           "Headless", "无界面"),
        ("Toolbar.Headless.Tip",       "Start TIA Portal without its window. It cannot show the first-connect trust dialog.",
                                       "以无窗口方式启动 TIA Portal。它无法显示首次连接的信任对话框。"),
        ("Toolbar.Doctor",             "Doctor", "环境检查"),
        ("Toolbar.Doctor.Tip",         "Check every Openness precondition on this machine",
                                       "检查本机是否满足 Openness 的全部前置条件"),
        ("Toolbar.Connect",            "Connect", "连接"),
        ("Toolbar.Connect.Tip",        "Start TIA Portal, or attach to one that is already running",
                                       "启动 TIA Portal,或附加到已在运行的实例"),
        ("Toolbar.Compile",            "Compile", "编译"),
        ("Toolbar.Inspect",            "Inspect", "审查"),
        ("Toolbar.Import",             "Import…", "导入…"),
        ("Toolbar.Save",               "Save project", "保存项目"),
        ("Toolbar.Save.Tip",           "Write the project to disk. Cannot be undone.",
                                       "把项目写入磁盘,此操作不可撤销。"),

        // ---- project row -----------------------------------------------------------
        ("Project.Label",              "Project", "项目"),
        ("Project.Placeholder",        "Path to an .ap15_1 … .ap21 project file",
                                       ".ap15_1 / .ap21 项目文件的路径"),
        ("Common.Browse",              "Browse…", "浏览…"),
        ("Common.Open",                "Open", "打开"),
        ("Common.Reload",              "Refresh", "刷新"),

        // ---- sidebar ---------------------------------------------------------------
        ("Sidebar.Devices",            "Devices", "设备"),
        ("Sidebar.Empty",              "Devices will be listed here once you connect and open a project.",
                                       "连接并打开项目后\n此处将列出设备"),

        // ---- tabs ------------------------------------------------------------------
        ("Tab.Log",                    "Log", "日志"),

        // ---- blocks ----------------------------------------------------------------
        ("Blocks.Filter",              "Filter by group path...", "按组路径筛选..."),
        ("Blocks.Count",               "{0} block(s)", "共 {0} 个程序块"),
        ("Blocks.Selected",            "{0} of {1} selected", "已选择 {0}/{1}"),
        ("Blocks.Empty.Title",         "No project open", "尚未打开项目"),
        ("Blocks.Empty.Body",          "Press Connect. If TIA Portal is already running with a project open, that project is taken over and its blocks appear here — no path needed. Otherwise give a project path above and open it.",
                                       "点击\"连接\"。如果博途已在运行并且已打开项目,会直接接管那个项目,程序块随即出现在这里——不需要填路径。否则在上方填写项目路径再打开。"),
        ("Blocks.ExportTo",            "Export to", "导出到"),
        ("Blocks.SourceFormat",        "Source text", "源文本"),
        ("Blocks.SourceFormat.Tip",    "Export source through the native Openness adapter. Mock mode uses synthetic source text.",
                                      "通过本地 Openness 适配器导出源文件。模拟模式生成示例源文本。"),
        ("Blocks.Export",              "Export", "导出"),
        ("Block.Protected",            "know-how protected", "专有技术保护"),
        ("Block.NeedsCompiling",       "needs compiling", "需要先编译"),

        // The categories TIA splits a PLC's software into, named as TIA names them.
        ("Tree.ProgramBlocks",         "Program blocks", "程序块"),
        ("Tree.DataTypes",             "PLC data types", "PLC 数据类型"),
        ("Tree.Tags",                  "PLC tags", "PLC 变量"),
        ("Tree.HmiScreens",            "Screens", "画面"),

        // ---- version control -------------------------------------------------------
        ("Vc.NoWorkspace",             "No workspace selected. Create one over your Git working tree below.",
                                       "尚未选择工作区。请在下方基于 Git 工作树创建一个。"),
        ("Vc.New",                     "New", "新建"),
        ("Vc.In",                      "in", "位于"),
        ("Vc.Create",                  "Create", "创建"),
        ("Vc.Folder.Tip",              "An existing folder — normally your Git working tree",
                                       "一个已存在的文件夹 — 通常就是你的 Git 工作树"),
        ("Vc.ShowAll",                 "Show in-sync objects", "显示已同步的对象"),
        ("Vc.Empty.Title",             "No workspace yet", "尚无工作区"),
        ("Vc.Empty.Body",              "The Version Control Interface maps the project onto a folder, one text file per object. Availability depends on the project and installed Openness capabilities.",
                                       "版本控制接口会把项目映射到一个文件夹,每个对象一个文本文件。可用性取决于项目和已安装的 Openness 功能。"),
        ("Col.State",                  "State", "状态"),
        ("Col.Object",                 "Object", "对象"),
        ("Col.Format",                 "Format", "格式"),
        ("Vc.Diff.Empty",              "Select a changed object to see what it changed. The comparison is against the files, so push first.",
                                       "选中一个有差异的对象即可查看改动内容。比较的是文件,所以要先推送。"),
        ("Vc.Diff.Unchanged",          "{0}: no uncommitted change in the workspace file.",
                                       "{0}:工作区文件没有未提交的改动。"),

        // ---- log -------------------------------------------------------------------
        ("Log.Title",                  "Log", "日志"),
        ("Log.Copy",                   "Copy", "复制"),
        ("Log.Clear",                  "Clear", "清空"),

        // ---- status bar ------------------------------------------------------------
        ("Status.NotConnected",        "Not connected.", "未连接"),
        ("Status.HeadlessMode",        "Headless mode", "无界面模式"),
        ("Status.MockMode",            "Mock mode", "模拟模式"),
        ("Status.Working",             "{0}…", "{0}…"),
        ("Status.CheckingEnvironment", "Checking environment", "正在检查环境"),
        ("Status.Connecting",          "Connecting to TIA Portal", "正在连接 TIA Portal"),
        ("Status.OpeningProject",      "Opening project", "正在打开项目"),
        ("Status.ReadingBlocks",       "Reading blocks of {0}", "正在读取 {0} 的程序块"),
        ("Status.Exporting",           "Exporting", "正在导出"),
        ("Status.Importing",           "Importing", "正在导入"),
        ("Status.Compiling",           "Compiling", "正在编译"),
        ("Status.Inspecting",          "Inspecting", "正在审查"),
        ("Status.SavingProject",       "Saving project", "正在保存项目"),
        ("Status.ReadingVc",           "Reading version control", "正在读取版本控制"),
        ("Status.CreatingWorkspace",   "Creating workspace", "正在创建工作区"),
        ("Status.MappingProject",      "Mapping project", "正在映射项目"),
        ("Status.ComparingWorkspace",  "Comparing with workspace", "正在与工作区比较"),
        ("Status.Synchronizing",       "Synchronizing {0}", "正在同步 {0}"),
        ("Status.EnvOk",               "Environment OK.", "环境正常。"),
        ("Status.EnvNotReady",         "Environment not ready — see the log.", "环境未就绪 — 详见日志。"),
        ("Status.Connected",           "Connected ({0}, Openness {1}).", "已连接({0},Openness {1})。"),
        ("Status.ProjectOpen",         "Project {0} open.", "项目 {0} 已打开。"),
        ("Status.BlocksIn",            "{0} block(s) in {1}.", "{1} 中共 {0} 个程序块。"),
        ("Status.Exported",            "Exported {0}/{1} to {2}", "已导出 {0}/{1} 到 {2}"),
        ("Status.ExportedFailed",      "Exported {0}/{1} to {2} ({3} failed)", "已导出 {0}/{1} 到 {2}({3} 个失败)"),
        ("Status.Imported",            "Imported {0}/{1} file(s). Not saved yet.", "已导入 {0}/{1} 个文件。尚未保存。"),
        ("Status.CompileResult",       "{0}: {1} error(s), {2} warning(s) in {3}s",
                                       "{0}:{1} 个错误,{2} 个警告,耗时 {3} 秒"),
        ("Status.InspectResult",       "{0} finding(s) over {1} block(s).", "在 {1} 个程序块中发现 {0} 处问题。"),
        ("Status.ProjectSaved",        "Project saved.", "项目已保存。"),
        ("Status.VcUnsupported",       "This project exposes no Version Control Interface in the current installation.",
                                       "当前安装环境中的该项目未提供版本控制接口。"),
        ("Status.VcNoWorkspace",       "No workspace yet. Point one at your Git working tree and create it.",
                                       "还没有工作区。请指向你的 Git 工作树并创建一个。"),
        ("Status.VcWorkspaces",        "{0} workspace(s).", "共 {0} 个工作区。"),
        ("Status.VcInSync",            "{0} mapped object(s), all in sync — nothing to commit.",
                                       "已映射 {0} 个对象,全部同步 — 无需提交。"),
        ("Status.VcDiffer",            "{0} mapped object(s), {1} differ.", "已映射 {0} 个对象,其中 {1} 个存在差异。"),
        ("Status.VcCreated",           "Workspace created. Now map the project into it.",
                                       "工作区已创建。接下来把项目映射进去。"),
        ("Status.VcMapDry",            "Dry run: {0} would be mapped, {1} already, {2} unsupported. Clear Dry run to apply.",
                                       "预演:将映射 {0} 个,已映射 {1} 个,{2} 个不支持。取消勾选“预演”才会实际执行。"),
        ("Status.VcMapApplied",        "Mapped {0}, already {1}, unsupported {2}, failed {3}.",
                                       "已映射 {0} 个,原已映射 {1} 个,不支持 {2} 个,失败 {3} 个。"),
        ("Status.VcSyncDry",           "Dry run: {0} would sync {1}, {2} already equal. Clear Dry run to apply.",
                                       "预演:将同步 {0} 个({1}),{2} 个已一致。取消勾选“预演”才会实际执行。"),
        ("Status.VcSyncApplied",       "{0} synchronized, {1} failed, {2} already equal.",
                                       "已同步 {0} 个,失败 {1} 个,{2} 个已一致。"),

        // ---- log lines -------------------------------------------------------------
        ("Log.BridgeStarted",          "bridge started ({0}).", "bridge 已启动({0})。"),
        ("Log.BridgeExited",           "bridge process exited.", "bridge 进程已退出。"),
        ("Log.EnvironmentHeader",      "--- environment ---", "--- 运行环境 ---"),
        ("Log.Installed",              "installed: V{0} {1}", "已安装:V{0} {1}"),
        ("Log.Attached",               "attached to an open project: {0}", "已附加到打开的项目:{0}"),
        ("Log.Opened",                 "opened {0} ({1})", "已打开 {0}({1})"),
        ("Log.DeviceCount",            "{0} device(s).", "共 {0} 个设备。"),
        ("Log.Failed",                 "FAILED {0}: {1}", "失败 {0}:{1}"),
        ("Log.Error",                  "error: {0}", "错误:{0}"),
        ("Log.InspectionHeader",       "--- inspection of {0} ---", "--- {0} 的审查结果 ---"),
        ("Log.WorkspaceCreated",       "created workspace {0} at {1}", "已创建工作区 {0},位置 {1}"),
        ("Log.CommitHint",             "Commit from {0}:  git add -A && git commit",
                                       "在 {0} 中提交:git add -A && git commit"),
        ("Log.PullHint",               "The project now holds the workspace's version — compile and save it.",
                                       "项目现在是工作区中的版本 — 请编译并保存。"),

        // ---- dialogs ---------------------------------------------------------------
        ("Dialog.OpenProject.Title",   "Open a TIA Portal project", "打开 TIA Portal 项目"),
        ("Dialog.OpenProject.Filter",  "TIA Portal projects|*.ap21;*.ap20;*.ap19;*.ap18;*.ap17;*.ap16;*.ap15_1|All files|*.*",
                                       "TIA Portal 项目|*.ap21;*.ap20;*.ap19;*.ap18;*.ap17;*.ap16;*.ap15_1|所有文件|*.*"),
        ("Dialog.Export.Title",        "Choose the export folder", "选择导出文件夹"),
        ("Dialog.Workspace.Title",     "Choose the workspace folder (your Git working tree)",
                                       "选择工作区文件夹(你的 Git 工作树)"),
        ("Dialog.Import.Title",        "Select blocks to import", "选择要导入的程序块"),
        ("Dialog.Import.Filter",       "Blocks and sources (*.xml;*.scl;*.db;*.udt)|*.xml;*.scl;*.db;*.udt",
                                      "程序块与源文件 (*.xml;*.scl;*.db;*.udt)|*.xml;*.scl;*.db;*.udt"),
        ("Dialog.Import.Caption",      "Import", "导入"),
        ("Dialog.Import.Text",         "Replace blocks that already exist in the project?\n\nNo  = fail on blocks that already exist (safer)\nYes = overwrite them",
                                       "是否替换项目中已存在的程序块?\n\n否 = 遇到已存在的块即失败(更安全)\n是 = 直接覆盖"),
        ("Dialog.Save.Caption",        "Save", "保存"),
        ("Dialog.Save.Text",           "Save the project to disk? This cannot be undone.",
                                       "确定把项目保存到磁盘吗?此操作不可撤销。"),
        ("Dialog.Pull.Caption",        "Restore from workspace", "从工作区恢复"),
        ("Dialog.Pull.Text",           "Read the workspace's text files back INTO the project?\n\nThis OVERWRITES blocks in the open project and cannot be undone.\nCompile and save afterwards.",
                                       "确定把工作区的文本文件读回项目吗?\n\n这会覆盖已打开项目中的程序块,且不可撤销。\n完成后请编译并保存。"),
        ("Dialog.Error.Caption",       "Unexpected error", "未预期的错误"),
        ("Dialog.Error.Details",       "Details written to {0}", "详细信息已写入 {0}"),
    ];

    public static readonly IReadOnlyDictionary<string, string> English = Build(static e => e.En);

    public static readonly IReadOnlyDictionary<string, string> Chinese = Build(static e => e.Zh);

    private static IReadOnlyDictionary<string, string> Build(Func<(string Key, string En, string Zh), string> pick)
    {
        var table = new Dictionary<string, string>(Catalogue.Length, StringComparer.Ordinal);
        foreach (var entry in Catalogue) table[entry.Key] = pick(entry);
        return table;
    }
}
