using System;
using System.Linq;
using System.Text.Json.Nodes;
using Siemens.Engineering.SW.Blocks;
using Siemens.Engineering.SW.ExternalSources;
using Siemens.Engineering.SW.Loader;
using Siemens.Engineering.SW.Units;
using TiaMcpServer.ModelContextProtocol;
using Siemens.Engineering;
using Siemens.Engineering.SW.Tags;

namespace TiaMcpServer.Siemens.Services
{
    internal sealed class NativeExchangeService
    {
        private readonly IEngineeringSession _session;

        public NativeExchangeService(IEngineeringSession session) => _session = session;

        public ResponseMessage CreatePlcInstanceDb(string softwarePath, string fbPath, string name, string groupPath = "", bool autoNumber = true, int number = 0, bool dryRun = true)
            => _session.RunHmiStepTool("CreatePlcInstanceDb", meta => {
                if (EngineeringGroupOperations.Parts(name).Length != 1 || number < 0) throw new ArgumentException("Single DB name and nonnegative number required.");
                using var access = dryRun ? null : _session.AcquireHmiEditAccess();
                var plc = _session.ExactPlcForEngineering(softwarePath, !dryRun);
                var fb = _session.ExactMasterCopyPlcSource(softwarePath, fbPath, true) as FB ?? throw new ArgumentException("fbPath must identify an FB, not an FC or DB.");
                var group = (PlcBlockGroup)EngineeringGroupOperations.Group(plc.BlockGroup, groupPath);
                if (group.Blocks.Find(name) != null) throw new InvalidOperationException("Destination DB name already exists.");
                meta["dryRun"] = dryRun; meta["mayHaveChanged"] = false; meta["fbPath"] = fbPath; meta["groupPath"] = groupPath; meta["name"] = name;
                if (!dryRun)
                {
                    meta["mayHaveChanged"] = true;
                    // Native project evidence: CreateInstanceDB(name, true, 0, fb) created "DB0" and compilation rejected "invalid number 0".
                    // Auto-numbering needs a valid seed, so 1 is passed and TIA assigns the free number.
                    // See docs/reference/real-machine-ledger.md for native acceptance evidence.
                    var db = group.Blocks.CreateInstanceDB(name, autoNumber, autoNumber && number < 1 ? 1 : number, fb.Name);
                    if (db == null || group.Blocks.Find(name) == null) throw new InvalidOperationException("Native instance DB not found after creation.");
                    meta["after"] = EngineeringScalarProperties.Read(db);
                }
                return dryRun ? "Native instance DB creation preview; no XML synthesized." : "Instance DB created using the selected FB name; no save/compile/download.";
            });

        public ResponseMessage GeneratePlcSourceFromBlocks(string softwarePath, string blockPathsJson, string filePath, bool dryRun = true)
            => _session.RunHmiStepTool("GeneratePlcSourceFromBlocks", meta => {
                var names = _session.ExactNameList(blockPathsJson); var file = NativeFileOutput.Plan(filePath);
                var plc = _session.ExactPlcForEngineering(softwarePath, false);
                var blocks = names.Select(n => _session.ExactMasterCopyPlcSource(softwarePath, n, true) as IGenerateSource ?? throw new NotSupportedException("Block does not support native source generation: " + n)).ToArray();
                meta["dryRun"] = dryRun; meta["mayHaveWrittenFiles"] = false; meta["blockPaths"] = JsonNode.Parse(blockPathsJson); meta["filePath"] = file.FullName;
                if (!dryRun)
                {
                    meta["mayHaveWrittenFiles"] = true;
                    plc.ExternalSourceGroup.GenerateSource(blocks, file);
                    meta["file"] = NativeFileOutput.Verify(file); meta["apiCallSuccess"] = true;
                }
                return dryRun ? "Native source generation preview." : "Source file generated by TIA from selected blocks and hashed; no project save/compile/download.";
            });

        public ResponseMessage GeneratePlcLoadableFile(string softwarePath, string objectPathsJson, string objectKind, string targetOption, string filePath, bool dryRun = true)
            => _session.RunHmiStepTool("GeneratePlcLoadableFile", meta => {
                if (objectKind == "block" || objectKind == "unit") objectKind += "s";
                if (objectKind != "blocks" && objectKind != "units") throw new ArgumentException("objectKind must be blocks/units.");
                var names = _session.ExactNameList(objectPathsJson); var file = NativeFileOutput.Plan(filePath);
                var plc = _session.ExactPlcForEngineering(softwarePath, false);
                if (!Enum.GetNames(typeof(TargetOption)).Contains(targetOption)) throw new ArgumentException("targetOption must be one of: " + string.Join("/", Enum.GetNames(typeof(TargetOption))) + " (Siemens.Engineering.SW.Loader.TargetOption).");
                var option = (TargetOption)EngineeringScalarProperties.ConvertValue(JsonValue.Create(targetOption), typeof(TargetOption))!;
                var service = plc.GetService<LoadableProvider>() ?? throw new NotSupportedException("LoadableProvider unavailable.");
                var blocks = objectKind == "blocks" ? names.Select(n => (PlcBlock)_session.ExactMasterCopyPlcSource(softwarePath, n, true)).ToArray() : Array.Empty<PlcBlock>();
                var unitRoot = objectKind == "units" ? plc.GetService<PlcUnitProvider>()?.UnitGroup.Units : null;
                var units = objectKind == "units" ? names.Select(n => unitRoot?.Find(n) ?? throw new InvalidOperationException("Exact software unit not found: " + n)).ToArray() : Array.Empty<PlcUnit>();
                meta["dryRun"] = dryRun; meta["mayHaveWrittenFiles"] = false; meta["targetOption"] = targetOption; meta["objectPaths"] = JsonNode.Parse(objectPathsJson);
                if (!dryRun)
                {
                    meta["mayHaveWrittenFiles"] = true;
                    if (objectKind == "blocks") service.GenerateLoadable(file, blocks, option); else service.GenerateLoadable(file, units, option);
                    meta["file"] = NativeFileOutput.Verify(file); meta["apiCallSuccess"] = true;
                }
                return dryRun ? "Loadable generation preview; no PLC contacted." : "Loadable file generated and hashed. Not downloaded; deployment/readiness not asserted.";
            });

        public ResponseMessage ManagePlcTagDefinition(string softwarePath, string tablePath, string name, string kind, string action, string dataType="", string addressOrValue="", string propertiesJson="{}", bool dryRun=true)
            => _session.RunHmiStepTool("ManagePlcTagDefinition", meta => {
                var request=PlcTagEditingLogic.Validate(action,kind,name,dataType,addressOrValue,propertiesJson,dryRun);
                bool writing=request.Writes;
                using var access=writing ? _session.AcquireHmiEditAccess() : null;
                var plc=_session.ExactPlcForEngineering(softwarePath,writing);
                var parts=EngineeringGroupOperations.Parts(tablePath);
                var group=EngineeringGroupOperations.Group(plc.TagTableGroup,string.Join("/",parts.Take(parts.Length-1)));
                var table=(PlcTagTable)(EngineeringGroupOperations.Find(EngineeringGroupOperations.Get(group,"TagTables"),parts.Last()) ?? throw new InvalidOperationException("Exact PLC tag table not found."));
                object collection=kind=="tag" ? (object)table.Tags : table.UserConstants;
                var target=EngineeringGroupOperations.Find(collection,name);
                if((action=="create")== (target!=null)) throw new InvalidOperationException(action=="create" ? "Definition exists." : "Exact definition not found.");
                var nativeType=kind=="tag" ? typeof(PlcTag) : typeof(PlcUserConstant);
                var prepared=EngineeringScalarProperties.Prepare(nativeType,request.Scalars);
                meta["dryRun"]=dryRun; meta["mayHaveChanged"]=false; meta["tablePath"]=tablePath; meta["name"]=name; meta["kind"]=kind;
                if(target!=null) { meta["before"]=EngineeringScalarProperties.Read(target); meta["commentBefore"]=CommentItems(TagComment(target)); }
                // Comment is a MultilingualText - resolve the cultures now so a preview already reports a missing culture.
                var editingCulture=(_session.CurrentProject as Project)?.LanguageSettings?.EditingLanguage?.Culture?.Name;
                if(request.Comments.Length>0) { meta["commentCultures"]=new JsonArray(request.Comments.Select(c => JsonValue.Create(c.Culture ?? editingCulture ?? "(first item)")).ToArray()); }
                if(target!=null) foreach(var (culture,_) in request.Comments) ResolveCommentItem(TagComment(target),culture,editingCulture);
                if(!writing) return "PLC tag/constant read or preview. Native field validation occurs on execution; no modification.";
                meta["mayHaveChanged"]=true;
                if(action=="create") target=kind=="tag" ? (object)table.Tags.Create(name,dataType,addressOrValue) : table.UserConstants.Create(name,dataType,addressOrValue);
                if(action=="delete") {
                    EngineeringGroupOperations.Call(target!,"Delete",Type.EmptyTypes);
                    if(EngineeringGroupOperations.Find(collection,name)!=null) throw new InvalidOperationException("Definition remains after delete.");
                    meta["verifiedAbsent"]=true;
                } else {
                    EngineeringScalarProperties.Apply(target!,prepared,meta);
                    foreach(var (culture,text) in request.Comments) {
                        var item=ResolveCommentItem(TagComment(target!),culture,editingCulture);
                        meta["lastAttemptedProperty"]="Comment["+(item.Language?.Culture?.Name ?? "?")+"]";
                        item.Text=text;
                        if(item.Text!=text) throw new InvalidOperationException("Comment readback differs for culture "+(item.Language?.Culture?.Name ?? culture)+".");
                    }
                    meta["after"]=EngineeringScalarProperties.Read(target!); meta["commentAfter"]=CommentItems(TagComment(target!));
                }
                return "Native PLC tag/constant operation completed and read back. No save/compile/download or runtime value write.";
            });

        private static MultilingualText TagComment(object target)
            => target is PlcTag tag ? tag.Comment : target is PlcUserConstant constant ? constant.Comment : throw new InvalidOperationException("Unexpected definition type: "+target.GetType().FullName);

        private static JsonObject CommentItems(MultilingualText text)
        {
            var items=new JsonObject();
            foreach(var item in EngineeringGroupOperations.Items(text.Items).Cast<MultilingualTextItem>()) items[item.Language?.Culture?.Name ?? "?"]=item.Text;
            return items;
        }

        private static MultilingualTextItem ResolveCommentItem(MultilingualText text,string? culture,string? editingCulture)
        {
            var items=EngineeringGroupOperations.Items(text.Items).Cast<MultilingualTextItem>().ToList();
            var wanted=culture ?? editingCulture;
            var item=wanted==null ? items.FirstOrDefault() : items.FirstOrDefault(i => string.Equals(i.Language?.Culture?.Name,wanted,StringComparison.OrdinalIgnoreCase));
            return item ?? throw new PortalException(PortalErrorCode.NotFound,"Comment culture not active in the project: "+(wanted ?? "(none)")+" (active: "+string.Join(", ",items.Select(i => i.Language?.Culture?.Name))+"). Activate it with ManageProjectLanguage or pass Comment as {\"<active culture>\": \"text\"}.");
        }
    }
}
