<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)obj/$(TiaReleaseKey)/</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)bin/$(TiaReleaseKey)/</BaseOutputPath>
  </PropertyGroup>
</Project>
