using System.ComponentModel;
using ModelContextProtocol.Server;
namespace TiaMcpServer.ModelContextProtocol
{
    public static partial class McpServer
    {
        [McpServerTool(Name="ReadCommunicationConnections"), Description("[L2][Hardware][READ] List Siemens.Engineering.HW.CommunicationConnections (S7/ISO/ISO-on-TCP/TCP/UDP/FDL/PtP/HMI) owned by one exact hardware object (devicePathJson/itemPathJson JSON name arrays, e.g. the CPU). Scalar properties (LocalConnectionName, TSAPs, addresses, ports) plus local/partner target and interface names; offset/limit pagination. NotSupported on TIA V20. Nothing modified.")]
        public static ResponseMessage ReadCommunicationConnections(string devicePathJson,string itemPathJson="[]",int offset=0,int limit=100)
            => Portal.ReadCommunicationConnections(devicePathJson,itemPathJson,offset,limit);
        [McpServerTool(Name="ManageCommunicationConnection"), Description("[L2][Hardware][WRITE] Create or delete one communication connection on an exact owner DeviceItem. create: connectionType is one exact kind (S7Connection/IsoConnection/IsoOnTcpConnection/TcpConnection/UdpConnection/FdlConnection/PtpConnection/HmiConnection), localInterfaceItemPathJson + localNodeName (required when the interface has several nodes), partnerDevicePathJson/partnerItemPathJson (partner DeviceItem) and partnerInterfaceItemPathJson/partnerNodeName; optional connectionName is written to LocalConnectionName and verified. delete: exact LocalConnectionName (ambiguous names refused) and confirmDelete=true. Default preview; real run needs exclusive access. NotSupported on TIA V20. No save/compile/download.")]
        public static ResponseMessage ManageCommunicationConnection(string devicePathJson,string itemPathJson,string action,string connectionType="",string connectionName="",string localInterfaceItemPathJson="[]",string localNodeName="",string partnerDevicePathJson="[]",string partnerItemPathJson="[]",string partnerInterfaceItemPathJson="[]",string partnerNodeName="",bool confirmDelete=false,bool dryRun=true)
            => Portal.ManageCommunicationConnection(devicePathJson,itemPathJson,action,connectionType,connectionName,localInterfaceItemPathJson,localNodeName,partnerDevicePathJson,partnerItemPathJson,partnerInterfaceItemPathJson,partnerNodeName,confirmDelete,dryRun);
        [McpServerTool(Name="ManageWatchForceTableWebAccess"), Description("[L2][Hardware][WRITE] Read/assign/unassign web-server access rules for PLC watch/force tables (WatchAndForceTableAccessManager on the exact CPU DeviceItem). read lists both rule sets. assign/unassign need softwarePath (exact PLC, must be Offline for a real run), tableKind watch|force, exact tablePath (group/table), access None|Read|Write and confirmChange=true. Existing rule with read-only Access is refused (unassign first). Default preview; readback verified; no save/compile/download.")]
        public static ResponseMessage ManageWatchForceTableWebAccess(string devicePathJson,string itemPathJson,string action="read",string softwarePath="",string tableKind="watch",string tablePath="",string access="Read",bool confirmChange=false,bool dryRun=true)
            => Portal.ManageWatchForceTableWebAccess(devicePathJson,itemPathJson,action,softwarePath,tableKind,tablePath,access,confirmChange,dryRun);
        [McpServerTool(Name="ExchangeSystemDiagnosticsSettings"), Description("[L2][Hardware][FILE] Export/import system diagnostics settings via SystemdiagnosticsSettingsDataProvider (project-level by default; optional exact devicePathJson/itemPathJson owner). export writes a NEW absolute file and returns its sha256; import needs an existing absolute file and confirmImport=true. Native result state attached; Error state fails the tool. Default preview; no save/compile/download.")]
        public static ResponseMessage ExchangeSystemDiagnosticsSettings(string action,string filePath,string devicePathJson="[]",string itemPathJson="[]",bool confirmImport=false,bool dryRun=true)
            => Portal.ExchangeSystemDiagnosticsSettings(action,filePath,devicePathJson,itemPathJson,confirmImport,dryRun);
        [McpServerTool(Name="ReadOpcUaAccessControl"), Description("[L2][PLC-OpcUA][READ] Read the PLC OPC UA server access control (ServerInterfaceGroup.AccessControl): section roles (RoleMappings with per-namespace permissions) or restrictions (NamespaceAccessRestrictions). Exact softwarePath; offset/limit pagination. NotSupported on TIA V20. No secrets, nothing modified.")]
        public static ResponseMessage ReadOpcUaAccessControl(string softwarePath,string section="roles",int offset=0,int limit=100)
            => Portal.ReadOpcUaAccessControl(softwarePath,section,offset,limit);
        [McpServerTool(Name="ManageOpcUaAccessControl"), Description("[L2][PLC-OpcUA][WRITE] Modify PLC OPC UA server access control: createRole (roleName, definedInNamespace), addStandardRole (roleName), deleteRole (roleName), setProjectRole (roleName, projectRole), setPermission (roleName, exact namespaceUri, permission Browse|Read|Write|Call|ReceiveEvents|ReadRolePermissions, enabled), setRestriction (exact namespaceUri, propertiesJson of scalar properties). Exact names only; ambiguity refused. Real run needs confirmChange=true, Offline PLC and exclusive access; readback verified. NotSupported on TIA V20. Default preview; no save/compile/download.")]
        public static ResponseMessage ManageOpcUaAccessControl(string softwarePath,string action,string roleName="",string definedInNamespace="",string projectRole="",string namespaceUri="",string permission="",bool enabled=false,string propertiesJson="{}",bool confirmChange=false,bool dryRun=true)
            => Portal.ManageOpcUaAccessControl(softwarePath,action,roleName,definedInNamespace,projectRole,namespaceUri,permission,enabled,propertiesJson,confirmChange,dryRun);
        [McpServerTool(Name="ImportDeviceAml"), Description("[L2][Hardware][FILE] Import an AutomationML/CAx (.aml) file into the open project via CaxProvider.Import(file, logFile, option). filePath must exist (absolute); logFilePath is a NEW absolute file; importOption RetainTiaDevice|OverwriteTiaDevice|MoveToParkingLot. May add or replace devices; real run needs confirmImport=true and exclusive access. Returns native bool result, device counts and the log file sha256. Default preview; no save/compile/download.")]
        public static ResponseMessage ImportDeviceAml(string filePath,string logFilePath,string importOption="RetainTiaDevice",bool confirmImport=false,bool dryRun=true)
            => Portal.ImportDeviceAml(filePath,logFilePath,importOption,confirmImport,dryRun);
        [McpServerTool(Name="ReadHardwareFeatures"), Description("[L2][Hardware][READ] Probe every Siemens.Engineering.HW.Features.* service from the V21 API catalog on one exact hardware object (devicePathJson/itemPathJson): reports advertised services, present/absent per feature and public scalar values (credential-related features report presence only). offset/limit pagination. Read-only.")]
        public static ResponseMessage ReadHardwareFeatures(string devicePathJson,string itemPathJson="[]",int offset=0,int limit=100)
            => Portal.ReadHardwareFeatures(devicePathJson,itemPathJson,offset,limit);
    }
}
