using System.ComponentModel;
using ModelContextProtocol.Server;
namespace TiaMcpServer.ModelContextProtocol
{
    public static partial class McpServer
    {
        [McpServerTool(Name="SetPlcUnitObjectAccess"), Description("[L2][PLC-Software][WRITE] Publish/unpublish a block or PLC type inside an exact software unit using official Access attribute. access=Published/Unpublished. objectPath includes nested groups relative to the unit's block/type root; OB publication is refused by native API. dryRun=true default; writes require Offline and readback. No save/compile/download.")]
        public static ResponseMessage SetPlcUnitObjectAccess(string softwarePath,string unitName,string objectKind,string objectPath,string access,bool dryRun=true)
            => Portal.SetPlcUnitObjectAccess(softwarePath,unitName,objectKind,objectPath,access,dryRun);
        [McpServerTool(Name="ManagePlcSafety"), Description("[L2][Safety][WRITE] Offline Safety read/createRuntimeGroup/deleteRuntimeGroup/updateRuntimeGroup/updateSettings via official optional Safety API. Exact PLC and runtimeGroup. Scalar propertiesJson for updates. dryRun=true default. Existing TIA Safety login required when protected; no credentials, safety-mode disabling, compile/save/download or automatic login. Read includes settings, runtime groups and available signature metadata; API availability is not functional safety acceptance.")]
        public static ResponseMessage ManagePlcSafety(string softwarePath,string action="read",string runtimeGroup="",string propertiesJson="{}",bool dryRun=true)
            => Portal.ManagePlcSafety(softwarePath,action,runtimeGroup,propertiesJson,dryRun);
        [McpServerTool(Name="ManagePlcCertificate"), Description("[L2][Security][WRITE] Offline engineering certificate list/read/create/import/export/delete/assign/unassign. Exact devicePathJson and itemPathJson segments; selected item must expose LocalCertificateManager. Exact certificateId. Create requires usage enum and scalar template propertiesJson; filePath for import/export. Assignment=WebserverCertificate/OpcUaServerCertificate on selected owner. dryRun=true default. No password/private-key export/download/save; export refuses overwrite.")]
        public static ResponseMessage ManagePlcCertificate(string devicePathJson,string itemPathJson,string action,string certificateId="",string filePath="",string usage="",string propertiesJson="{}",string assignment="",bool dryRun=true,string assignmentItemPathJson="")
            => Portal.ManagePlcCertificate(devicePathJson,itemPathJson,action,certificateId,filePath,usage,propertiesJson,assignment,dryRun,assignmentItemPathJson);
        [McpServerTool(Name="ManageLibraryTypeVersion"), Description("[L2][Library][WRITE] Exact library type/version read/edit/release/setDefault/deleteVersion/updateInstances. Empty libraryName selects project library; otherwise unique already-open global library. typePath relative to TypeFolder. Release requires newVersion and official dependenciesMode. updateInstances requires exact targetSoftwarePath; native type update chooses its applicable versions, not necessarily version argument. dryRun=true default. No export, save, close or compile. Semantic validity/dependency impact determined by native TIA.")]
        public static ResponseMessage ManageLibraryTypeVersion(string typePath,string version,string action,string libraryName="",string newVersion="",string dependenciesMode="",string author="",string comment="",string targetSoftwarePath="",bool dryRun=true)
            => Portal.ManageLibraryTypeVersion(typePath,version,action,libraryName,newVersion,dependenciesMode,author,comment,targetSoftwarePath,dryRun);
        [McpServerTool(Name="CreateLibraryMasterCopy"), Description("[L2][Library][WRITE] Create a native master copy from an exact block/type/device/screen in an existing library folder. sourcePath is relative object path; for device use JSON array of exact group/station names. Empty libraryName=project library; otherwise already-open global library. dryRun=true default. Native IMasterCopySource required; no automatic save or close.")]
        public static ResponseMessage CreateLibraryMasterCopy(string sourceKind,string sourcePath,string softwarePath="",string folderPath="",string libraryName="",bool dryRun=true)
            => Portal.CreateLibraryMasterCopy(sourceKind,sourcePath,softwarePath,folderPath,libraryName,dryRun);
        [McpServerTool(Name="ManageHardwareObject"), Description("[L2][Hardware][WRITE] Native deleteDevice/deleteItem/moveItem/copyItem. devicePathJson=[group,...,station] or [unique exact station name]; itemPathJson lists exact child names, preserving slashes in names. Move/copy require destinationDevicePathJson,destinationItemPathJson,position and pass native CanPlug check. dryRun=true default. Deletes may remove contained software. No save/download/online control.")]
        public static ResponseMessage ManageHardwareObject(string devicePathJson,string action,string itemPathJson="[]",string destinationDevicePathJson="[]",string destinationItemPathJson="[]",int position=-1,bool dryRun=true)
            => Portal.ManageHardwareObject(devicePathJson,action,itemPathJson,destinationDevicePathJson,destinationItemPathJson,position,dryRun);
        [McpServerTool(Name="ImportPlcWatchTableOffline"), Description("[L2][PLC-Software][WRITE] Import native SimaticML watch tables into an exact existing group. Offline-only, no overwrite. Rejects force-table and mixed-object XML and DTD. dryRun=true default. Does not execute modify values, start monitoring, save or download. filePath is on the MCP server.")]
        public static ResponseMessage ImportPlcWatchTableOffline(string softwarePath,string filePath,string groupPath="",bool dryRun=true)
            => Portal.ImportPlcWatchTableOffline(softwarePath,filePath,groupPath,dryRun);
        [McpServerTool(Name="ManageTechnologyObject"), Description("[L2][PLC-Software][WRITE] Native technology object read/create/delete/setParameter. Exact objectPath relative to TechnologicalObjectGroup, including user folders. create requires official typeIdentifier and version. setParameter takes exact parameter name and scalar valueJson. dryRun=true default; writes require Offline. No save/compile/download; dependencies not analyzed.")]
        public static ResponseMessage ManageTechnologyObject(string softwarePath,string objectPath,string action,string typeIdentifier="",string version="",string parameter="",string valueJson="null",bool dryRun=true)
            => Portal.ManageTechnologyObject(softwarePath,objectPath,action,typeIdentifier,version,parameter,valueJson,dryRun);
        [McpServerTool(Name="ManagePlcSoftwareUnit"), Description("[L2][PLC-Software][WRITE] Native Software Unit list/read/create/delete/update/createRelation/deleteRelation. Exact name; relatedUnit and official relationType for relations. update accepts writable scalar propertiesJson, excludes Name. dryRun=true default; actual writes require Offline. Delete includes contained objects. No save/compile/download or implicit publication of objects.")]
        public static ResponseMessage ManagePlcSoftwareUnit(string softwarePath,string action,string name="",string relatedUnit="",string relationType="",string propertiesJson="{}",bool dryRun=true)
            => Portal.ManagePlcSoftwareUnit(softwarePath,action,name,relatedUnit,relationType,propertiesJson,dryRun);
    }
}
