using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using Siemens.Engineering;
using Siemens.Engineering.SW;
using Siemens.Engineering.SW.Blocks;
using Siemens.Engineering.SW.ExternalSources;
using Siemens.Engineering.SW.Tags;
using TiaMcp.Adapters.Contracts;
using TiaMcp.Adapters.Hardware;
namespace TiaMcp.Adapters.Native.Plc
{
    public sealed partial class PlcOrganisationAdapter
    {
#if PLC_SOFTWARE_PROTECTION
        public HardwareAddressingReply CreatePlcInstanceDb(string softwarePath, string fbPath, string name, string groupPath = "", bool autoNumber = true, int number = 0, bool dryRun = true)
            => _session.RunHmiStepTool("CreatePlcInstanceDb", meta => {
                if (PlcGroupOperations.Parts(name).Length != 1 || number < 0) throw new ArgumentException("Single DB name and nonnegative number required.");
                using var access = dryRun ? null : _session.AcquireHmiEditAccess();
                var plc = _session.ExactPlcForEngineering(softwarePath, !dryRun);
                var fb = _session.ExactMasterCopyPlcSource(softwarePath, fbPath, true) as FB ?? throw new ArgumentException("fbPath must identify an FB, not an FC or DB.");
                var group = (PlcBlockGroup)PlcGroupOperations.Group(plc.BlockGroup, groupPath);
                if (group.Blocks.Find(name) != null) throw new InvalidOperationException("Destination DB name already exists.");
                meta["dryRun"] = dryRun; meta["mayHaveChanged"] = false; meta["fbPath"] = fbPath; meta["groupPath"] = groupPath; meta["name"] = name;
                if (!dryRun)
                {
                    meta["mayHaveChanged"] = true; MutationStarted = true;
                    // Native project evidence: CreateInstanceDB(name, true, 0, fb) created "DB0" and compilation rejected "invalid number 0".
                    // Auto-numbering needs a valid seed, so 1 is passed and TIA assigns the free number.
                    // See docs/reference/real-machine-ledger.md for native acceptance evidence.
                    var db = group.Blocks.CreateInstanceDB(name, autoNumber, autoNumber && number < 1 ? 1 : number, fb.Name);
                    if (db == null || group.Blocks.Find(name) == null) throw new InvalidOperationException("Native instance DB not found after creation.");
                    meta["after"] = HardwareScalarEvidence.Read(db);
                }
                return dryRun ? "Native instance DB creation preview; no XML synthesized." : "Instance DB created using the selected FB name; no save/compile/download.";
            });

#else
        public HardwareAddressingReply CreatePlcInstanceDb(string softwarePath, string fbPath, string name, string groupPath = "", bool autoNumber = true, int number = 0, bool dryRun = true)
            => throw new NotSupportedException("CreateInstanceDB requires V15.1 or later.");
#endif
        public HardwareAddressingReply GeneratePlcSourceFromBlocks(string softwarePath, string[] blockPaths, string filePath, bool dryRun = true, string validationError = "")
            => _session.RunHmiStepTool("GeneratePlcSourceFromBlocks", meta => {
                if (validationError.Length != 0) throw new ArgumentException(validationError);
                var names = blockPaths; var file = PlcSourceFileOutput.Plan(filePath);
                var plc = _session.ExactPlcForEngineering(softwarePath, false);
                var blocks = names.Select(n => _session.ExactMasterCopyPlcSource(softwarePath, n, true) as IGenerateSource ?? throw new NotSupportedException("Block does not support native source generation: " + n)).ToArray();
                meta["dryRun"] = dryRun; meta["mayHaveWrittenFiles"] = false; meta["blockPaths"] = blockPaths; meta["filePath"] = file.FullName;
                if (!dryRun)
                {
                    meta["mayHaveWrittenFiles"] = true;
                    plc.ExternalSourceGroup.GenerateSource(blocks, file);
                    meta["file"] = PlcSourceFileOutput.Verify(file); meta["apiCallSuccess"] = true;
                }
                return dryRun ? "Native source generation preview." : "Source file generated by TIA from selected blocks and hashed; no project save/compile/download.";
            });

        public HardwareAddressingReply UpdatePlcProgram(string softwarePath, bool confirmUpdate = false, bool dryRun = true)
            => _session.RunHmiStepTool("SetPlcProgram", meta => {
                bool writing = !dryRun;
                if (writing && !confirmUpdate) throw new ArgumentException("Real program update requires confirmUpdate=true besides dryRun=false.");
                using var access = writing ? _session.AcquireHmiEditAccess() : null;
                var plc = _session.ExactPlcForEngineering(softwarePath, writing);
                var method = plc.GetType().GetMethod("UpdateProgram", Type.EmptyTypes) ?? throw new NotSupportedException("PlcSoftware.UpdateProgram() unavailable.");
                meta["dryRun"] = dryRun; meta["mayHaveChanged"] = false; meta["softwarePath"] = softwarePath;
                meta["nativeReturnType"] = method.ReturnType.FullName;
                meta["before"] = HardwareScalarEvidence.Read(plc);
                if (!writing) return "PLC program update preview; no native call.";
                meta["mayHaveChanged"] = true; MutationStarted = true;
                var result = method.Invoke(plc, null);
                meta["apiCallSuccess"] = true; meta["nativeResult"] = result == null ? null : HardwareScalarEvidence.Read(result);
                meta["after"] = HardwareScalarEvidence.Read(plc);
                meta["readbackVerified"] = false; meta["readbackScope"] = "UpdateProgram returns void; program content changes are not enumerated by this tool.";
                return "Native PlcSoftware.UpdateProgram returned; no save/compile/download.";
            });

        private static Dictionary<string, object?> ConstantRow(PlcConstant constant, string kind) => new Dictionary<string, object?> { ["name"] = constant.Name, ["dataTypeName"] = constant.DataTypeName, ["value"] = constant.Value, ["kind"] = kind, ["constantClass"] = constant.GetType().Name };

        public HardwareAddressingReply ReadPlcTagTableConstants(string softwarePath, string tablePath, string kind = "all", string unitName = "", string unitKind = "unit", int offset = 0, int limit = 200)
            => _session.RunHmiStepTool("GetPlcTagTableConstants", meta => {
                ValidateConstants(tablePath, kind, unitName, unitKind, offset, limit);
                var plc = _session.ExactPlcForEngineering(softwarePath, false);
                var unit = _session.OptionalUnit(plc, unitName, unitKind);
                PlcTagTableSystemGroup root = unit == null ? plc.TagTableGroup : PlcOrganisationPrimitives.TagTableGroup(unit);
                var table = (PlcTagTable)_session.ExactObjectUnder(root, tablePath, "TagTables", "PLC tag table");
                PlcUserConstantComposition userConstants = table.UserConstants; PlcSystemConstantComposition systemConstants = table.SystemConstants;
                var rows = new List<object?>();
                if (kind != "system") rows.AddRange(PlcGroupOperations.Items(userConstants).Cast<PlcUserConstant>().Select(c => (object?)ConstantRow(c, "user")));
                if (kind != "user") rows.AddRange(PlcGroupOperations.Items(systemConstants).Cast<PlcSystemConstant>().Select(c => (object?)ConstantRow(c, "system")));
                meta["table"] = new Dictionary<string, object?> { ["name"] = table.Name, ["unit"] = unit == null ? null : PlcGroupOperations.Get(unit, "Name"), ["isDefault"] = table.IsDefault, ["userConstantCount"] = userConstants.Count, ["systemConstantCount"] = systemConstants.Count };
                Page(rows.ToArray(), offset, limit, meta);
                meta["apiCallSuccess"] = true;
                meta["scope"] = "PlcConstant Name / DataTypeName / Value of the table's UserConstants and SystemConstants; user constants are edited with ManagePlcTag kind=constant. No modification.";
                return "Tag table constants read; no modification.";
            });
        private static void ValidateConstants(string tablePath, string kind, string unitName, string unitKind, int offset, int limit)
        {
            if (string.IsNullOrWhiteSpace(tablePath) || tablePath.Length > 1024 || tablePath.Trim() != tablePath) throw new ArgumentException("Exact nonempty tablePath required (max 1024 chars, no surrounding whitespace).");
            if (kind != "all" && kind != "user" && kind != "system") throw new ArgumentException("kind must be one of: all/user/system (case-sensitive).");
            if (!string.IsNullOrEmpty(unitName) && unitKind != "unit" && unitKind != "safety") throw new ArgumentException("unitKind must be one of: unit/safety (case-sensitive).");
            if (offset < 0 || limit < 1 || limit > 500) throw new ArgumentException("offset>=0, limit 1..500 required.");
        }
        private static void Page(object?[] rows, int offset, int limit, Dictionary<string, object?> meta)
        {
            var page = rows.Skip(offset).Take(limit).ToArray();
            meta["records"] = page; meta["expectedCount"] = rows.Length; meta["actualCount"] = page.Length;
            meta["offset"] = offset; meta["limit"] = limit;
            meta["nextOffset"] = offset + page.Length < rows.Length ? (int?)(offset + page.Length) : null;
            meta["truncated"] = offset + page.Length < rows.Length;
        }
    }
}
