using System.Text.Json.Nodes;
using TiaMcp.BuildCommon;
using TiaMcp.ReleaseTool;
using Xunit;

namespace TiaMcp.ReleaseTool.Tests;

[Trait("Category", "StaticChecks")]
public sealed class RatchetPolicyTests
{
    private static CommandResult Run(StaticTree tree, string kind, params string[] args) => ReleaseCommands.RunStaticCaptured("check-ratchet", ["-Root", tree.Root, "-Kind", kind, "-Baseline", Path.Combine(tree.Root, "baseline.json"), .. args]);
    private static void Roots(StaticTree tree) { foreach (var name in SourceCheck.Roots) Directory.CreateDirectory(Path.Combine(tree.Root, name)); }
    [Theory]
    [InlineData("swallowed", "try { A(); } catch { }")]
    [InlineData("comments", "// 2.0: old")]
    [InlineData("envelopes", "x[\"timestamp\"] = DateTime.Now; x[\"success\"] = true;")]
    public void RatchetsPreserveBytesOnGrowthAndAcceptMovesAndShrink(string kind, string source)
    {
        using var tree = new StaticTree(); Roots(tree);
        var path = tree.Write("src/Engine/A.cs", source);
        Assert.Equal(0, Run(tree, kind, "-UpdateBaseline", "-AllowGrowth").ExitCode);
        var baseline = Path.Combine(tree.Root, "baseline.json"); var bytes = File.ReadAllBytes(baseline);
        Assert.Equal(0, Run(tree, kind).ExitCode);
        tree.Write("src/Engine/A.cs", source + "\n" + source);
        Assert.Equal(1, Run(tree, kind).ExitCode);
        Assert.Equal(1, Run(tree, kind, "-UpdateBaseline").ExitCode);
        Assert.Equal(bytes, File.ReadAllBytes(baseline));
        tree.Write("src/Engine/A.cs", "\n" + source);
        File.Move(path, Path.Combine(tree.Root, "src/Engine/Moved.cs"));
        Assert.Equal(0, Run(tree, kind).ExitCode);
        File.Delete(Path.Combine(tree.Root, "src/Engine/Moved.cs"));
        Assert.Equal(0, Run(tree, kind, "-UpdateBaseline").ExitCode);
        Assert.NotEqual(bytes, File.ReadAllBytes(baseline));
        Assert.Equal(64, Run(tree, kind, "-AllowGrowth").ExitCode);
    }
    [Theory]
    [InlineData("[]")]
    [InlineData("{\"format\":99,\"entries\":[],\"catches\":[],\"counts\":{}}")]
    [InlineData("{\"format\":1,\"entries\":[{}],\"catches\":[{}],\"counts\":{}}")]
    public void InvalidBaselinesFailEveryRatchet(string json)
    {
        using var tree = new StaticTree(); Roots(tree); tree.Write("baseline.json", json);
        foreach (var kind in RatchetChecks.Baselines.Keys) Assert.Equal(1, Run(tree, kind).ExitCode);
    }
    [Fact]
    public void McpReviewsAreExactAndCannotBlessNewSinksOrDuplicates()
    {
        using var tree = new StaticTree(); Roots(tree);
        tree.Write("src/Engine/A.cs", "NameZh = \"中文\";");
        Assert.Equal(1, Run(tree, "mcp-text", "-UpdateBaseline", "-AllowGrowth").ExitCode);
        var review = McpText.ScanSource("NameZh = \"中文\";", "src/Engine/A.cs", "Engine").Single();
        review["reason"] = "Reviewed bilingual table."; review["dataCategory"] = "bilingual-table";
        var reviewPath = tree.Write("reviews.json", new JsonArray(review.DeepClone()).ToJsonString());
        Assert.Equal(0, Run(tree, "mcp-text", "-UpdateBaseline", "-AllowGrowth", "-ReviewData", reviewPath).ExitCode);
        Assert.Equal(0, Run(tree, "mcp-text").ExitCode);
        var original = File.ReadAllBytes(Path.Combine(tree.Root, "baseline.json"));
        foreach (var changed in new[] { "Message = \"中文\";", "throw new Exception(\"中文\");", "NameZh = \"新增\";", "NameZh = \"中文\"; NameZh = \"中文\";" })
        {
            tree.Write("src/Engine/A.cs", changed); Assert.Equal(1, Run(tree, "mcp-text").ExitCode); Assert.Equal(1, Run(tree, "mcp-text", "-UpdateBaseline").ExitCode); Assert.Equal(original, File.ReadAllBytes(Path.Combine(tree.Root, "baseline.json")));
        }
        tree.Write("src/Engine/A.cs", "NameZh = \"中文\";");
        Assert.Equal(1, Run(tree, "mcp-text", "-UpdateBaseline", "-AllowGrowth").ExitCode);
        Assert.Equal(64, Run(tree, "mcp-text", "-ReviewData", reviewPath).ExitCode);
        var baseline = JsonNode.Parse(System.Text.Encoding.UTF8.GetString(original))!;
        foreach (var field in new[] { "reason", "cjk", "dataCategory", "fingerprint", "kind", "literal" })
        {
            var bad = baseline.DeepClone(); bad["allowlist"]![0]![field] = null;
            tree.Write("baseline.json", bad.ToJsonString()); Assert.Equal(1, Run(tree, "mcp-text").ExitCode);
        }
    }
    [Fact]
    public void SourceScanExclusionsAndMissingRootsMatchPython()
    {
        using var tree = new StaticTree(); Roots(tree);
        tree.Write("src/P/A.cs", "// 2.0: old");
        foreach (var name in new[] { "bin/A.cs", "obj/A.cs", "bin-v20/A.cs", "obj-v20/A.cs", "Generated/A.cs", "A.g.cs", "A.g.i.cs", "A.generated.cs", "A.designer.cs" }) tree.Write("src/P/" + name, "/* unterminated");
        tree.Write("src/P/Auto.cs", "// <auto-generated/>\n/* unterminated");
        var errors = new List<string>(); Assert.Single(SourceCheck.Sources(tree.Root, errors)); Assert.Empty(errors);
        errors.Clear(); Assert.Empty(SourceCheck.Sources(Path.Combine(tree.Root, "missing"), errors)); Assert.Equal(3, errors.Count);
        tree.Write("src/Studio/Gui/A.cs", "Message = \"中文\";");
        Assert.DoesNotContain(SourceCheck.Sources(tree.Root, [] , ui: false), s => s.Project == "Gui");
        foreach (var kind in RatchetChecks.Baselines.Keys) { tree.Write("src/P/A.cs", "\"unterminated"); Assert.Equal(1, Run(tree, kind, "-UpdateBaseline", "-AllowGrowth").ExitCode); }
    }
}
