"""Group actual release catalogs and compare official XML members with compiled native call sites.

Read-only against Siemens SDKs; emits identifiers and hashes, never copies SDK files.
Direct member-name references are evidence of compiled calls, not end-to-end tool coverage.
Overloads are counted separately in domainSignatures and together in domainMemberNames.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
KEYS = ['14sp1', '15.1', '16', '17', '18', '19', '20', '21']
BOILER = set('Equals GetHashCode ToString GetEnumerator Any Contains IndexOf CopyTo GetAttribute GetAttributes GetAttributeInfos SetAttribute SetAttributes GetComposition GetCompositionInfos GetInvocationInfos GetCreationInfos GetService GetServiceInfos Invoke Find Count Parent Dispose Clone CompareTo GetType MemberwiseClone Finalize Item'.split())


def read(path):
    return json.loads(path.read_text('utf-8-sig'))


def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', 'utf-8')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--public-api-root', type=Path, required=True)
    parser.add_argument('--output', type=Path, default=ROOT / 'bin-build/multi-version/api-audit')
    args = parser.parse_args()
    full = read(ROOT / 'manifest/tools-list.json')
    policy = (ROOT / 'src/Engine/Siemens/ToolVersionPolicy.cs').read_text('utf-8-sig').split('internal static string ToolProblem', 1)[0]
    v21only = set(re.findall(r'\["([^"]+)"\]\s*=', policy))
    names = {t['name'] for t in full['tools']}
    assert v21only <= names
    catalogs = {key: {t['name'] for t in read(ROOT / f'bin-build/multi-version/tools-{key}.json')['tools']} for key in KEYS[:6]}
    catalogs.update({'20': names - v21only, '21': names})
    union = set.union(*catalogs.values())
    groups = []
    for name in sorted(union):
        versions = [key for key in KEYS if name in catalogs[key]]
        groups.append({'name': name, 'releases': versions, 'group': 'all-releases' if len(versions) == 8 else 'release-only' if len(versions) == 1 else 'shared-subset',
                       'contract': 'shared-planner; profile-specific envelope' if name == 'PlanArtifactImportOrder' else 'consult selected host schema; equal names do not guarantee equal contracts'})
    version_record = {'schemaVersion': 1, 'basis': 'six host --catalog outputs, compiled full-engine roster and runtime-tested V20/V21 admission policy',
                      'nativeAcceptance': 'NOT RUN for the newly enabled targets',
                      'releases': {key: {'profile': 'full-engine' if key in ('20', '21') else 'plc-foundation', 'toolCount': len(catalogs[key]), 'tools': sorted(catalogs[key])} for key in KEYS},
                      'groupCounts': dict(Counter(t['group'] for t in groups)), 'tools': groups}
    write(ROOT / 'manifest/version-tools.json', version_record)
    lines = ['# Generated release tool catalog', '',
             'Generated by `Audit-VersionTools.py` from built catalogs. See [scope and contracts](version-tools.md).',
             'Groups compare tool names. Read the selected host schema; shared names do not certify identical parameters or native behavior.', '']
    for group, title in [('all-releases', 'All eight releases'), ('shared-subset', 'Shared by some releases'), ('release-only', 'One release only')]:
        selected = [t for t in groups if t['group'] == group]
        lines += [f'## {title} ({len(selected)})', '', '| Tool | Release keys |', '|---|---|']
        lines += [f'| `{t["name"]}` | {", ".join(t["releases"])} |' for t in selected]
        lines.append('')
    (ROOT / 'docs/reference/version-tool-catalog.md').write_text('\n'.join(lines), 'utf-8')
    statistics = []
    for key in KEYS:
        relative = {'14sp1': 'TIA_V14SP1_PublicAPI/V14 SP1', '15.1': 'TIA_V15.1_PublicAPI/V15.1', '21': 'TIA_V21_PublicAPI/V21/net48'}.get(key, f'TIA_V{key}_PublicAPI/V{key}')
        api = args.public_api_root / relative
        xml_files = sorted(p for p in api.glob('Siemens.Engineering*.xml') if '.AddIn' not in p.name)
        assert xml_files, f'No XML: {api}'
        signatures, members = set(), set()
        for path in xml_files:
            for element in ET.parse(path).iter('member'):
                signature = element.get('name', '')
                if not signature.startswith(('M:', 'P:')) or signature.startswith(('M:Siemens.Engineering.Private.', 'P:Siemens.Engineering.Private.')) or 'Siemens.Engineering.Compiler.CompileProvider' in signature:
                    continue
                stem = signature[2:].split('(', 1)[0]
                owner, _, member = stem.rpartition('.')
                if '#' in member or member in BOILER:
                    continue
                signatures.add(signature)
                members.add((signature[0], owner, member.split('``')[0]))
        if key in ('20', '21'):
            # Parallel release pipelines write per-version folders; older runs used the flat release folder.
            release_dir = ROOT / f'bin-build/releases/v{full["fileVersion"].rsplit(".", 1)[0]}'
            coverage = release_dir / f'v{key}' / f'native-call-coverage-v{key}.json'
            if not coverage.exists():
                coverage = release_dir / f'native-call-coverage-v{key}.json'
        else:
            coverage = ROOT / f'bin-build/multi-version/adapters/coverage-{key}.json'
        calls = set()
        for site in read(coverage)['sites']:
            match = re.search(r' (Siemens\.Engineering\.[^ ]+?)::([^\(]+)\(', site['member'])
            if not match:
                continue
            owner, member = match.groups()
            owner = re.sub(r'<.*>', '', owner).replace('/', '.')
            kind = 'P' if member.startswith(('get_', 'set_')) else 'M'
            if kind == 'P': member = member[4:]
            member = re.sub(r'<.*>', '', member)
            calls.add((kind, owner, member))
        observed = calls & members
        candidates = members - observed
        by_namespace = Counter(owner.rsplit('.', 1)[0] for _, owner, _ in candidates)
        row = {'releaseKey': key, 'mcpTools': len(catalogs[key]), 'xmlFiles': len(xml_files), 'domainSignatures': len(signatures), 'domainMemberNames': len(members),
               'compiledDirectMemberNames': len(observed), 'withoutDirectMemberReference': len(candidates), 'topCandidateNamespaces': sorted(by_namespace.items(), key=lambda item: (-item[1], item[0]))[:8],
               'sdkXmlSha256': {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in xml_files},
               'compiledCallInventorySha256': hashlib.sha256(coverage.read_bytes()).hexdigest()}
        statistics.append(row)
        write(args.output / f'api-candidates-{key}.json', {'releaseKey': key, 'caveat': 'No exact owner/member-name direct call found. Dynamic calls, inherited/generic targets and unadvertised adapter code require manual review. This is not a missing-tool count.',
                                                     'members': [f'{kind}:{owner}.{member}' for kind, owner, member in sorted(candidates)]})
    record = {'method': __doc__, 'nativeTiaExecuted': False, 'versions': statistics}
    write(ROOT / 'manifest/version-api-audit.json', record)
    print(json.dumps({'toolGroups': version_record['groupCounts'], 'releases': [{k: r[k] for k in ('releaseKey', 'mcpTools', 'domainSignatures', 'compiledDirectMemberNames', 'withoutDirectMemberReference')} for r in statistics]}, indent=2))


if __name__ == '__main__':
    main()
