using System;
using System.Linq;
using System.Text.Json.Nodes;
using Siemens.Engineering.SW.Blocks;
using Siemens.Engineering.SW.ExternalSources;
using Siemens.Engineering.SW.Loader;
using Siemens.Engineering.SW.Units;
using TiaMcpServer.ModelContextProtocol;

namespace TiaMcpServer.Siemens
{
    public partial class Portal
    {
        private static string[] ExactNameList(string json)
        {
            if (json.Length > 65536) throw new ArgumentException("Name list too large.");
            var names = (JsonNode.Parse(json) as JsonArray ?? throw new ArgumentException("Expected a JSON array of exact paths.")).Select(n => n!.GetValue<string>()).ToArray();
            if (names.Length < 1 || names.Length > 500 || names.Any(string.IsNullOrWhiteSpace) || names.Distinct(StringComparer.OrdinalIgnoreCase).Count() != names.Length) throw new ArgumentException("Provide 1..500 unique nonempty paths.");
            return names;
        }
        public ResponseMessage CreatePlcInstanceDb(string softwarePath, string fbPath, string name, string groupPath = "", bool autoNumber = true, int number = 0, bool dryRun = true)
            => RunHmiStepTool("CreatePlcInstanceDb", meta => {
                if (EngineeringGroupOperations.Parts(name).Length != 1 || number < 0) throw new ArgumentException("Single DB name and nonnegative number required.");
                using var access = dryRun ? null : AcquireHmiEditAccess();
                var plc = ExactPlcForEngineering(softwarePath, !dryRun);
                var fb = ExactMasterCopyPlcSource(softwarePath, fbPath, true) as FB ?? throw new ArgumentException("fbPath must identify an FB, not an FC or DB.");
                var group = (PlcBlockGroup)EngineeringGroupOperations.Group(plc.BlockGroup, groupPath);
                if (group.Blocks.Find(name) != null) throw new InvalidOperationException("Destination DB name already exists.");
                meta["dryRun"] = dryRun; meta["mayHaveChanged"] = false; meta["fbPath"] = fbPath; meta["groupPath"] = groupPath; meta["name"] = name;
                if (!dryRun)
                {
                    meta["mayHaveChanged"] = true;
                    var db = group.Blocks.CreateInstanceDB(name, autoNumber, number, fb.Name);
                    if (db == null || group.Blocks.Find(name) == null) throw new InvalidOperationException("Native instance DB not found after creation.");
                    meta["after"] = EngineeringScalarProperties.Read(db);
                }
                return dryRun ? "Native instance DB creation preview; no XML synthesized." : "Instance DB created using the selected FB name; no save/compile/download.";
            });
        public ResponseMessage GeneratePlcSourceFromBlocks(string softwarePath, string blockPathsJson, string filePath, bool dryRun = true)
            => RunHmiStepTool("GeneratePlcSourceFromBlocks", meta => {
                var names = ExactNameList(blockPathsJson); var file = NativeFileOutput.Plan(filePath);
                var plc = ExactPlcForEngineering(softwarePath, false);
                var blocks = names.Select(n => ExactMasterCopyPlcSource(softwarePath, n, true) as IGenerateSource ?? throw new NotSupportedException("Block does not support native source generation: " + n)).ToArray();
                meta["dryRun"] = dryRun; meta["mayHaveWrittenFiles"] = false; meta["blockPaths"] = JsonNode.Parse(blockPathsJson); meta["filePath"] = file.FullName;
                if (!dryRun)
                {
                    meta["mayHaveWrittenFiles"] = true;
                    plc.ExternalSourceGroup.GenerateSource(blocks, file);
                    meta["file"] = NativeFileOutput.Verify(file); meta["apiCallSuccess"] = true;
                }
                return dryRun ? "Native source generation preview." : "Source file generated by TIA from selected blocks and hashed; no project save/compile/download.";
            });
        public ResponseMessage GeneratePlcLoadableFile(string softwarePath, string objectPathsJson, string objectKind, string targetOption, string filePath, bool dryRun = true)
            => RunHmiStepTool("GeneratePlcLoadableFile", meta => {
                if (objectKind != "blocks" && objectKind != "units") throw new ArgumentException("objectKind must be blocks/units.");
                var names = ExactNameList(objectPathsJson); var file = NativeFileOutput.Plan(filePath);
                var plc = ExactPlcForEngineering(softwarePath, false);
                var option = (TargetOption)EngineeringScalarProperties.ConvertValue(JsonValue.Create(targetOption), typeof(TargetOption))!;
                var service = plc.GetService<LoadableProvider>() ?? throw new NotSupportedException("LoadableProvider unavailable.");
                var blocks = objectKind == "blocks" ? names.Select(n => (PlcBlock)ExactMasterCopyPlcSource(softwarePath, n, true)).ToArray() : Array.Empty<PlcBlock>();
                var unitRoot = objectKind == "units" ? plc.GetService<PlcUnitProvider>()?.UnitGroup.Units : null;
                var units = objectKind == "units" ? names.Select(n => unitRoot?.Find(n) ?? throw new InvalidOperationException("Exact software unit not found: " + n)).ToArray() : Array.Empty<PlcUnit>();
                meta["dryRun"] = dryRun; meta["mayHaveWrittenFiles"] = false; meta["targetOption"] = targetOption; meta["objectPaths"] = JsonNode.Parse(objectPathsJson);
                if (!dryRun)
                {
                    meta["mayHaveWrittenFiles"] = true;
                    if (objectKind == "blocks") service.GenerateLoadable(file, blocks, option); else service.GenerateLoadable(file, units, option);
                    meta["file"] = NativeFileOutput.Verify(file); meta["apiCallSuccess"] = true;
                }
                return dryRun ? "Loadable generation preview; no PLC contacted." : "Loadable file generated and hashed. Not downloaded; deployment/readiness not asserted.";
            });
    }
}
