using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaMcpServer.Siemens;
namespace TiaMcpServer.ModelContextProtocol
{
    public static partial class McpServer
    {
        [McpServerTool(Name="ReadClassicHmiScreenTree"), Description("[L2][HMI-Classic][READ] Typed folder tree of a classic (non-Unified) WinCC HMI device: ScreenSystemFolder / ScreenUserFolder (Screens, Folders), ScreenPopupSystemFolder / ScreenPopupUserFolder (ScreenPopups), ScreenTemplateSystemFolder / ScreenTemplateUserFolder (ScreenTemplates), ScreenSlideinSystemFolder (ScreenSlidein by SlideinType) plus ScreenOverview / ScreenGlobalElements presence. kind all/screens/popups/templates/slideins, optional folderPath under the family root, recursive to maxDepth; names only (first 500 per folder). Unified targets are refused. No modification.")]
        public static ResponseMessage ReadClassicHmiScreenTree(string softwarePath, string kind="all", string folderPath="", int maxDepth=4)
            => Portal.ReadClassicHmiScreenTree(softwarePath,kind,folderPath,maxDepth);
        [McpServerTool(Name="ManageClassicHmiScreenObject"), Description("[L2][HMI-Classic][WRITE] Classic WinCC screen objects beyond plain screens: objectKind popup (ScreenPopup: read / export / delete, objectPath folder/.../name), template (ScreenTemplate: read / export / delete), slidein (ScreenSlidein addressed by SlideinType Top/Bottom/Left/Right: read / export; no native Delete), overview (ScreenOverview: read / export / import) and globalElements (ScreenGlobalElements: read / export / import). export writes a NEW absolute XML file and hashes it; import (objectPath = target folder for popups / templates, importOptions None/Override) uses ScreenPopupComposition / ScreenTemplateComposition / ScreenSlideinComposition.Import or HmiTarget.ImportScreenOverview / ImportScreenGlobalElements and returns the imported names. Deletion and Override import need confirmDelete=true besides dryRun=false; every delete is verified by Find. No save/compile/download; plain screens stay with the screen tools.")]
        public static ResponseMessage ManageClassicHmiScreenObject(string softwarePath, string objectKind, string objectPath="", string action="read", string filePath="", string importOptions="None", bool confirmDelete=false, bool dryRun=true)
            => Portal.ManageClassicHmiScreenObject(softwarePath,objectKind,objectPath,action,filePath,importOptions,confirmDelete,dryRun);
        [McpServerTool(Name="ManageClassicHmiFolder"), Description("[L2][HMI-Classic][WRITE] Classic WinCC user folders of one family: folderKind screens (ScreenUserFolder), popups (ScreenPopupUserFolder), templates (ScreenTemplateUserFolder), tags (TagUserFolder; the TagSystemFolder row also names the DefaultTagTable) or scripts (VBScriptUserFolder). read returns the typed folder row (child names, one nested level); create adds newName under folderPath (empty = system folder) through the typed Folders.Create and reads it back; delete removes the empty user folder at folderPath (system folders and nonempty folders refused, confirmDelete=true). Default dryRun=true; no save/compile/download.")]
        public static ResponseMessage ManageClassicHmiFolder(string softwarePath, string folderKind, string folderPath="", string action="read", string newName="", bool confirmDelete=false, bool dryRun=true)
            => Portal.ManageClassicHmiFolder(softwarePath,folderKind,folderPath,action,newName,confirmDelete,dryRun);
        [McpServerTool(Name="ManageClassicHmiGraphic"), Description("[L2][HMI-Classic][WRITE] Multilingual graphics of a classic WinCC HMI device through the V21 GraphicsProvider service (MultiLingualGraphic): list, read, export (MultiLingualGraphic.Export writes a NEW XML file plus the image files beside it, per language with the 'default' suffix), import (MultiLingualGraphicComposition.Import, importOptions None/Override; graphics referenced by relative paths) and delete (confirmDelete=true, verified by Find). V20 answers NotSupported (no GraphicsProvider). Default dryRun=true; no save.")]
        public static ResponseMessage ManageClassicHmiGraphic(string softwarePath, string action="list", string name="", string filePath="", string importOptions="None", bool confirmDelete=false, bool dryRun=true)
            => Portal.ManageClassicHmiGraphic(softwarePath,action,name,filePath,importOptions,confirmDelete,dryRun);
    }
}
