using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaMcpServer.Siemens;
namespace TiaMcpServer.ModelContextProtocol
{
    // Phase 6 ⑥-② (2.7.39): typed Startdrive option package. Drive objects are addressed by devicePathJson + itemPathJson (the drive
    // unit / control unit device item hosting DriveObjectContainer) plus driveObjectNumber (official DriveObjectNumber) or
    // driveObjectIndex (position in DriveObjects; the reliable selector on G120 drives, where DriveObjectNumber is not retrievable).
    public static partial class McpServer
    {
        [McpServerTool(Name="ReadDriveObjects"), Description("[L2][Hardware][READ] Typed Startdrive drive objects of one device item (DriveObjectContainer.DriveObjects): per object the index, DriveObjectNumber (null when TIA cannot retrieve it), telegrams (Telegram type / number / input-output words and bytes / addresses / hardware identifiers / PKW), the DriveFunctionInterface view (current and possible drive object types, activation state, availability of function-in-use / commissioning / safety commissioning / hardware projection), technology extensions and the DCC chart container summary; plus the device item's ModuleAccessPoint hardware identifiers, V21 DriveItemHardwareModule and online-container availability. Read-only, offline.")]
        public static ResponseMessage ReadDriveObjects(string devicePathJson, string itemPathJson, bool includeTelegrams=true, bool includeFunctions=true, bool includeTechnologyExtensions=true, bool includeDcc=true)
            => Portal.ReadDriveObjects(devicePathJson,itemPathJson,includeTelegrams,includeFunctions,includeTechnologyExtensions,includeDcc);
        [McpServerTool(Name="ReadDriveParameters"), Description("[L2][Hardware][READ] Typed offline drive parameters of one drive object: source read (ReadDriveParameter view) or write (DriveParameter view); namesJson [\"p1000[0]\",\"r47\"] uses Find(name), numbersJson [{number, arrayIndex}] uses Find(number, arrayIndex) (arrayIndex -1 for array-less parameters); without both the composition is enumerated in native order with offset / limit. Rows: name, number, array index / length, value (BICO sinks report {bicoSource, parameterText}), min / max, unit, parameter text, optional enum value list and bit parameters (Bits); bit names such as r722.0 resolve through the parent's Bits. includeValue=false reads the metadata without touching Value - do that first for BICO sinks and status words on a freshly added drive: on a G120C, TIA Portal V21 itself went down while reading the Value of r2139 and of the unwired p840[0] (2.7.39 real project). Read-only, offline; ReadOnlineDriveParameters reads the connected drive.")]
        public static ResponseMessage ReadDriveParameters(string devicePathJson, string itemPathJson, ushort driveObjectNumber=0, int driveObjectIndex=-1, string source="read", string namesJson="[]", string numbersJson="[]", bool includeBits=false, bool includeEnumValues=false, int offset=0, int limit=100, bool includeValue=true)
            => Portal.ReadDriveParameters(devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,source,namesJson,numbersJson,includeBits,includeEnumValues,offset,limit,includeValue);
        [McpServerTool(Name="ManageStartdriveParameter"), Description("[L2][Hardware][WRITE] Exact offline drive parameter read or write on one drive object (driveObjectNumber or driveObjectIndex): read returns the ReadDriveParameter row with bits, enum values and BICO source; write sets DriveParameter.Value from a JSON scalar (converted to the current value type) or wires a BICO sink with valueJson {\"bicoSource\":\"r2050[1]\"} (Value = Parameters.Find(source); bit sources such as r722.0 resolve through the parent's Bits). Exact parameter names such as p1000[0], r47 or p2080[0].6; no fuzzy matching. Real project (G120C, 2.7.39): p1120[0] 10 -> 11 -> 10 and p1070[0] <- r2050[1] verified. Default preview; readback after the write. Never uses OnlineDriveObjectContainer or commands a drive.")]
        public static ResponseMessage ManageStartdriveParameter(string devicePathJson, string itemPathJson, ushort driveObjectNumber, string parameter, string action="read", string valueJson="null", bool dryRun=true, int driveObjectIndex=-1)
            => Portal.ManageStartdriveParameter(devicePathJson,itemPathJson,driveObjectNumber,parameter,action,valueJson,dryRun,driveObjectIndex);
        [McpServerTool(Name="ManageDriveTelegrams"), Description("[L2][Hardware][WRITE] Telegrams of one drive object (TelegramComposition): read; check (CanInsertTelegram / CanInsertMainTelegram / CanInsertSupplementaryTelegram / CanInsertSafetyTelegram / CanInsertTorqueTelegram / CanInsertAdditionalTelegram(inputSize, outputSize) and CanChangeTelegram); insert (typed Insert* per telegramType MainTelegram / SupplementaryTelegram / AdditionalTelegram / SafetyTelegram / TorqueTelegram / EdgeTelegram, telegramNumber 999 = free telegram); erase (EraseTelegram, main telegrams only on G220); while a MainTelegram exists, check / insert for MainTelegram skip the native Can* / Insert* (TIA Portal V21 crashed on a G120C there) - use changeNumber / changeSize; changeNumber (Telegram.TelegramNumber after CanChangeTelegram); changeSize (Telegram.ChangeSize(direction Input|Output, size words, keepOriginalAddress) after CanChangeSize); connectTechnologyObject (V21 AxisHardwareConnectionSDRProvider / EncoderHardwareConnectionSDRProvider SDR interfaces, V20 base interfaces: interfaceKind actor / sensor (sensorIndex) / torque / encoder of the technology object at softwarePath + objectPath, optional connectOption Default | AllowAllModules). Default preview; telegrams are read back on a fresh navigation because TIA invalidates Telegram objects after size changes. No download.")]
        public static ResponseMessage ManageDriveTelegrams(string devicePathJson, string itemPathJson, ushort driveObjectNumber=0, int driveObjectIndex=-1, string action="read", string telegramType="", int telegramNumber=-1, int inputSize=-1, int outputSize=-1, string direction="", int size=-1, bool keepOriginalAddress=true, string softwarePath="", string objectPath="", string interfaceKind="", int sensorIndex=0, string connectOption="", bool dryRun=true)
            => Portal.ManageDriveTelegrams(devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,action,telegramType,telegramNumber,inputSize,outputSize,direction,size,keepOriginalAddress,softwarePath,objectPath,interfaceKind,sensorIndex,connectOption,dryRun);
        [McpServerTool(Name="ManageDriveFunctions"), Description("[L2][Hardware][WRITE] Offline DriveFunctionInterface of one drive object. read: drive object type handler (current / possible types), activation (state, isActive), availability of FunctionInUse / Commissioning / SafetyCommissioning / HardwareProjection. Actions with valueJson: changeDriveObjectType {driveObjectType} (DriveObjectTypeHandler.ChangeDriveObjectType from PossibleDriveObjectTypes), changeActivationState {activationState Deactivate|Activate|DeactivateAndNotPresent}, activateFunction / deactivateFunction {functionKey BasicPositioner|TechnologyController} and setSIAxisType {rotaryLinear} (FunctionInUse, SINAMICS FW V6.3+), setMotorCode {motorCode, motorDataSet} and setSimoGearMlfb {mlfb} (Commissioning), updateCheckSums (SafetyCommissioning, FW V6.1+), setMotorType {motorType, dataSet} (G120), readMotorConfiguration / projectMotorConfiguration {dataSet, entries {p305: 20}} and setEquivalentCircuitDiagramData {dataSet, equivalentCircuitDiagram}, setEncoder {encoderInterface, encoderType, absoluteIncremental, rotaryLinear, encoderNumber} (G120), readEncoderConfiguration / setEncoderType {encoderNumber, rotaryLinear[, absoluteIncremental]} / projectEncoderConfiguration {encoderNumber, entries} (HardwareProjection; configuration entries by name or number). Native bool results are reported; false sets operationSuccess=false. Default preview; offline only, no download.")]
        public static ResponseMessage ManageDriveFunctions(string devicePathJson, string itemPathJson, ushort driveObjectNumber=0, int driveObjectIndex=-1, string action="read", string valueJson="{}", bool dryRun=true)
            => Portal.ManageDriveFunctions(devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,action,valueJson,dryRun);
        [McpServerTool(Name="ManageDriveSecurity"), Description("[L2][Hardware][WRITE] Drive security of one drive object (DriveObject.Security, SINAMICS FW V6.1+): read reports UmacConfiguration / DriveDataEncryption availability (the API exposes no state); activateUmac / deactivateUmac call UmacConfiguration.Activate / Deactivate (offline only); activateEncryption / deactivateEncryption call DriveDataEncryption.Activate / Deactivate with password (SecureString, never logged). Default preview; native bool result reported; no download.")]
        public static ResponseMessage ManageDriveSecurity(string devicePathJson, string itemPathJson, ushort driveObjectNumber=0, int driveObjectIndex=-1, string action="read", string password="", bool dryRun=true)
            => Portal.ManageDriveSecurity(devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,action,password,dryRun);
        [McpServerTool(Name="ManageTechnologyExtensions"), Description("[L2][Hardware][WRITE] Startdrive technology extensions. Drive scope (devicePathJson + itemPathJson + drive object): read lists TechnologyExtensionContainer.TechnologyExtensions (identifier / name / display name / isActivated, parameters with includeParameters), activate / deactivate by identifier or name (TechnologyExtension.Activate / Deactivate, readback verifies IsActivated). Portal scope (TiaPortal.GetService<TechnologyExtensionInstallationProvider>): readPackages, install / installAndGetIdentifier (filePath .tec), uninstall (identifier, confirmUninstallInUse) - these change the TIA Portal installation, not the project. Default preview.")]
        public static ResponseMessage ManageTechnologyExtensions(string action="read", string devicePathJson="[]", string itemPathJson="[]", ushort driveObjectNumber=0, int driveObjectIndex=-1, string identifier="", string filePath="", bool confirmUninstallInUse=false, bool includeParameters=false, bool dryRun=true)
            => Portal.ManageTechnologyExtensions(action,devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,identifier,filePath,confirmUninstallInUse,includeParameters,dryRun);
        [McpServerTool(Name="ManageDriveHardwareModule"), Description("[L2][Hardware][WRITE] Drive component hardware module of one device item: read returns the ModuleAccessPoint hardware identifiers and the V21 DriveItemHardwareModule (component name, position number, type name, type identifier); changeType calls DriveItemHardwareModule.ChangeType(typeIdentifier such as OrderNumber:6SL3120-2TE21-8Axx//10014), setPositionNumber writes PositionNumber (V21; NotSupported on V20). Default preview; readback verifies the type identifier; no download.")]
        public static ResponseMessage ManageDriveHardwareModule(string devicePathJson, string itemPathJson, string action="read", string typeIdentifier="", int positionNumber=-1, bool dryRun=true)
            => Portal.ManageDriveHardwareModule(devicePathJson,itemPathJson,action,typeIdentifier,positionNumber,dryRun);
        [McpServerTool(Name="ManageDriveSafetyAcceptanceTest"), Description("[L2][Hardware][WRITE] V21 Safety Integrated acceptance test of a drive device item: read lists SafetyAcceptanceTestProvider.TestFunctions (identifier, active) and whether the owning device provides SafetyAcceptanceTestReport; setActive writes TestFunction.Active for one identifier; resetTestFunctions calls ResetTestFunctions(); createProtocol writes the report file through SafetyAcceptanceTestReport.CreateProtocol(filePath, fileOperation None|Overwrite) and verifies it by size and SHA-256. NotSupported on V20. Default preview; no download.")]
        public static ResponseMessage ManageDriveSafetyAcceptanceTest(string devicePathJson, string itemPathJson, string action="read", string identifier="", bool active=false, string filePath="", string fileOperation="", bool dryRun=true)
            => Portal.ManageDriveSafetyAcceptanceTest(devicePathJson,itemPathJson,action,identifier,active,filePath,fileOperation,dryRun);
        [McpServerTool(Name="ReadOnlineDriveParameters"), Description("[L2][Hardware][ONLINE] Parameters of the connected drive (OnlineDriveObjectContainer.OnlineDriveObjects[n].ReadParameters): namesJson / numbersJson selectors or paged enumeration, same typed rows as ReadDriveParameters (BICO sources, bits, enum values, includeValue). Requires the drive to be online in TIA Portal; nothing is written.")]
        public static ResponseMessage ReadOnlineDriveParameters(string devicePathJson, string itemPathJson, ushort driveObjectNumber=0, int driveObjectIndex=-1, string namesJson="[]", string numbersJson="[]", bool includeBits=false, bool includeEnumValues=false, int offset=0, int limit=100, bool includeValue=true)
            => Portal.ReadOnlineDriveParameters(devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,namesJson,numbersJson,includeBits,includeEnumValues,offset,limit,includeValue);
        [McpServerTool(Name="ManageOnlineDriveFunctions"), Description("[L2][Hardware][ONLINE-WRITE] OnlineDriveFunctionInterface of the connected drive: read reports DriveDomainFunctions / HardwareProjection / FunctionInUse availability and the activation state; performFactoryReset {resetMode ParameterReset|SafetyParameterReset} and performRamToRomCopy (DriveDomainFunctions.PerformFactoryReset / PerformRAMtoROMCopyAllDriveObject) and changeActivationState {activationState} act on the real drive and need confirmOnline=true. No dryRun: the read action is the preview.")]
        public static ResponseMessage ManageOnlineDriveFunctions(string devicePathJson, string itemPathJson, ushort driveObjectNumber=0, int driveObjectIndex=-1, string action="read", string resetMode="", string activationState="", bool confirmOnline=false)
            => Portal.ManageOnlineDriveFunctions(devicePathJson,itemPathJson,driveObjectNumber,driveObjectIndex,action,resetMode,activationState,confirmOnline);
    }
}
