using System.ComponentModel;
using ModelContextProtocol.Server;

namespace TiaMcpServer.ModelContextProtocol
{
    public static partial class McpServer
    {
        [McpServerTool(Name = "ManageSinumerikArchive"), Description("[L2][Hardware][WRITE] V20 SINUMERIK Project.HwUtilities archive/retrieve/fAddressArchive (.dsf). Exact device/item paths are JSON arrays. archive mode OnlyHardware/HardwareAndAllProgramBlocks; F-address archive selects productive and modified PLC items. Optional comment/author/password; passwords are not logged. dryRun defaults true. Existing output files refused; outputs hashed. Retrieve inserts a device and returns its name, without save. Requires SINUMERIK option; supplied V21 SDK unsupported.")]
        public static ResponseMessage ManageSinumerikArchive([Description("Operation name from the supported actions in the tool description.")] string action, [Description("Absolute input/output path on the MCP server, with the documented extension.")] string filePath, [Description("JSON array of exact device-group/device names.")] string devicePathJson = "[]", [Description("JSON array of exact PLC device-item names below the selected device.")] string itemPathJson = "[]", [Description("JSON array of exact modified PLC device-group/device names.")] string modifiedDevicePathJson = "[]", [Description("JSON array selecting the modified PLC item for F-address archive.")] string modifiedItemPathJson = "[]", [Description("For archives OnlyHardware | HardwareAndAllProgramBlocks; for SINUMERIK safety None | NcSI | DbSI.")] string mode = "HardwareAndAllProgramBlocks", [Description("Optional archive comment.")] string comment = "", [Description("Optional archive author.")] string author = "", [Description("Optional archive password; passed as SecureString and never logged.")] string password = "", [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true)
            => Portal.ManageSinumerikArchive(action, filePath, devicePathJson, itemPathJson, modifiedDevicePathJson, modifiedItemPathJson, mode, comment, author, password, dryRun);

        [McpServerTool(Name = "ImportSinumerikAlarmTexts"), Description("[L2][PLC-Software][WRITE] V20 SINUMERIK NCU Device.GetService<SinumerikAlarmTextProvider>().AlarmTextImporter.ImportAlarmTexts. devicePathJson exact device path array; filesJson array of absolute .ts/.csv files on server. DB2 alarm texts can replace existing contents; project languages must be active. Default dryRun=true. Reports native completion, not unverified content fidelity. No save; requires SINUMERIK option; supplied V21 SDK unsupported.")]
        public static ResponseMessage ImportSinumerikAlarmTexts([Description("JSON array of exact device-group/device names.")] string devicePathJson, [Description("JSON array of 1..200 existing absolute .ts/.csv alarm-text files.")] string filesJson, [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true)
            => Portal.ImportSinumerikAlarmTexts(devicePathJson, filesJson, dryRun);

        [McpServerTool(Name = "ManageSinumerikSafetyMode"), Description("[L2][Safety][WRITE] V20 SINUMERIK NCU SafetyModeProvider: read CurrentMode or set None/NcSI/DbSI. Exact devicePathJson array. Set requires dryRun=false and confirmSafetyChange=true; native API enforces NCU offline/configuration eligibility and resulting mode is read back. Mode changes affect safety/telegram engineering; no automatic save/compile/download. Default action=read. Requires SINUMERIK option; supplied V21 SDK unsupported.")]
        public static ResponseMessage ManageSinumerikSafetyMode([Description("JSON array of exact device-group/device names.")] string devicePathJson, [Description("Operation name from the supported actions in the tool description.")] string action = "read", [Description("For archives OnlyHardware | HardwareAndAllProgramBlocks; for SINUMERIK safety None | NcSI | DbSI.")] string mode = "", [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true, [Description("Must be true with dryRun=false for a safety-mode write.")] bool confirmSafetyChange = false)
            => Portal.ManageSinumerikSafetyMode(devicePathJson, action, mode, dryRun, confirmSafetyChange);

        [McpServerTool(Name = "InitializeSimotionScripting"), Description("[L2][Hardware][WRITE] V20 Project SimotionProvider.Initialize scripting bootstrap; dryRun=true only checks provider. Actual call returns the native initialization string without executing it or running external SCOUT scripts. Requires SIMOTION SCOUT TIA. Supplied V21 SDK unsupported. No project save or controller access.")]
        public static ResponseMessage InitializeSimotionScripting([Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true) => Portal.InitializeSimotionScripting(dryRun);

        [McpServerTool(Name = "ExportScadaData"), Description("[L2][PLC-Software][READ] V20 ScadaExportProvider.Export PLC configuration to an absolute ZIP path on server. softwarePath empty selects project; otherwise one exact PLC. Requires SIMATIC SCADA Export for TIA Portal option. Default dryRun=true; existing file refused and resulting nonempty ZIP hashed. Does not deploy WinCC runtime. Supplied V21 SDK unsupported.")]
        public static ResponseMessage ExportScadaData([Description("Absolute input/output path on the MCP server, with the documented extension.")] string filePath, [Description("Exact PLC software name/path; empty selects project only where documented.")] string softwarePath = "", [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true) => Portal.ExportScadaData(filePath, softwarePath, dryRun);
    }
}
