using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaMcpServer.Siemens;
namespace TiaMcpServer.ModelContextProtocol
{
    // Phase 6 ⑥-③ (2.7.42): typed Teamcenter Gateway option package (identical on V20 / V21). The engine keeps one active
    // TcGatewayConnectionInfo per session; the dataset and workflow tools present it to the gateway.
    public static partial class McpServer
    {
        [McpServerTool(Name="ManageTeamcenterConnection"), Description("[L2][VersionControl][WRITE] Teamcenter Gateway connection of this engine session (TiaPortal.GetService<TeamcenterConnectionProvider>): read (connected, group, role, SHA-256 prefix of the session token, provider availability), connect (Connect(userName, password as SecureString - never logged, group, role, hostUrl, instance)), connectSso (ConnectSSO(hostUrl, instance, loginUrl, applicationId); without an active SSO session Teamcenter prompts in a browser), disconnect (Disconnect(info)). One connection per session; the info object stays in engine memory for ManageTeamcenterDataset / ManageTeamcenterWorkflow. Default preview; project unchanged.")]
        public static ResponseMessage ManageTeamcenterConnection(string action="read", string userName="", string password="", string group="", string role="", string hostUrl="", string instance="", string loginUrl="", string applicationId="", bool dryRun=true)
            => Portal.ManageTeamcenterConnection(action,userName,password,group,role,hostUrl,instance,loginUrl,applicationId,dryRun);
        [McpServerTool(Name="ManageTeamcenterDataset"), Description("[L2][VersionControl][WRITE] Teamcenter datasets with the active connection: checkout / checkin / cancelCheckout (TcGatewayLockProvider.CheckoutDataset / CheckinDataset / CancelCheckoutDataset(info, itemId, revisionId, datasetType T4TiaProjectDataset | T4TiaLibraryDataset, datasetName)), search (TcGatewaySearchAndDownloadProvider.Search(info, itemType Project | GlobalLibrary, tiaObjectName, itemId, itemName, revisionId; wildcards allowed, at least one of the three names) -> item ids with revision ids), download (Download(info, itemId, revisionId, itemType, localCacheOption Overwrite | DoNotOverwrite) -> starter file path in the Teamcenter cache; nothing is opened automatically). Default preview (search runs directly); the local project is unchanged.")]
        public static ResponseMessage ManageTeamcenterDataset(string action, string itemId="", string revisionId="", string datasetType="", string datasetName="", string itemType="", string tiaObjectName="", string itemName="", string localCacheOption="", bool dryRun=true)
            => Portal.ManageTeamcenterDataset(action,itemId,revisionId,datasetType,datasetName,itemType,tiaObjectName,itemName,localCacheOption,dryRun);
        [McpServerTool(Name="ManageTeamcenterWorkflow"), Description("[L2][VersionControl][WRITE] Save the open project (target project) or an open global library (target globalLibrary + libraryName) to Teamcenter through TcGatewayWorkflowProvider: readCustomAttributes (GetTeamcenterCustomAttributes(info, itemType e.g. T4TiaProject) -> name, data type, default, required, bounds, list of values), save / saveWithProxyObject (Save / SaveWithProxyObject(info, localCacheOption Overwrite | DoNotOverwrite)), saveToItem / saveToItemWithProxyObject (itemId, revisionId, localCacheOption), saveAsNewItem / saveAsNewItemWithProxyObject (itemDetailsJson {itemId, itemName*, revisionId, teamcenterItemType*, comment, teamcenterFolder, teamcenterProject [..]} via ItemDetailsDelegate), saveAsNewRevision / saveAsNewRevisionWithProxyObject (revisionDetailsJson {revisionId, comment} via RevisionDetailsDelegate; itemType names the mapped attribute type when customAttributesJson is given). customAttributesJson {name: value} sets mapped TeamcenterProperty values with SetValue + ErrorCallback before saving. Every save action saves the open object through the gateway and needs confirmSave=true; returns the native ItemInfo. Default preview.")]
        public static ResponseMessage ManageTeamcenterWorkflow(string action, string target="project", string libraryName="", string itemType="", string itemId="", string revisionId="", string localCacheOption="", string itemDetailsJson="{}", string revisionDetailsJson="{}", string customAttributesJson="{}", bool confirmSave=false, bool dryRun=true)
            => Portal.ManageTeamcenterWorkflow(action,target,libraryName,itemType,itemId,revisionId,localCacheOption,itemDetailsJson,revisionDetailsJson,customAttributesJson,confirmSave,dryRun);
    }
}
