using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaMcpServer.Siemens;
namespace TiaMcpServer.ModelContextProtocol
{
    public static partial class McpServer
    {
        [McpServerTool(Name="ReadSivarcRuleTree"), Description("[L2][HMI][READ] Typed SiVArc rule hierarchy of one family: category screens / tags / advancedTags / alarms / copies / textLists (Sivarc.ScreenRules ... TextlistRules). Without tablePath: the folder subtree from folderPath (user folders and rule tables with isDefault, counts and the connected library type version). With tablePath (Folder/Table): the table's top-level rules paged as records plus nested rule groups up to maxDepth (200 rules per group). Rule rows are typed per family (condition, operator, enabled, layout field, loop count, tag table, folder structure, program block / library references). Answers NotSupported without the SiVArc option. Never generates.")]
        public static ResponseMessage ReadSivarcRuleTree(string category, string folderPath="", string tablePath="", bool includeRules=true, int maxDepth=4, int offset=0, int limit=200)
            => Portal.ReadSivarcRuleTree(category,folderPath,tablePath,includeRules,maxDepth,offset,limit);
        [McpServerTool(Name="ManageSivarcRuleContainer"), Description("[L2][HMI][WRITE] SiVArc rule folders and rule tables of one family: kind folder (*RuleFolderComposition.Create / Delete, empty folders only) or table (*RuleTableComposition.Create(name), createFromType with typePath + typeVersion of a *RuleTableType in the project or an open global library (libraryName), Delete of non-default tables). path is Folder/Sub/Name relative to the family's system folder; read returns the typed row. delete needs confirmDelete=true when dryRun=false. Default preview; real edits need the SiVArc licence; never generates or saves.")]
        public static ResponseMessage ManageSivarcRuleContainer(string category, string kind, string path, string action="read", string libraryName="", string typePath="", string typeVersion="", bool confirmDelete=false, bool dryRun=true)
            => Portal.ManageSivarcRuleContainer(category,kind,path,action,libraryName,typePath,typeVersion,confirmDelete,dryRun);
        [McpServerTool(Name="ManageSivarcRule"), Description("[L2][HMI][WRITE] One SiVArc rule or rule group (kind rule / group) inside a rule table: rulePath is Group/Sub/Name relative to tablePath. Actions read, create (Create(name)), createFromMasterCopy (CreateFrom(MasterCopy, CreateOptions Replace|Rename) with masterCopyPath in the project or an open global library; rulePath is then the target group path, empty = the table), update, delete (confirmDelete when real). propertiesJson holds typed scalars (Name, Comment, Condition, ConditionOperator None|And|Equal|..., Enabled, screens: LayoutField / LoopCount, tags: TagGroupHierarchy / TagTable, copies: FolderStructure). referencesJson assigns library objects or PLC blocks: {ProgramBlock:{kind:plcBlock,softwarePath,path} | {kind:masterCopy|libraryType|masterCopyFolder|typeFolder,path,libraryName}, LibraryScreen, ScreenObjectLibraryItem, TagLibraryItem, AlarmLibraryItem, TextlistLibraryItem, LibraryObject; null clears}. deviceSelectionJson {PLC_1:true, HMI_RT_1:false} writes the PLC / HMI device columns (SetAttributes), deviceNamesJson reads them. Screen rules also report GetLayoutFields(). Default preview; never generates or saves.")]
        public static ResponseMessage ManageSivarcRule(string category, string tablePath, string rulePath="", string kind="rule", string action="read", string propertiesJson="{}", string referencesJson="{}", string deviceSelectionJson="{}", string deviceNamesJson="[]", string libraryName="", string masterCopyPath="", string createOption="Replace", bool confirmDelete=false, bool dryRun=true)
            => Portal.ManageSivarcRule(category,tablePath,rulePath,kind,action,propertiesJson,referencesJson,deviceSelectionJson,deviceNamesJson,libraryName,masterCopyPath,createOption,confirmDelete,dryRun);
        [McpServerTool(Name="ReadSivarcBlockDefinitions"), Description("[L2][PLC-Software][READ] SiVArc data of one code block (blockPath Folder/Block under the PLC block group) through the SivarcDataProvider block service: tag definitions (name / value / comment), text definitions (name / expression / comment / multilingual text) and the V21 tag member settings (UseCommonConfiguration, CommonParameters, BlockParameters with acquisition cycle / mode). Answers NotSupported without the SiVArc option. Read-only.")]
        public static ResponseMessage ReadSivarcBlockDefinitions(string softwarePath, string blockPath, bool includeBlockParameters=true)
            => Portal.ReadSivarcBlockDefinitions(softwarePath,blockPath,includeBlockParameters);
        [McpServerTool(Name="ManageSivarcBlockDefinition"), Description("[L2][PLC-Software][WRITE] One SiVArc definition of a code block: kind tagDefinition (Name / Value / Comment; create / update / delete), textDefinition (Name / Expression / Comment plus textsJson {de-DE: text} per project language; create / update / delete), tagMemberSettings (UseCommonConfiguration; update), commonParameters or blockParameter=name (AcquisitionCycle, AcquisitionMode None|CyclicContinuous|CyclicInOperation|OnDemand, Comment; update; V21). delete needs confirmDelete when real. Default preview; real edits need the SiVArc licence; never saves.")]
        public static ResponseMessage ManageSivarcBlockDefinition(string softwarePath, string blockPath, string kind, string name="", string action="read", string propertiesJson="{}", string textsJson="{}", bool confirmDelete=false, bool dryRun=true)
            => Portal.ManageSivarcBlockDefinition(softwarePath,blockPath,kind,name,action,propertiesJson,textsJson,confirmDelete,dryRun);
        [McpServerTool(Name="ResolveSivarcExpression"), Description("[L2][HMI][READ] Resolve a SiVArc expression (Block.DB.SymbolicName & HmiApplication.Type & LibraryObject.FolderPath ...) for every instance of one code block in the compiled PLC call structure: Sivarc.GetExpressionResolver(codeBlock, hmiDeviceItem, libraryItem).Resolve(expression). devicePathJson / itemPathJson name the HMI device item, libraryItemKind masterCopy | libraryType with libraryItemPath (project library or open global library via libraryName). Rows: instanceName, callPath, result (paged by maxResults). Requires a compiled PLC and the SiVArc option; read-only.")]
        public static ResponseMessage ResolveSivarcExpression(string softwarePath, string blockPath, string devicePathJson, string itemPathJson, string libraryItemKind, string libraryItemPath, string expression, string libraryName="", int maxResults=500)
            => Portal.ResolveSivarcExpression(softwarePath,blockPath,devicePathJson,itemPathJson,libraryItemKind,libraryItemPath,expression,libraryName,maxResults);
        [McpServerTool(Name="ManageSivarcScreenLayout"), Description("[L2][HMI][WRITE] SiVArc layout fields of one screen (classic WinCC Screen or Unified HmiScreen) through the V21 LayoutData screen service: action export writes the YML file (must not exist; verified by size and SHA-256), import applies a YML file and returns state / numberOfLayouts. screenName is an exact name or an absolute /Group/Screen path. Import defaults to preview; NotSupported on V20 or without the SiVArc option; never saves.")]
        public static ResponseMessage ManageSivarcScreenLayout(string softwarePath, string screenName, string action, string filePath, bool dryRun=true)
            => Portal.ManageSivarcScreenLayout(softwarePath,screenName,action,filePath,dryRun);
        [McpServerTool(Name="UpgradeSivarcDefinitions"), Description("[L2][PLC-Software][WRITE] Upgrade the SiVArc definitions of one PLC (SivarcDefinitionsUpgrader.Upgrade on the PlcSoftware: legacy SIVARCCOND / SIVARCTEXT functions become tag / text definitions in the block plug-ins). Returns warningCount and the recursive feedback messages. Default preview; NotSupported without the SiVArc option; never saves.")]
        public static ResponseMessage UpgradeSivarcDefinitions(string softwarePath, bool dryRun=true)
            => Portal.UpgradeSivarcDefinitions(softwarePath,dryRun);
    }
}
