using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaMcpServer.Siemens;
namespace TiaMcpServer.ModelContextProtocol
{
    // Phase 6 ⑥-③ (2.7.42): typed TIA Portal Test Suite option package (Project.GetService<TestSuiteService>; identical on V20 / V21).
    // category styleGuide (rule sets) / application (test cases, kind testSet = ApplicationTestSet) / system (system test cases).
    public static partial class McpServer
    {
        [McpServerTool(Name="ReadTestSuiteCases"), Description("[L2][Project][READ] Typed Test Suite read: category styleGuide (StyleGuideGroup.RuleSets), application (ApplicationTestGroup.TestCases, or kind testSet for ApplicationTestGroup.ApplicationTestSets) or system (SystemTestGroup.SystemTestCases). Rows carry the class and name plus the scope: TestCase.GetScope() (PLC name), SystemTestCase OPC UA server address / interface type (UserDefined | StandardSIMATIC | SiOMECompanionSpecification) / interface folder. Exact name or live offset pagination. NotSupported when the Test Suite package is missing; no test executed.")]
        public static ResponseMessage ReadTestSuiteCases(string category, string name="", int offset=0, int limit=100, string kind="case")
            => Portal.ReadTestSuiteCases(category,name,offset,limit,kind);
        [McpServerTool(Name="ExchangeTestSuiteCase"), Description("[L2][Project][WRITE] Typed Test Suite definition exchange: export (RuleSet / TestCase / SystemTestCase.SaveToFile(FileInfo) -> new .xml / .tat / .tst file verified by size and SHA-256; native bool reported), import (RuleSetComposition / TestCaseComposition / SystemTestCaseComposition.LoadFromFile(file, importOptions None|Override|SkipInactiveCultures|ActivateInactiveCultures, loadOptions: style guide RSLoadOptions None|IgnorePropertyErrors|IgnoreMissingAttributes|SkipInvalidObjects joined with |, application / system TCLoadOptions None|IgnoreInvalidObject); the file may hold several definitions, name is optional and only verified afterwards), importTestSets (application only: ApplicationTestSystemGroup.LoadFromFile(file, importOptions, TSLoadOptions None|IgnoreInvalidObject) returns the imported test sets and test cases), delete (Delete() on the case or, with kind testSet, the ApplicationTestSet; verified absent). Default preview; no test execution or automatic save.")]
        public static ResponseMessage ExchangeTestSuiteCase(string category, string action, string name, string filePath="", string importOptions="None", string loadOptions="", bool dryRun=true, string kind="case")
            => Portal.ExchangeTestSuiteCase(category,action,name,filePath,importOptions,loadOptions,dryRun,kind);
        [McpServerTool(Name="RunTestSuiteCase"), Description("[L2][Project][EXECUTE] Typed Test Suite execution through the executor service of the category's system group: one definition (name), several (namesJson) or the whole group (runAll) - RuleSetExecutor.Run(RuleSet | IEnumerable<RuleSet> | StyleGuideSystemGroup), TestCaseExecutor.Run(TestCase | IEnumerable<TestCase> | ApplicationTestSystemGroup, or with kind testSet ApplicationTestSet | IEnumerable<ApplicationTestSet>), SystemTestCaseExecutor.Run(SystemTestCase | IEnumerable<SystemTestCase> | SystemTestSystemGroup). Returns the typed TestResults (state Success|Information|Warning|Error, error / warning counts, recursive messages with path, state, description, UTC time) and testPassed. runAll on an empty group is refused (2.7.42 real project: the application executor answered a native NullReferenceException, the system executor 'No test case(s) in the selected project'; only the style-guide executor returned Success for an empty group). Default preview; application / system runs need confirmExternalExecution=true because they start a PLCSIM Advanced instance (SystemManaged) or use the configured instance / OPC UA server (official: SupportSimulationNotEnabledException / OpcUaServerAddressNotValidException / LicenseNotFoundException are the recoverable failures). No automatic save.")]
        public static ResponseMessage RunTestSuiteCase(string category, string name="", bool confirmExternalExecution=false, bool dryRun=true, string namesJson="[]", bool runAll=false, string kind="case")
            => Portal.RunTestSuiteCase(category,name,confirmExternalExecution,dryRun,namesJson,runAll,kind);
        [McpServerTool(Name="ManageTestSuiteCase"), Description("[L2][Project][WRITE] Typed Test Suite definition management: read; rename (Name = newName); setScope - style guide: RuleSet.SetScope(updateOptions Add|Override, scope objects from scopeJson [{kind project | deviceGroup (name) | plc (softwarePath -> CPU device item) | blocks | tags | types (softwarePath, optional groupPath below the system group) | units (softwarePath -> PlcUnitProvider.UnitGroup)}], native bool reported), application: TestCase.SetScope(PlcSoftware at softwarePath[, instanceName, executionMode SystemManagedPLCSIMInstance | ExternallyManagedPLCSIMInstance]; software controllers are refused natively), system: SystemTestCase.SetScope(opcUaServerAddress opc.tcp://server:port/path, serverInterfaceType UserDefined | StandardSIMATIC | SiOMECompanionSpecification[, interfaceFolderPath absolute directory]); copyScope (RuleSet.CopyScope(target rule set named by targetName)); createFromMasterCopy (RuleSetComposition / TestCaseComposition / SystemTestCaseComposition.CreateFrom(MasterCopy at masterCopyPath in the project library or the open global library libraryName), renamed to name when given); showInEditor (rule sets, test cases, test sets; WithUserInterface sessions). Default preview; readback after the change; no test run or automatic save.")]
        public static ResponseMessage ManageTestSuiteCase(string category, string name, string action="read", string kind="case", string newName="", string softwarePath="", string instanceName="", string executionMode="", string opcUaServerAddress="", string serverInterfaceType="", string interfaceFolderPath="", string updateOptions="", string scopeJson="[]", string targetName="", string masterCopyPath="", string libraryName="", bool dryRun=true)
            => Portal.ManageTestSuiteCase(category,name,action,kind,newName,softwarePath,instanceName,executionMode,opcUaServerAddress,serverInterfaceType,interfaceFolderPath,updateOptions,scopeJson,targetName,masterCopyPath,libraryName,dryRun);
    }
}
