using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using TiaMcp.BuildCommon;

namespace TiaMcp.ReleaseTool;

internal static class SourceCheck
{
    internal static readonly string[] Roots = ["src", "src/Shared", "src/Studio"];
    internal static int Line(string source, int offset) => source.AsSpan(0, Math.Min(offset, source.Length)).Count('\n') + 1;
    internal static string Hash(object? value) => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(
        PythonJson.Dumps(value, ensureAscii: false, compactSeparators: true))));
    internal static string Fingerprint(string kind, object? value) => Hash(new object?[] { kind, value });
    internal static JsonNode Json(object? value) => JsonNode.Parse(PythonJson.Dumps(value, ensureAscii: false))!;
    internal static void Write(string path, object? value, bool ascii = false)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, PythonJson.Dumps(value, ensureAscii: ascii, indent: 2) + "\n", new UTF8Encoding(false));
    }
    internal static IEnumerable<string> Files(string directory)
    {
        if (!Directory.Exists(directory)) yield break;
        foreach (var path in Directory.EnumerateFiles(directory).Order(PythonStringComparer.Instance)) yield return path;
        foreach (var child in Directory.EnumerateDirectories(directory).Order(PythonStringComparer.Instance))
            if (!CSharpLexer.SkipDirs.Contains(Path.GetFileName(child)))
                foreach (var path in Files(child)) yield return path;
    }
    internal static IEnumerable<(string Path, string Project, string Source)> Sources(string root, List<string> errors, bool ui = true)
    {
        foreach (var relative in Roots)
        {
            var directory = Path.Combine(root, relative);
            if (!Directory.Exists(directory)) { errors.Add("missing source root: " + relative); continue; }
            var paths = relative == "src"
                ? Directory.EnumerateDirectories(directory).Where(p => Path.GetFileName(p) is not ("Shared" or "Studio") && !CSharpLexer.SkipDirs.Contains(Path.GetFileName(p))).Order(PythonStringComparer.Instance).SelectMany(Files).Concat(Directory.EnumerateFiles(directory))
                : Files(directory);
            foreach (var path in paths)
            {
                if (!path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase) || CSharpLexer.GeneratedSuffixes.Any(s => path.EndsWith(s, StringComparison.OrdinalIgnoreCase))) continue;
                var name = Path.GetRelativePath(root, path).Replace('\\', '/');
                var project = relative == Roots[1] ? "openness-shared" : Path.GetRelativePath(directory, path).Split(Path.DirectorySeparatorChar)[0];
                if (!ui && project is "Gui" or "Client" or "Launcher") continue;
                string source;
                try { source = Repository.ReadSource(path); }
                catch (Exception ex) when (ex is IOException or DecoderFallbackException) { errors.Add(name + ": " + ex.Message); continue; }
                var header = Regex.Match(source, @"\A\s*(?:(?://[^\n]*(?:\n|$)|/\*.*?\*/)\s*)*", RegexOptions.Singleline).Value;
                if (!Regex.IsMatch(header, @"<auto-generated\b", RegexOptions.IgnoreCase)) yield return (name, project, source);
            }
        }
    }
    internal static object[][] Normalized(IEnumerable<Token> tokens) => tokens.Select(t => new object[] { t.Kind, t.Value }).ToArray();
    internal static JsonArray Sorted(IEnumerable<JsonObject> rows) => new(rows.OrderBy(r => r["fingerprint"]!.GetValue<string>(), StringComparer.Ordinal)
        .ThenBy(r => r["path"]!.GetValue<string>(), PythonStringComparer.Instance).ThenBy(r => r["line"]!.GetValue<int>()).Select(r => (JsonNode)r.DeepClone()).ToArray());
    internal static List<JsonObject> Unmatched(IEnumerable<JsonObject> rows, IEnumerable<JsonObject> allowances)
    {
        var remaining = allowances.GroupBy(r => r["fingerprint"]!.GetValue<string>()).ToDictionary(g => g.Key, g => g.Count());
        var result = new List<JsonObject>();
        foreach (var row in rows)
        {
            var key = row["fingerprint"]!.GetValue<string>();
            if (remaining.GetValueOrDefault(key) > 0) remaining[key]--; else result.Add(row);
        }
        return result;
    }
    internal static List<JsonObject> Baseline(JsonNode data, string field, string[] kinds)
    {
        if (data is not JsonObject || data["format"]?.ToJsonString() != "1" || data[field] is not JsonArray rows)
            throw new ReleaseException("Unsupported baseline format");
        foreach (var node in rows)
        {
            if (node is not JsonObject row || !kinds.Contains(row["kind"]?.GetValue<string>()) ||
                row["fingerprint"] is not JsonValue fp || !fp.TryGetValue<string>(out var hash) || !Regex.IsMatch(hash, @"\A[0-9a-f]{64}\z") ||
                row["path"] is not JsonValue path || !path.TryGetValue<string>(out _) || row["line"] is not JsonValue line ||
                !line.TryGetValue<int>(out var number) || number < 1 || row.ContainsKey("cjk") && (row["cjk"] is not JsonValue cjk || !cjk.TryGetValue<int>(out var count) || count < 1))
                throw new ReleaseException("Invalid baseline entry: " + node);
        }
        return rows.Select(r => r!.AsObject()).ToList();
    }
    internal static int Report(string label, IEnumerable<string> errors, string detail = "")
    {
        var rows = errors.ToArray();
        foreach (var error in rows) Console.WriteLine("[FAIL] " + error);
        Console.WriteLine($"{label}: {rows.Length} issue(s). {detail}");
        return rows.Length == 0 ? 0 : 1;
    }
}
