using System.Buffers.Binary;
using System.Text.Json;
using TiaMcp.WorkerProtocol;
using TiaMcp.WorkerProtocol.JsonV2;
using TiaMcp.WorkerProtocol.HostPreview;

int passed = 0;
void Check(bool value, string label) { if (!value) throw new Exception(label); passed++; }
void Reject(Action call, string label)
{
    try { call(); } catch (IdentityViolation) { passed++; return; }
    throw new Exception("Accepted: " + label);
}
byte[] Pack(params byte[][] frames)
{
    using var stream = new MemoryStream();
    foreach (var frame in frames) { var size = new byte[4]; BinaryPrimitives.WriteInt32LittleEndian(size, frame.Length); stream.Write(size); stream.Write(frame); }
    return stream.ToArray();
}
byte[] Header(int length) { var b = new byte[4]; BinaryPrimitives.WriteInt32LittleEndian(b, length); return b; }
foreach (int requested in new[] { -1, 0, 1, 2, 3 })
foreach (int host in new[] { 1, 2, 3 })
foreach (int worker in new[] { 1, 2, 3 })
{
    if (requested == 2 && host == 2 && worker == 2) { ExplicitProtocolSelection.RequireV2(requested, host, worker); passed++; }
    else Reject(() => ExplicitProtocolSelection.RequireV2(requested, host, worker), "version mismatch");
}
var engine = new EngineIdentity(2, "20", new string('a', 64), new string('b', 64), new string('c', 32));
var policies = new[] { new OperationPolicy("List", false, readOnly: true) };
var hello = StrictCodec.Encode(new HelloFrame(engine, BindingSnapshot.Unbound(0)));
JsonSession Session() { var s = new JsonSession(engine, policies, OuterIdStyle.Numeric); s.AcceptHello(hello); return s; }
using var document = JsonDocument.Parse("{}");
var arguments = document.RootElement;
// Real identity is generated by JsonSession and checked by the worker guard.
var fixture = new EchoFixture(engine, policies);
var session = Session();
var result = session.Call("List", arguments, fixture, r => { if (!r.GetProperty("ok").GetBoolean()) throw new Exception(); });
Check(result.Outcome == ReplyOutcome.Succeeded && !session.Faulted && fixture.Calls == 1, "bounded fake roundtrip");
foreach (var malformed in new[] { Array.Empty<byte>(), new byte[3], Header(-1), Header(0), Header(int.MaxValue), Header(StrictCodec.MaxFrameBytes + 1), Header(10), Pack(new byte[]{(byte)'{'}) })
{
    var s = Session(); int validators = 0;
    Reject(() => s.Call("List", arguments, new BoundedMemoryExchange(malformed), _ => validators++), "bad frame");
    Check(s.Faulted && s.OutcomeUnknown && validators == 0, "bad framing poisons before validation");
}
Reject(() => new BoundedMemoryExchange(new byte[BoundedMemoryExchange.MaxExchangeBytes + 1]), "exchange byte cap");
var tiny = Pack(Enumerable.Range(0, BoundedMemoryExchange.MaxFrames + 1).Select(_ => new byte[] {1}).ToArray());
Reject(() => new BoundedMemoryExchange(tiny).Exchange(new byte[] {1}).ToArray(), "frame count cap");
var validTiny = Pack(new byte[] {1,2,3});
var isolated = new BoundedMemoryExchange(validTiny); Array.Clear(validTiny);
Check(isolated.Exchange(new byte[]{1}).Single().Span.SequenceEqual(new byte[]{1,2,3}), "response copied before caller mutation");
Reject(() => isolated.Exchange(new byte[]{1}), "no replay");
using var cancellation = new CancellationTokenSource(); cancellation.Cancel();
var cancelledSession = Session();
Reject(() => cancelledSession.Call("List", arguments, new BoundedMemoryExchange(Pack(hello), cancellation.Token), _ => {}), "cancelled exchange");
Check(cancelledSession.Faulted, "attempted cancellation never falls back");
var helloSession = new JsonSession(engine, policies, OuterIdStyle.Numeric);
Reject(() => helloSession.AcceptHello(new byte[]{(byte)'{'}), "bad handshake");
Check(helloSession.Faulted, "handshake failure is terminal");
var once = new BoundedMemoryExchange(Pack(new byte[]{1})).Exchange(new byte[]{1});
Check(once.Single().Span[0] == 1, "single consumption succeeds");
Reject(() => once.ToArray(), "enumeration cannot replay");
foreach (int length in new[] { 0, StrictCodec.MaxFrameBytes + 1 })
    Reject(() => new BoundedMemoryExchange(Array.Empty<byte>()).Exchange(new byte[length]), "request byte cap");
var maximum = new byte[StrictCodec.MaxFrameBytes];
Check(new BoundedMemoryExchange(Pack(maximum)).Exchange(new byte[]{1}).Single().Length == maximum.Length, "exact frame cap accepted");
Check(new BoundedMemoryExchange(Pack(Enumerable.Range(0, BoundedMemoryExchange.MaxFrames).Select(_ => new byte[]{1}).ToArray())).Exchange(new byte[]{1}).Count() == BoundedMemoryExchange.MaxFrames, "exact count cap accepted");
using var midCancel = new CancellationTokenSource();
using var midFrames = new BoundedMemoryExchange(Pack(new byte[]{1}, new byte[]{2}), midCancel.Token).Exchange(new byte[]{1}).GetEnumerator();
Check(midFrames.MoveNext(), "first frame before cancellation");
midCancel.Cancel();
try { midFrames.MoveNext(); throw new Exception("Ignored mid-exchange cancellation"); }
catch (OperationCanceledException) { passed++; }
Console.WriteLine($"{passed} passed, 0 failed, 0 skipped.");

sealed class EchoFixture(EngineIdentity engine, OperationPolicy[] policies) : IV2Exchange
{
    public int Calls;
    public IEnumerable<ReadOnlyMemory<byte>> Exchange(ReadOnlyMemory<byte> request)
    {
        Calls++;
        var frame = (RequestFrame)StrictCodec.Decode(request);
        var guard = new WorkerRequestGuard(engine, policies);
        var observed = BindingSnapshot.Unbound(0);
        guard.Accept(frame.Identity, observed);
        var replyIdentity = guard.Finish(observed, ReplyOutcome.Succeeded);
        using var document = JsonDocument.Parse("{\"ok\":true}");
        var reply = StrictCodec.Encode(new ReplyFrame(frame.Id, replyIdentity, document.RootElement));
        byte[] wire = new byte[reply.Length + 4]; BinaryPrimitives.WriteInt32LittleEndian(wire, reply.Length); reply.CopyTo(wire, 4);
        return new BoundedMemoryExchange(wire).Exchange(request);
    }
}
