namespace TiaOpenness.Gui.Localization;

internal static partial class Strings
{
    private static (string Key, string En, string Zh)[] FeaturePageCatalogue =>
    [
        ("Feature.NotConnected", "Not connected yet.", "尚未接入。"),
        ("Feature.Count", "{0} events", "{0} 条"),
        ("Feature.Copy", "Copy", "复制"),
        ("Feature.OpenFolder", "Open folder", "打开文件夹"),
        ("Feature.Connection", "Connection info", "连接信息"),
        ("Feature.Address", "Address", "地址"),
        ("Feature.Transport", "Transport", "传输方式"),
        ("Calls.Count", "{0} calls · {1} pending", "{0} 条 · {1} 待批"),
        ("Calls.ReleaseOnly", "{0} only", "仅 {0}"),
        ("Calls.Follow", "Follow latest", "跟随最新"),
        ("Calls.Paused", "Paused", "已暂停"),
        ("Calls.WriteOnly", "Writes only", "只看写操作"),
        ("Calls.FailOnly", "Failed / unknown", "只看失败/未知"),
        ("Calls.Search", "Search tool name…", "搜索工具名…"),
        ("Calls.EmptyTitle", "No AI calls yet", "还没有 AI 调用"),
        ("Calls.NoMatches", "No matching calls", "没有匹配的调用"),
        ("Calls.EmptyHelp", "Load the tia-portal-vm server in an AI client and make a request. Connection info is on the right.", "在 AI 客户端中加载 tia-portal-vm 服务并发起一次请求，调用会出现在这里。连接信息见右侧。"),
        ("Calls.Time", "Time", "时间"),
        ("Calls.Host", "Host / version", "宿主 / 版本"),
        ("Calls.Tool", "Tool", "工具名"),
        ("Calls.ReadWrite", "R/W", "读/写"),
        ("Calls.Result", "Result", "结果"),
        ("Calls.Duration", "Duration", "耗时"),
        ("Calls.Target", "Target", "目标摘要"),
        ("Calls.Read", "R", "读"),
        ("Calls.Write", "W", "写"),
        ("Calls.Success", "OK", "成功"),
        ("Calls.Rejected", "Rejected before execution", "操作前拒绝"),
        ("Calls.Pending", "Pending", "待批"),
        ("Calls.RequestId", "Request ID", "请求 ID"),
        ("Calls.Detail", "Call details", "调用详情"),
        ("Calls.Parameters", "Parameters (JSON)", "参数 JSON"),
        ("Calls.Summary", "Result summary", "结果摘要"),
        ("Calls.Error", "Error code and message", "错误码与信息"),
        ("Calls.ApprovalRecord", "Approval record", "审批记录"),
        ("Calls.CopyConnection", "Copy connection info", "复制连接信息"),
        ("Calls.SecretPlaceholder", "Secret shown as ••••", "密钥以占位符 •••• 显示"),
        ("Calls.OpenPending", "Open pending list", "打开待批列表"),
        ("Calls.ApprovalOn", "On · {0}s", "开启 · {0}s"),
        ("Calls.PendingSummary", "{0} requests {1} write operations. Auto-reject in {2}s.", "{0} 请求 {1} 项写操作，{2}s 后自动拒绝。"),
        ("Approval.Project", "Target project", "目标工程"),
        ("Approval.Pending", "Waiting", "等待批准"),
        ("Approval.Approved", "Approved", "已批准"),
        ("Approval.Executing", "Executing", "执行中"),
        ("Approval.Completed", "Completed", "完成"),
        ("Approval.Failed", "Failed", "失败"),
        ("Approval.Partial", "Partial", "部分完成"),
        ("Approval.Unknown", "Result unknown", "结果未知"),
        ("Approval.Rejected", "Rejected", "已拒绝"),
        ("Approval.TimedOut", "Timed out", "已超时"),
        ("Approval.Disconnected", "Workbench disconnected", "工作台断开"),
        ("Approval.NoneExecuted", "No operation was executed.", "未执行任何操作。"),
        ("Approval.VerifyProject", "Verify the project in TIA Portal.", "请在博途中核对工程。"),
        ("Approval.NoLongerPending", "This request is no longer awaiting a decision, or another request is still being processed.", "此请求已不再等待审批，或另一个请求仍在处理中。"),
        ("Approval.AutoReject", "Auto-reject in", "超时自动拒绝"),
        ("Approval.Approve", "Approve", "批准执行"),
        ("Approval.Deny", "Reject", "拒绝"),
        ("Approval.Parameters", "View full parameters", "查看完整参数"),
        ("Approval.ToastTitle", "AI requests project changes · {0} operations", "AI 请求修改工程 · {0} 项操作"),
        ("Approval.ToastHelp", "Click to open pending list", "点击查看待批列表"),
        ("Audit.Verify", "Verify integrity", "校验完整性"),
        ("Audit.Pass", "{0} events, hash chain intact", "共 {0} 条，哈希链完整"),
        ("Audit.Break", "Records after #{0} were modified", "第 {0} 条之后的记录被改动"),
        ("Audit.Jump", "Jump to", "跳到该位置"),
        ("Audit.Limitation", "Deleting the whole file or truncating its end cannot be detected.", "整个文件被删除或末尾被截掉无法检测。"),
        ("Audit.Event", "Event", "事件类型"),
        ("Audit.Object", "Tool / object", "工具 / 对象"),
        ("Audit.Hash", "Hash", "哈希"),
        ("Audit.Request", "Write request", "写请求"),
        ("Audit.Approve", "Approved", "批准"),
        ("Audit.Reject", "Rejected", "拒绝"),
        ("Audit.Timeout", "Timed out", "超时"),
        ("Audit.Start", "Execution start", "开始执行"),
        ("Audit.End", "Execution end", "执行结束"),
        ("Audit.Toggle", "Approval toggled", "审批开关变化"),
        ("Audit.Retention", "Retention", "保留设置"),
        ("Audit.FileSize", "File size limit", "单文件上限"),
        ("Audit.Copies", "Files kept", "保留份数"),
        ("Audit.Coverage", "Coverage", "当前覆盖"),
        ("Audit.OpenFolder", "Open log folder", "打开日志文件夹"),
        ("Audit.About", "About the audit log", "关于审计日志"),
        ("Audit.AboutText", "Key operations are written to a hash-chained log: each record includes the previous hash, so the chain is traceable and tampering detectable.", "关键操作写入带哈希链的日志文件：每条记录包含上一条的哈希，可追溯、可检测是否被改动。"),
        ("Env.Recheck", "Re-check", "重新检查"),
        ("Env.Generate", "Generate diagnostics", "生成诊断包"),
        ("Env.Diagnostics", "Diagnostics package", "诊断包"),
        ("Env.DiagnosticHelp", "Bundles logs, environment info and config (secrets redacted) into a zip on the Desktop.", "把日志、环境信息和配置（密钥脱敏）打包成 zip 放到桌面。遇到说不清的问题，先生成再找人。"),
        ("Env.Redacted", "Secrets redacted", "密钥已脱敏"),
        ("Env.FirstConnection", "First connection", "首次连接"),
        ("Env.FirstConnectionHelp", "On first Openness access TIA Portal shows a confirmation dialog. Click “Yes to all”, otherwise it asks on every start.", "第一次通过 Openness 连接时，博途会弹出访问确认框，请点“全部是”；否则每次启动都会再次询问。"),
        ("Env.Checking", "Checking…", "检查中…"),
        ("Env.NeedsAction", "{0} items need attention", "{0} 项需要处理"),
        ("Env.AllPass", "All passed", "全部通过"),
        ("Env.Unchecked", "Not checked", "未检查"),
        ("Env.Installations", "Installed TIA Portal versions", "已安装的 TIA Portal 版本"),
        ("Env.Membership", "Openness user group", "Openness 用户组"),
        ("Env.Runtime", "Runtime", "运行环境"),
        ("Env.BundledRuntime", "Bundled .NET runtime", "随包 .NET 运行时"),
        ("Env.Application", "This app", "本软件"),
        ("Env.Engines", "Engine / worker files", "引擎 / worker 文件"),
        ("Env.Data", "Writable data directory", "data 目录可写"),
        ("Env.Network", "Network", "网络"),
        ("Env.Port", "Port availability", "端口占用"),
        ("Env.Url", "URL reservation", "URL 保留"),
        ("Env.Firewall", "Firewall", "防火墙"),
    ];
}
