namespace TiaOpenness.Gui.Localization;

internal static partial class Strings
{
    private static (string Key, string En, string Zh)[] FeaturePageCatalogue =>
    [
        ("Feature.NotConnected", "Not connected yet.", "尚未接入。"),
        ("Feature.Count", "{0} events", "{0} 条"),
        ("Feature.Copy", "Copy", "复制"),
        ("Feature.OpenFolder", "Open folder", "打开文件夹"),
        ("Feature.Connection", "Connection info", "连接信息"),
        ("Feature.Address", "Address", "地址"),
        ("Feature.Transport", "Transport", "传输方式"),
        ("Calls.Count", "{0} calls · {1} pending", "{0} 条 · {1} 待批"),
        ("Calls.ReleaseOnly", "{0} only", "仅 {0}"),
        ("Calls.Follow", "Follow latest", "跟随最新"),
        ("Calls.Paused", "Paused", "已暂停"),
        ("Calls.WriteOnly", "Writes only", "只看写操作"),
        ("Calls.FailOnly", "Failed / unknown", "只看失败/未知"),
        ("Calls.Search", "Search tool name…", "搜索工具名…"),
        ("Calls.EmptyTitle", "No AI calls yet", "还没有 AI 调用"),
        ("Calls.NoMatches", "No matching calls", "没有匹配的调用"),
        ("Calls.EmptyHelp", "Load the tia-portal-vm server in an AI client and make a request. Connection info is on the right.", "在 AI 客户端中加载 tia-portal-vm 服务并发起一次请求，调用会出现在这里。连接信息见右侧。"),
        ("Calls.Time", "Time", "时间"),
        ("Calls.Host", "Host / version", "宿主 / 版本"),
        ("Calls.Tool", "Tool", "工具名"),
        ("Calls.ReadWrite", "R/W", "读/写"),
        ("Calls.Result", "Result", "结果"),
        ("Calls.Duration", "Duration", "耗时"),
        ("Calls.Target", "Target", "目标摘要"),
        ("Calls.Read", "R", "读"),
        ("Calls.Write", "W", "写"),
        ("Calls.Success", "OK", "成功"),
        ("Calls.Rejected", "Rejected before execution", "操作前拒绝"),
        ("Calls.Pending", "Pending", "待批"),
        ("Calls.RequestId", "Request ID", "请求 ID"),
        ("Calls.Detail", "Call details", "调用详情"),
        ("Calls.ResultJson", "Result (JSON)", "结果 JSON"),
        ("Calls.PreviewRedacted", "Credentials redacted.", "凭据已脱敏。"),
        ("Calls.PreviewTruncated", "Credentials redacted; preview limited to 4096 characters.", "凭据已脱敏；预览最多 4096 字符。"),
        ("Calls.PendingOperations", "{0} operations", "{0} 项操作"),
        ("Calls.JournalSummary", "{0} · execution: {1} · completeness: {2}", "{0} · 执行：{1} · 完整性：{2}"),
        ("Calls.ApprovalUnavailable", "Approval history is not available in the call journal.", "调用日志中未提供审批历史。"),
        ("Calls.Execution.NotStarted", "Not started", "未开始"),
        ("Calls.Execution.ReadOnly", "Read only", "只读"),
        ("Calls.Execution.Completed", "Completed", "已完成"),
        ("Calls.Execution.Partial", "Partial", "部分执行"),
        ("Calls.Execution.Unknown", "Unknown", "未知"),
        ("Calls.Completeness.Complete", "Complete", "完整"),
        ("Calls.Completeness.Partial", "Partial", "部分"),
        ("Calls.Completeness.None", "None", "无"),
        ("Calls.Completeness.Unknown", "Unknown", "未知"),
        ("Calls.Parameters", "Parameters (JSON)", "参数 JSON"),
        ("Calls.Summary", "Result summary", "结果摘要"),
        ("Calls.Error", "Error code and message", "错误码与信息"),
        ("Calls.ApprovalRecord", "Approval record", "审批记录"),
        ("Calls.CopyConnection", "Copy connection info", "复制连接信息"),
        ("Calls.SecretPlaceholder", "Secret shown as ••••", "密钥以占位符 •••• 显示"),
        ("Calls.OpenPending", "Open pending list", "打开待批列表"),
        ("Calls.ApprovalOn", "On · {0}s", "开启 · {0}s"),
        ("Calls.PendingSummary", "{0} requests {1} write operations. Auto-reject in {2}s.", "{0} 请求 {1} 项写操作，{2}s 后自动拒绝。"),
        ("Approval.Project", "Target project", "目标工程"),
        ("Approval.Pending", "Waiting", "等待批准"),
        ("Approval.Approved", "Approved", "已批准"),
        ("Approval.Executing", "Executing", "执行中"),
        ("Approval.Completed", "Completed", "完成"),
        ("Approval.Failed", "Failed", "失败"),
        ("Approval.Partial", "Partial", "部分完成"),
        ("Approval.Unknown", "Result unknown", "结果未知"),
        ("Approval.Rejected", "Rejected", "已拒绝"),
        ("Approval.TimedOut", "Timed out", "已超时"),
        ("Approval.Disconnected", "Workbench disconnected", "工作台断开"),
        ("Approval.NoneExecuted", "No operation was executed.", "未执行任何操作。"),
        ("Approval.VerifyProject", "Verify the project in TIA Portal.", "请在博途中核对工程。"),
        ("Approval.NoLongerPending", "This request is no longer awaiting a decision, or another request is still being processed.", "此请求已不再等待审批，或另一个请求仍在处理中。"),
        ("Approval.AutoReject", "Auto-reject in", "超时自动拒绝"),
        ("Approval.Approve", "Approve", "批准执行"),
        ("Approval.Deny", "Reject", "拒绝"),
        ("Approval.Parameters", "View full parameters", "查看完整参数"),
        ("Approval.ToastTitle", "AI requests project changes · {0} operations", "AI 请求修改工程 · {0} 项操作"),
        ("Approval.ToastHelp", "Click to open pending list", "点击查看待批列表"),
        ("Audit.Verify", "Verify integrity", "校验完整性"),
        ("Audit.Pass", "{0} events, hash chain intact", "共 {0} 条，哈希链完整"),
        ("Audit.Break", "Records after #{0} were modified", "第 {0} 条之后的记录被改动"),
        ("Audit.Jump", "Jump to", "跳到该位置"),
        ("Audit.Limitation", "Deleting the whole file or truncating its end cannot be detected.", "整个文件被删除或末尾被截掉无法检测。"),
        ("Audit.Event", "Event", "事件类型"),
        ("Audit.Object", "Tool / object", "工具 / 对象"),
        ("Audit.Hash", "Hash", "哈希"),
        ("Audit.Request", "Write request", "写请求"),
        ("Audit.Approve", "Approved", "批准"),
        ("Audit.Reject", "Rejected", "拒绝"),
        ("Audit.Timeout", "Timed out", "超时"),
        ("Audit.Start", "Execution start", "开始执行"),
        ("Audit.End", "Execution end", "执行结束"),
        ("Audit.Toggle", "Approval toggled", "审批开关变化"),
        ("Audit.Retention", "Retention", "保留设置"),
        ("Audit.FileSize", "File size limit", "单文件上限"),
        ("Audit.Copies", "Files kept", "保留份数"),
        ("Audit.Coverage", "Coverage", "当前覆盖"),
        ("Audit.OpenFolder", "Open log folder", "打开日志文件夹"),
        ("Audit.About", "About the audit log", "关于审计日志"),
        ("Audit.AboutText", "Key operations are written to a hash-chained log: each record includes the previous hash, so the chain is traceable and tampering detectable.", "关键操作写入带哈希链的日志文件：每条记录包含上一条的哈希，可追溯、可检测是否被改动。"),
        ("Env.Recheck", "Re-check", "重新检查"),
        ("Env.Generate", "Generate diagnostics", "生成诊断包"),
        ("Env.Diagnostics", "Diagnostics package", "诊断包"),
        ("Env.DiagnosticHelp", "Bundles check results, recent logs and redacted config into a zip under data/reports. The manifest lists included, missing and redacted items.", "把体检结果、最近日志和脱敏配置打包到 data/reports。清单记录包含、缺失和脱敏的内容。"),
        ("Env.Redacted", "Secrets redacted", "密钥已脱敏"),
        ("Env.FirstConnection", "First connection", "首次连接"),
        ("Env.FirstConnectionHelp", "On first attach, TIA Portal may show an Openness access confirmation naming the connecting application. Verify the application path, then choose “Yes” for this access or “Yes to all” to remember approval. Attach once with the TIA UI visible; a headless session cannot show this prompt. This page does not attach to TIA.", "首次附着时，博途可能弹出 Openness 访问确认框，并显示申请连接的应用程序。核对应用路径后，选“是”允许本次访问，或“全部是”记住批准。先在博途界面可见时连接一次，无界面会话无法显示此提示。本页不连接博途。"),
        ("Env.Checking", "Checking…", "检查中…"),
        ("Env.NeedsAction", "{0} items need attention", "{0} 项需要处理"),
        ("Env.AllPass", "All passed", "全部通过"),
        ("Env.Unchecked", "Not checked", "未检查"),
        ("Env.Installations", "Installed TIA Portal versions", "已安装的 TIA Portal 版本"),
        ("Env.Membership", "Openness user group", "Openness 用户组"),
        ("Env.Runtime", "Runtime", "运行环境"),
        ("Env.BundledRuntime", "Bundled .NET runtime", "随包 .NET 运行时"),
        ("Env.Application", "This app", "本软件"),
        ("Env.Engines", "Engine / worker files", "引擎 / worker 文件"),
        ("Env.Data", "Writable data directory", "data 目录可写"),
        ("Env.Network", "Network", "网络"),
        ("Env.Port", "Port availability", "端口占用"),
        ("Env.Url", "URL reservation", "URL 保留"),
        ("Env.Firewall", "Firewall", "防火墙"),
        ("Env.Framework", ".NET Framework 4.8", ".NET Framework 4.8 运行时"),
        ("Env.ReleaseFiles", "{0} engine / worker files", "{0} 引擎 / worker 文件"),
        ("Env.Passed", "Passed", "通过"),
        ("Env.Failed", "Requirement not met", "条件未满足"),
        ("Env.Unknown", "Could not determine", "无法确定"),
        ("Env.NewLogon", "Added to group; sign out and in", "已加入组；需注销重登"),
        ("Env.Fallback", "User data directory in use", "正在使用用户数据目录"),
        ("Env.PortUsed", "Port is in use", "端口已被占用"),
        ("Env.NoEndpoint", "No saved local HTTP endpoint", "没有已保存的本机 HTTP 地址"),
        ("Env.Guidance", "Guidance; no attach performed", "操作指引；未执行附着"),
        ("Env.CheckDetail", "{0}\n\nAction: {1}\n\nLocal evidence / paths:\n{2}", "{0}\n\n处理方法：{1}\n\n本机证据 / 路径：\n{2}"),
        ("Env.FixButton", "Fix (doctor --fix)", "修复（doctor --fix）"),
        ("Env.ManualButton", "Show steps", "查看步骤"),
        ("Env.FixInstall", "Install a supported TIA Portal release (V14 SP1, V15.1, V16–V21) with Openness enabled. Repair the installation if its PublicAPI assemblies are missing.", "安装支持的 TIA Portal（V14 SP1、V15.1、V16–V21），勾选 Openness；缺少 PublicAPI 程序集时修复安装。"),
        ("Env.FixMembership", "Click Fix to run the existing doctor --fix, which may request UAC to add the current user to Siemens TIA Openness. Alternatively use lusrmgr.msc as administrator. Sign out and back in after adding the user.", "点击修复运行现有 doctor --fix，可能弹出 UAC，将当前用户加入 Siemens TIA Openness。也可由管理员使用 lusrmgr.msc 手动添加，然后注销并重新登录。"),
        ("Env.FixLogon", "The user is already listed in Siemens TIA Openness but the current token lacks membership. Sign out of Windows and sign back in, then reopen the Workbench; restarting only the app is insufficient.", "用户已在 Siemens TIA Openness 成员列表中，但当前令牌尚未生效。请注销 Windows 后重新登录，再打开工作台；只重启应用不够。"),
        ("Env.FixFramework", "Install .NET Framework 4.8 or later using the Windows runtime installer, then restart the Workbench.", "使用 Windows 运行时安装程序安装 .NET Framework 4.8 或更高版本，然后重启工作台。"),
        ("Env.FixRuntime", "Restore runtime/dotnet from the complete delivery. The .NET 10 host, hostfxr, core, ASP.NET Core and Windows Desktop runtimes must be present.", "从完整交付包恢复 runtime/dotnet，需包含 .NET 10 host、hostfxr、Core、ASP.NET Core 和 Windows Desktop 运行时。"),
        ("Env.FixFiles", "Restore the indicated release directory from the matching complete delivery; keep its host, dependencies, release-key and worker together. Do not borrow binaries from another release.", "从匹配的完整交付包恢复所列版本目录；宿主、依赖、release-key 和 worker 必须配套，不要借用其他版本的二进制。"),
        ("Env.FixData", "The evidence lists the actual data, config and log directories. A read-only installation uses user storage. Grant write access to that user directory or set TIA_MCP_DATA_DIRECTORY to a writable absolute path and restart. Reports are saved in its reports subdirectory.", "证据列出实际 data、配置和日志目录。只读安装使用用户存储。请授予该用户目录写权限，或将 TIA_MCP_DATA_DIRECTORY 设置为可写绝对路径后重启；诊断包保存到其 reports 子目录。"),
        ("Env.FixPort", "Inspect the listed PID/process. If it is the expected MCP host, keep it running; otherwise choose another port in Engine & MCP settings or stop the owning application yourself.", "核对列出的 PID/进程；若为预期 MCP 宿主可继续使用，否则在引擎与 MCP 设置中选择其他端口，或自行停止占用程序。"),
        ("Env.FixUrl", "Save a local HTTP endpoint in Engine & MCP settings, then use its network configuration button to reserve the exact URL for your Windows user. Review UAC there. This page only inspects the reservation and current-user execute permission.", "在引擎与 MCP 设置中保存本机 HTTP 地址，再使用网络配置按钮为当前 Windows 用户保留对应 URL，在那里确认 UAC。本页仅检查 URL 保留及当前用户执行权限。"),
        ("Env.FixFirewall", "Use the network configuration button in Engine & MCP settings to create/enable the named TIA-MCP inbound TCP rule. The check covers its address, port, direction and allow action; it does not prove remote connectivity or override other firewall policies.", "使用引擎与 MCP 设置中的网络配置按钮创建/启用 TIA-MCP 入站 TCP 规则。检查覆盖地址、端口、方向及允许操作，不证明远程连通性，也不覆盖其他防火墙策略。"),
        ("Env.NoDoctorHost", "No bundled V20/V21 doctor executable is available. Add the user manually with lusrmgr.msc, then sign out and in.", "没有可用的随包 V20/V21 doctor 可执行文件。请使用 lusrmgr.msc 手动添加用户，再注销重登。"),
        ("Env.FixStarted", "The doctor fix is running; answer its Windows UAC prompt if shown, then check whether a new logon is needed.", "doctor 修复正在运行；如弹出 Windows UAC 请确认，然后核对是否需要重新登录。"),
        ("Env.FixFailed", "The doctor fix could not start. Use the manual membership steps.", "doctor 修复未能启动，请按步骤手动处理用户组。"),
        ("Env.BundleChecks", "Checking environment…", "正在检查环境…"),
        ("Env.BundleRedact", "Redacting logs and config…", "正在脱敏日志和配置…"),
        ("Env.BundleWrite", "Writing diagnostic zip…", "正在写入诊断 zip…"),
        ("Env.BundleDone", "Diagnostic bundle saved", "诊断包已保存"),
        ("Env.BundleFailed", "Diagnostic export failed: {0}", "诊断包导出失败：{0}"),
    ];
}
