using System;
using System.Collections.Generic;

namespace TiaOpenness.Gui.Localization;

/// <summary>
/// Every visible string, in both languages.
///
/// The two languages are held as one table of triples rather than two parallel files: a key
/// cannot exist in English and be missing in Chinese, because there is only one place to add
/// it. <c>StringsTests</c> checks the rest - no duplicates, nothing blank, and the same
/// <c>{0}</c> placeholders on both sides.
/// </summary>
internal static partial class Strings
{
    /// <summary>key, English, Chinese.</summary>
    internal static (string Key, string En, string Zh)[] Catalogue => [.. CommonCatalogue, .. ProjectPagesCatalogue, .. EngineCatalogue];

    private static readonly (string Key, string En, string Zh)[] CommonCatalogue =
    [
        ("Control.Enabled", "Allow AI to control the Workbench UI", "允许 AI 控制工作台界面"),
        ("Control.Unavailable", "Workbench control channel unavailable", "工作台控制通道不可用"),
        ("Control.Activity", "AI updated the UI · {0} · {1} · {2}s ago", "AI 操作了界面 · {0} · {1} · {2} 秒前"),
        ("Control.Prefilled", "AI prefill · awaiting confirmation", "AI 预填，待确认"),
        ("Control.Confirm", "Keep values", "确认预填"),
        ("Control.Clear", "Clear prefill", "清除预填"),
        ("Control.Record", "Workbench UI · {0} · {1}", "工作台界面 · {0} · {1}"),
        ("Shell.VersionControl", "Version control", "版本控制"),
        ("Shell.Engineering", "Project operations", "工程操作"),
        ("Shell.Brand", "TIA Workbench", "TIA 工作台"),
        ("Shell.Overview", "Overview", "概览"),
        ("Shell.Settings", "Engine & MCP settings…", "引擎 & MCP 设置…"),
        ("Shell.Diagnostics", "Export diagnostics", "导出诊断包"),
        ("Shell.DiagnosticsNotConnected", "Diagnostic export is not connected yet.", "诊断包导出尚未接入。"),
        ("Shell.ApprovalOff", "Approval off", "审批已关"),
        ("Shell.Pending", "{0} pending", "{0} 待批"),
        ("Shell.PendingTitle", "Pending approvals", "待批请求"),
        ("Shell.NoPending", "No pending requests", "没有待批请求"),
        ("Shell.NoPendingDescription", "Write calls from AI clients queue here and are handled one by one — there is no \"approve all\".", "AI 客户端发起会修改工程的调用时会在这里排队，逐条处理，没有“全部批准”。"),
        ("Shell.McpStatus", "MCP · {0}", "MCP · {0}"),
        ("Shell.SessionStatus", "TIA Portal {0} · {1}{2}", "TIA Portal {0} · {1}{2}"),
        ("Shell.Status", "MCP service · {0} · TIA Portal {1} · {2}", "MCP 服务 · {0} · TIA Portal {1} · {2}"),
        ("Shell.Calls", "AI calls", "AI 调用"),
        ("Shell.Audit", "Audit log", "审计日志"),
        ("Shell.Environment", "Environment check", "环境体检"),
        ("Shell.CallsEmpty", "No AI calls yet. Connect an AI client from MCP & clients to get started.", "还没有 AI 调用。在 MCP 与客户端页面连接 AI 客户端后开始使用。"),
        ("Shell.AuditEmpty", "No audit records yet.", "暂无审计记录。"),
        ("Shell.EnvironmentEmpty", "No environment check results yet.", "暂无环境体检结果。"),
        ("Shell.Cancel", "Cancel", "取消"),
        ("Settings.Approval", "Write approval", "写操作审批"),
        ("Settings.On", "On", "开启"),
        ("Settings.Off", "Off", "关闭"),
        ("Settings.Timeout", "Timeout", "超时秒数"),
        ("Settings.Appearance", "Appearance", "外观"),
        ("Settings.Language", "Language", "语言"),
        ("Settings.English", "English", "English"),
        ("Settings.Chinese", "中文", "中文"),
        ("Settings.Theme", "Theme", "主题"),
        ("Settings.Auto", "Auto", "自动"),
        ("Settings.Light", "Light", "浅色"),
        ("Settings.Dark", "Dark", "深色"),
        ("Settings.Update", "Updates", "更新"),
        ("Settings.Engine", "Engine", "引擎"),
        ("Settings.EngineVersion", "{0}", "{0}"),
        ("Settings.CheckUpdate", "Check updates", "检查更新"),
        ("Settings.Releases", "GitHub Releases", "GitHub Releases"),
        ("Settings.Diagnostics", "Diagnostics", "诊断"),
        ("Settings.ConfigDirectory", "Config folder", "配置目录"),
        ("Settings.LogDirectory", "Runtime logs", "运行日志"),
        ("Settings.About", "About", "关于"),
        ("Settings.Homepage", "Project home", "项目主页"),
        ("Settings.PathMissing", "The folder does not exist yet: {0}", "目录尚不存在：{0}"),
        ("Settings.ConfirmOffTitle", "Turn off write approval?", "关闭写操作审批？"),
        ("Settings.ConfirmOffDescription", "Write operations from AI clients will run immediately without manual approval. All calls are still recorded in the audit log.", "关闭后，AI 客户端发起的写操作将直接执行，不再需要人工批准。所有调用仍会记录到审计日志。"),
        ("Settings.TurnOff", "Turn off", "关闭审批"),
        ("Mcp.Clients", "AI clients", "AI 客户端"),
        ("Mcp.ClientsNote", "Writes MCP connection info only · undetected clients still writable", "仅写入 MCP 连接信息 · 未检测到的仍可写入"),
        ("Mcp.ClientCounts", "· {0} selected · {1} detected", "· 已选 {0} 个 · 检测到 {1} 个"),
        ("Mcp.Detected", "Detected", "已检测到"),
        ("Mcp.SecretTitle", "Shared secret & write", "共享密钥与写入"),
        ("Mcp.SecretNote", "One key for both sides · server and client config saved together", "一把密钥，两端共用 · 服务端与客户端配置同时保存"),
        ("Mcp.NoSecret", "No secret yet", "尚无密钥 — 点击生成"),
        ("Mcp.Hide", "Hide", "隐藏"),
        ("Mcp.WillWrite", "Will write to:", "将写入："),
        ("Mcp.ActivityLog", "Log", "日志"),
        ("Mcp.TestNotRun", "Not run yet", "尚未执行"),
        ("Config.Ipv4", "VM IPv4", "虚拟机 IPv4"),
        ("Config.AutoDetect", "Auto-detect", "自动检测"),
        ("Dialog.OK", "_OK", "确定(_O)"),
        ("Dialog.Cancel", "_Cancel", "取消(_C)"),
        ("Dialog.Yes", "_Yes", "是(_Y)"),
        ("Dialog.No", "_No", "否(_N)"),
        ("Config.ListSeparator", ", ", "、"),
        ("Config.ClientSaveError", "{0}: {1}", "{0}：{1}"),
        ("Config.UpdateSize", "({0})", "（{0}）"),
        ("Config.ReasonSeparator", "; ", "；"),
        ("Config.Eyebrow", "ENGINEERING LINK CONSOLE", "工程连接控制台"),
        ("Config.RemoteTitle", "Connect TIA and AI on one page", "一页连接 TIA 与 AI"),
        ("Config.LocalTitle", "Same machine, one pass", "同一台电脑，一次完成"),
        ("Config.RemoteSubtitle", "The machine with TIA Portal runs an HTTP service. AI clients connect over the network; both sides use one shared secret.", "安装 TIA Portal 的电脑运行 HTTP 服务；AI 客户端通过网络连接，两端使用同一密钥。"),
        ("Config.LocalSubtitle", "TIA Portal and the AI client run on the same PC. The client starts the engine on demand over stdio — no address, port or secret.", "TIA Portal 与 AI 客户端在同一台电脑，客户端通过 stdio 按需启动引擎，无需地址、端口或密钥。"),
        ("Config.RemoteMode", "VM ↔ Host", "虚拟机 ↔ 宿主机"),
        ("Config.LocalMode", "Same machine", "同一台电脑"),
        ("Config.RemoteNote", "The TIA machine runs an HTTP service; AI clients connect with a shared secret.", "TIA 电脑运行 HTTP 服务；AI 客户端通过网络和共享密钥连接。"),
        ("Config.LocalNote", "TIA and the AI client share one PC; the client starts the engine over stdio.", "TIA 与 AI 客户端在同一台电脑，通过 stdio 按需启动引擎。"),
        ("Config.Installation", "TIA installation", "TIA 安装"),
        ("Config.Version", "Version", "版本"),
        ("Config.InstallPath", "Install path · without Bin", "安装路径 · 不含 Bin"),
        ("Config.Browse", "Browse", "浏览"),
        ("Config.Detected", "Detected", "已检测到"),
        ("Config.NotDetected", "Not detected", "未检测到"),
        ("Config.HttpService", "HTTP service", "HTTP 服务"),
        ("Config.Port", "Port", "端口"),
        ("Config.Network", "Network permission", "网络权限"),
        ("Config.Start", "Start service", "启动服务"),
        ("Config.Stop", "Stop service", "停止服务"),
        ("Config.Generate", "Generate", "生成"),
        ("Config.Show", "Show", "显示"),
        ("Config.Test", "Test connection", "测试连接"),
        ("Config.Write", "Write client config", "写入客户端配置"),
        ("Config.Summary", "Summary", "连接摘要"),
        ("Config.Service", "Service", "服务"),
        ("Config.Address", "Address", "地址"),
        ("Config.Transport", "Transport", "传输方式"),
        ("Config.Idle", "idle", "空闲"),
        ("Config.Running", "running", "运行中"),
        ("Config.Local", "stdio", "stdio"),
        ("Config.NoSelection", "No client selected", "尚未选择客户端"),
        ("Config.Selected", "{0} selected", "已选 {0} 个"),
        ("Config.NoAddress", "Address not set", "未填写地址"),
        ("Config.LocalAddress", "stdio · local", "stdio · 本机"),
        ("Config.LastTest", "Last test · {0}", "上次测试 · {0}"),
        ("Config.TestNotRun", "Not run yet. TIA project connection not verified.", "尚未测试。尚未验证 TIA 工程连接。"),
        ("Config.TestFailed", "Failed. See activity log.", "失败，请查看活动日志。"),
        ("Config.Entries", "{0} entries", "{0} 条记录"),
        ("Config.Entry", "{0} entry", "{0} 条记录"),
        ("Config.SaveBoth", "Save both sides", "保存两端配置"),
        ("Config.NotChecked", "Not checked yet", "尚未检查"),
        ("Config.RunUpdate", "Update engine…", "更新引擎…"),
        ("Config.NeedsAttention", "Needs attention", "需要处理"),
        ("Config.Saved", "Saved", "已保存"),
        ("Config.Testing", "Testing…", "正在测试…"),
        ("Config.ConnectionOk", "Connection OK", "连接正常"),
        ("Config.ConfiguringNetwork", "Configuring network…", "配置网络…"),
        ("Config.NetworkConfigured", "Network configured", "网络已配置"),
        ("Config.ServiceStopped", "Service stopped", "服务已停止"),
        ("Config.ServiceRunning", "Service process running", "服务进程运行中"),
        ("Config.ClientsConfigured", "{0} clients configured", "已配置 {0} 个客户端"),
        ("Config.SelectRelease", "Select a runnable TIA Portal version.", "请选择可运行的 TIA Portal 版本。"),
        ("Config.ClientListSeparator", ", ", "，"),
        ("Config.ClientDetection", "Client detection: {0} (✓ = detected on this PC; undetected clients can still be configured)", "客户端检测：{0}（✓ = 本机检测到；未检测到的仍可写入）"),
        ("Config.ClientInstructionsCaption", "Client instructions", "客户端使用说明"),
        ("Config.BrowseTiaDescription", "Select the Portal V{0} installation directory, without Bin", "选择 Portal V{0} 安装目录，不带 Bin"),
        ("Config.Ready", "Ready. Configure the service and clients on one page, using the same secret on both sides.", "就绪。服务与客户端配置在同一页完成，两端使用同一密钥。"),
        ("Config.ChooseClients", "Select one or more clients. Saving writes their configuration automatically.", "选择一个或多个客户端，保存后将自动写入对应配置。"),
        ("Config.ClientInstructionsDetected", "{0}: {1} (Detected: {2})", "{0}：{1}（已检测到：{2}）"),
        ("Config.ClientInstructionsNotDetected", "{0}: {1} (Not detected: {2})", "{0}：{1}（未检测到：{2}）"),
        ("Config.HttpListenFailed", "HTTP listener failed ({0}): {1}. For access denied, click “Network permission”; if the port is in use, stop the old MCP or use another port.", "HTTP 监听失败（{0}）：{1}。拒绝访问时点击“网络权限”；端口占用时停止旧 MCP 或更换端口。"),
        ("Config.Unauthorized", "Authentication failed (401): check that both sides use the same shared secret.", "鉴权失败（401）：请检查两端连接密钥是否一致。"),
        ("Config.ConnectionFailed", "Connection failed: {0} Check the VM service, IP, port and firewall.", "连接失败：{0} 请检查虚拟机服务、IP、端口和防火墙。"),
        ("Config.TiaDetected", "Auto-detected V{0} installation directory ({1}): {2}", "已自动检测到 V{0} 安装目录（{1}）：{2}"),
        ("Config.TiaNotDetected", "Not auto-detected: {0}. Use “Browse” to select the Portal V{1} installation root manually.", "未自动检测到：{0}。请用“浏览”手动选择 Portal V{1} 安装根目录。"),
        ("Config.SavedReleaseMismatch", "The TIA version in the saved configuration does not match.", "已保存配置中的 TIA 版本不匹配。"),
        ("Config.ServerLoaded", "Loaded V{0} service configuration.", "已载入 V{0} 服务配置。"),
        ("Config.ClientConnectionSaved", "Client connection details were encrypted and saved for the current Windows user.", "客户端侧连接信息已按当前 Windows 用户加密保存。"),
        ("Config.ServerSaved", "Service configuration saved. Next: Network permission → Start service.", "服务端配置已保存。下一步：网络权限 → 启动服务。"),
        ("Config.ClientOnlySaved", "This PC failed service validation; only client details were saved: {0}", "本机未通过服务端校验，只保存了客户端侧信息：{0}"),
        ("Config.SelectClientsFirst", "Select one or more AI clients first.", "请先选择一个或多个 AI 客户端。"),
        ("Config.WriteClientsPrompt", "Exit the selected clients first to avoid concurrent configuration writes.\nOther settings will be preserved and the original files backed up:\n\n", "请先退出所选客户端，避免配置同时写入。\n将保留其它设置并备份原文件：\n\n"),
        ("Config.WriteClientsContinue", "\n\nClient configurations store the secret in their own format. Do not share files or backups. Continue?", "\n\n客户端配置按其格式保存密钥，请勿分享文件或备份。继续？"),
        ("Config.ClientSaved", "{0} saved: {1}", "{0} 已保存：{1}"),
        ("Config.RestartClients", "Restart the configured clients and use {0} to read the project tree. Do not let multiple AIs modify the same project at the same time.", "重启已配置的客户端，使用 {0} 读取工程树。不要让多个 AI 同时修改同一工程。"),
        ("Config.SomeClientsNotSaved", "Some clients were not saved; successful changes were retained:\n{0}", "部分客户端未保存，其它成功项已保留：\n{0}"),
        ("Config.EngineOutsideBundle", "Engine version unknown: this is not an extracted delivery bundle (manifest\\delivery.json is missing)", "引擎版本未知：这里不是解压后的交付包（没有 manifest\\delivery.json）"),
        ("Config.SourceRepositoryUpdate", "Source repository (.git present): do not update here; publish with dotnet run --project build-tools/release -- release -Version X.Y.Z -Summary <summary>", "源码仓库（有 .git）：不在这里更新，发布走 dotnet run --project build-tools/release -- release -Version X.Y.Z -Summary <summary>"),
        ("Config.CheckingUpdate", "Checking GitHub for the latest version…", "正在检查 GitHub 最新版本…"),
        ("Config.UpdateAvailable", "Update to {0}{1} · Stop the engine first, then click “Update engine…” below", "可更新到 {0}{1} · 先停引擎，再点下面的“更新引擎…”"),
        ("Config.UpdateAvailableLog", "Update check: {0} → {1}{2}; use “Update → Update engine…” ({3})", "检查更新：{0} → {1}{2}，菜单“更新 → 更新引擎…”执行（{3}）"),
        ("Config.UpToDate", "Up to date ({0})", "已是最新（{0}）"),
        ("Config.UpToDateLog", "Update check: {0} is up to date ({1})", "检查更新：{0} 已是最新（{1}）"),
        ("Config.CannotCheckUpdate", "Cannot check: {0}", "无法检查：{0}"),
        ("Config.UpdateCheckFailed", "Update check failed: {0}", "检查更新失败：{0}"),
        ("Config.FinishOperationsBeforeUpdate", "Finish project operations and disconnect the TIA session before updating the software.", "请先完成工程操作并断开 TIA 会话，再更新软件。"),
        ("Config.CannotUpdateSource", "This is a source repository; do not update here.", "这是源码仓库，不在这里更新。"),
        ("Config.StopServiceBeforeUpdate", "Click “Stop” to end the MCP started by this window before updating.", "先点“停止”结束本窗口启动的 MCP，再更新。"),
        ("Config.EnginesStillRunning", "Engines are still running; the updater will refuse: {0}. Stop them before updating (an AI client may have started them; close that session).", "引擎仍在运行，更新器会拒绝：{0}。请先停止它（可能是某个 AI 客户端启动的：关闭那个会话），再更新。"),
        ("Config.UpdaterMissing", "Updater not found: {0}. Download the complete delivery bundle again from GitHub Releases.", "找不到更新器 {0}。请从 GitHub Releases 重新下载完整交付包。"),
        ("Config.LatestVersion", "the latest version", "最新版"),
        ("Config.RunUpdatePrompt", "This application will close. The bundled C# updater will update\n{0}\nto {1}: download the ZIP and .sha256, verify SHA-256, back up to .previous, and replace the delivery files. This application reopens automatically when finished; on failure the console keeps the error details, and -Rollback restores the previous version.\n\nContinue?", "将关闭本程序，由随包 C# 更新器把\n{0}\n更新到 {1}：下载 ZIP 与 .sha256、校验 SHA-256、备份到 .previous 并替换交付文件。完成后自动重新打开本程序；失败时控制台保留错误信息，-Rollback 可恢复上一版。\n\n继续？"),
        ("Config.RunUpdateCaption", "Update engine", "更新引擎"),
        ("Config.UpdaterStarted", "The updater has started in a new window. This application will close.", "更新器已在新窗口启动，本程序即将关闭。"),
        ("Config.NetworkPrompt", "Authorize this HTTP address for the current user and allow the local subnet to access this port.\nWindows will ask for administrator permission next. Continue?", "为当前用户授权此 HTTP 地址，并放行本地子网到此端口。\n接下来会出现 Windows 管理员权限提示，继续？"),
        ("Config.NetworkIncomplete", "Network configuration did not finish. Check the errors in the administrator window.", "网络配置未完成，请查看管理员窗口中的错误信息。"),
        ("Config.NetworkReady", "Network permissions configured. You can now start the service.", "网络权限配置完成。现在可以启动服务。"),
        ("Config.ServiceAlreadyStarted", "This window has already started MCP.", "此窗口已经启动 MCP。"),
        ("Config.ServiceExited", "MCP exited with code: {0}", "MCP 已退出，退出码：{0}"),
        ("Config.ServiceNotStarted", "The MCP process did not start.", "MCP 进程未启动。"),
        ("Config.CheckListening", "Check the log for the listening message and test the connection from the host. Keep this window open.", "请检查日志中的 listening 提示，并在宿主机测试连接。保持此窗口打开。"),
        ("Config.StopServicePrompt", "This will stop the MCP started by this window and disconnect clients.\nMake sure no project operations are running. Continue?", "将停止本窗口启动的 MCP，中断客户端连接。\n请确认没有正在执行的工程操作。继续？"),
        ("Config.StopServiceCaption", "Stop MCP", "停止 MCP"),
        ("Config.WaitBeforeClosing", "Configuration is in progress. Wait before closing.", "正在处理配置，请稍候再关闭。"),
        ("Desktop.Configuration", "MCP & clients", "MCP 与客户端"),

        ("Primer.Transfer", "Import / Export", "导入 / 导出"),

        ("Primer.Bound", "Bound", "已绑定"),
        ("Primer.SelectAll", "Select all", "全选"),
        ("Primer.Clear", "Clear", "清空"),
        ("Primer.Name", "NAME", "名称"),
        ("Primer.Type", "TYPE", "类型"),
        ("Primer.Number", "NO.", "编号"),
        ("Primer.Language", "LANG", "语言"),
        ("Primer.Group", "GROUP PATH", "组路径"),
        ("Primer.Consistent", "CONSISTENT", "一致"),

        ("Primer.ExportXml", "Export · SimaticML XML", "导出 · SimaticML XML"),

        ("Primer.CompileSoftware", "Compile PLC software", "编译 PLC 软件"),
        ("Primer.Errors", "errors", "个错误"),
        ("Primer.Warnings", "warnings", "条警告"),
        ("Primer.Inspection", "Inspection", "检查"),
        ("Primer.ReadStatus", "Read status", "读取状态"),
        ("Primer.NewWorkspace", "New workspace", "新建工作区"),
        ("Primer.Mapping", "Object mapping", "对象映射"),
        ("Primer.WholeProject", "Whole project", "整个项目"),
        ("Primer.PreviewMapping", "Preview", "预览"),
        ("Primer.RunMapping", "Run mapping", "执行映射"),
        ("Primer.Sync", "Sync", "同步"),
        ("Primer.NotGitPush", "Not a git push", "不是 git push"),
        ("Primer.ToWorkspace", "→ Workspace", "→ 工作区"),
        ("Primer.ToProject", "→ Project", "→ 工程"),
        ("Primer.PreviewSync", "Preview sync", "预览同步"),
        ("Primer.RunSync", "Run sync", "执行同步"),
        ("Primer.MappedObjects", "Mapped objects", "已映射对象"),
        ("Primer.File", "FILE", "文件"),
        ("Primer.LocalDiff", "Local git diff", "本地 Git 差异"),
        ("Primer.WorkingTree", "Working tree", "工作树"),
        ("Primer.DiffScope", "Staged, unstaged and untracked changes. No branches, commits or remote sync here.", "包含已暂存、未暂存与未跟踪的变更。此处不涉及分支、提交或远端同步。"),
        ("Primer.NamingPattern", "Naming rule (regular expression)", "命名规则（正则表达式）"),
        ("Primer.Mapped", "mapped", "已映射"),
        ("Primer.Unsupported", "unsupported", "不支持"),

        ("Primer.All", "All", "全部"),
        ("Primer.Differ", "Differ", "差异"),
        ("Primer.Missing", "Missing", "缺失"),
        ("Primer.InspectFile", "Select this VCI object to inspect its local Git diff", "选择此 VCI 对象以查看本地 Git 差异"),
        // Client guidance, configuration validation and result summaries.
        ("Config.ClientDetected", "Detected", "已检测"),
        ("Config.ClientTooltipDetected", "{0}\nDetected: {1}\nWrite to: {2}", "{0}\n已检测到：{1}\n写入：{2}"),
        ("Config.ClientTooltipNotDetected", "{0}\nNot detected: {1}\nWrite to: {2}", "{0}\n未检测到：{1}\n写入：{2}"),
        ("Config.ClientHint.ClaudeCode", "Official desktop client: restart, select Code → Local, and start a new session. The CLI uses this configuration too.", "官方桌面客户端：重启后选择 Code → Local，新建会话。CLI 也使用此配置。"),
        ("Config.ClientHint.Codex", "After saving, restart the Codex desktop app / CLI and reopen your task to load MCP.", "保存后重启 Codex 桌面应用 / CLI，重新打开任务以加载 MCP。"),
        ("Config.ClientHint.Gemini", "Restart Gemini CLI and use /mcp to check the server status.", "重启 Gemini CLI，使用 /mcp 检查服务器状态。"),
        ("Config.ClientHint.Qwen", "Writes to Alibaba Qwen Code settings.json (the same format as Gemini CLI). Restart Qwen Code and use /mcp to check the server.", "写入阿里 Qwen Code 的 settings.json（格式同 Gemini CLI）。重启 Qwen Code，用 /mcp 检查服务器。"),
        ("Config.ClientHint.Kimi", "Writes to Moonshot Kimi Code CLI mcp.json, respecting KIMI_CODE_HOME. Restart, then start a new session once the status bar shows MCP is ready.", "写入月之暗面 Kimi Code CLI 的 mcp.json，尊重 KIMI_CODE_HOME。重启后状态栏显示 MCP 就绪即可新建会话。"),
        ("Config.ClientHint.CodeBuddy", "Writes to Tencent CodeBuddy Code CLI .mcp.json (select Hunyuan / DeepSeek or other models in CodeBuddy). Restart and check with /mcp.", "写入腾讯 CodeBuddy Code CLI 的 .mcp.json（混元 / DeepSeek 等模型在 CodeBuddy 里选）。重启后用 /mcp 检查。"),
        ("Config.ClientHint.QwenAgent", "Writes to Qwen Agent .qwen-agent\\mcp.json (url + Bearer header, without OAuth). Fully quit the Qwen Agent process, rather than just closing its window, then reopen it to reload. For a single project, place the same file in <project>\\.qwen-agent\\mcp.json.", "写入千问工作助理（Qwen Agent）的 .qwen-agent\\mcp.json（url + Bearer 头，不走 OAuth）。必须完全退出千问工作助理进程（不是关窗口）再打开才会重新读取；只对一个项目生效时把同名文件放到 <项目>\\.qwen-agent\\mcp.json。"),
        ("Config.ClientHint.Cursor", "Restart Cursor, then check and enable tia-portal-vm in MCP settings.", "重启 Cursor，在 MCP 设置中检查 tia-portal-vm 并启用。"),
        ("Config.ClientHint.VsCode", "Uses the default VS Code user configuration (Insiders if it is the only edition installed). Reload the window, then start and trust the service in the MCP server list.", "适用于 VS Code 默认用户配置（本机只有 Insiders 时写 Insiders）。重载窗口，在 MCP 服务器列表中启动并信任该服务。"),
        ("Config.ClientHint.OpenCode", "Writes to OpenCode opencode.json. Select {0} in the OpenCode provider settings; MCP configuration is independent of the model. Restart OpenCode and start a new session.", "写入 OpenCode 的 opencode.json；模型在 OpenCode 的 provider 里选 {0}，MCP 配置与模型无关。重启 OpenCode 后新建会话。"),
        ("Config.ClientModel.GLM", "Zhipu GLM", "智谱 GLM"),
        ("Config.ClientConfigFile", "Configuration file {0}", "配置文件 {0}"),
        ("Config.ClientConfigDirectory", "Configuration directory {0}", "配置目录 {0}"),
        ("Config.ClientExecutable", "{0} on PATH", "PATH 上的 {0}"),
        ("Config.ClientInstallDirectory", "Installation directory {0}", "安装目录 {0}"),
        ("Config.ClientInstalledProgram", "Installed program {0}", "已安装程序 {0}"),
        ("Config.ClientNotFound", "No configuration directory, executable, installation directory, or uninstall entry was found on this machine (you can still write the configuration; it will take effect after installation).", "本机没有它的配置目录、可执行文件、安装目录或卸载项（仍可写入，安装后即生效）"),
        ("Config.InvalidClientJson", "The existing client configuration is not a JSON object. It has not been modified.", "现有客户端配置不是 JSON 对象，未修改。"),
        ("Config.UnclosedJsonComment", "A JSON comment is not closed. The configuration has not been modified.", "JSON 注释未闭合，未修改配置。"),
        ("Config.UnsupportedTomlTable", "The Codex configuration uses inline or special MCP table definitions that cannot be safely merged. The original file has not been modified.", "Codex 配置使用内联或特殊 MCP 表定义，无法安全合并；原文件未修改。"),
        ("Config.UnclosedTomlMultiline", "A TOML multiline string is not closed. The original file has not been modified.", "TOML 多行字符串未闭合，原文件未修改。"),
        ("Config.UnclosedTomlString", "A TOML string is not closed. The original file has not been modified.", "TOML 字符串未闭合，原文件未修改。"),
        ("Config.InvalidServerMap", "The existing {0} is not a JSON object. It has not been modified.", "现有 {0} 不是 JSON 对象，未修改。"),
        ("Config.InvalidEndpoint", "Enter a complete IPv4 address and a port from 1–65535, rather than a web link. Example: 192.0.2.10", "请填写完整 IPv4 地址和 1–65535 范围的端口，不要粘贴网页链接。示例：192.0.2.10"),
        ("Config.InvalidSecret", "The connection secret must not be empty or contain line breaks or control characters.", "连接密钥不能为空，也不能包含换行或控制字符。"),
        ("Config.TiaEnvironmentSource", "TiaPortalLocation environment variable", "TiaPortalLocation 环境变量"),
        ("Config.TiaDefaultSource", "Default installation directory", "默认安装目录"),
        ("Config.InvalidClaudeJson", "The existing Claude configuration is not a JSON object. It has not been modified.", "现有 Claude 配置不是 JSON 对象，未修改。"),
        ("Config.RemoteNotReady", "The HTTP service is reachable, but MCP is not ready. Check the service log in the virtual machine.", "HTTP 服务可达，但 MCP 尚未就绪。请检查虚拟机中的服务日志。"),
        ("Config.UnknownVersion", "Unknown", "未知"),
        ("Config.EngineNotFound", "The {0} engine was not found. Place the configurator in the root of the complete Release bundle, alongside the runtime folder.", "找不到 {0} 引擎。请将配置程序放在完整 Release 包的根目录，与 runtime 文件夹同级。"),
        ("Config.TiaRegistrySource", "Registry TIAP{0}\\TIA_Opns", "注册表 TIAP{0}\\TIA_Opns"),
        ("Config.TiaNotFound", "No V{0} Openness installation was found in the environment variable, registry, or default directories.", "环境变量、注册表和默认目录都没有 V{0} 的 Openness 安装"),
        ("Config.TiaApiNotFound", "The {0} Openness API ({1}) was not found in this directory. Select the installation root or the corresponding PublicAPI directory.", "该目录未找到 {0} Openness API（{1}）。请选择安装根目录或对应 PublicAPI 目录。"),
        ("Config.RemoteReady", "HTTP is reachable, authentication passed, and MCP is ready. Version: {0}. The TIA project connection has not been verified.", "HTTP 可达，鉴权通过，MCP 已就绪。版本：{0}。尚未验证 TIA 工程连接。"),
        ("Config.InvalidReleaseJson", "GitHub did not return a release JSON object.", "GitHub 返回的不是 release JSON。"),
        ("Config.InvalidReleaseTag", "The release tag is not a version number: {0}", "release 的 tag 不是版本号：{0}"),
        ("Config.MissingReleaseTag", "The release page did not provide the latest version tag (API: {0}).", "发布页没有给出最新版本的 tag（API：{0}）"),
        ("Config.UpdateUnreachable", "This machine cannot reach github.com: {0}. Check your network or proxy, then select “Check for updates” again.", "这台机器访问不到 github.com：{0}。检查网络或代理后再点“检查更新”。"),
        ("Primer.ExportSource", "Export · Source text", "导出 · 源文本"),
        ("Primer.Yes", "Yes", "是"),
        ("Primer.No", "No", "否"),
        ("Primer.Protected", "Protected", "受保护"),
        ("Primer.Identical", "Identical", "一致"),
        ("Primer.Differs", "Differs", "有差异"),
        ("Primer.Unknown", "Unknown", "未知"),
        ("Primer.RuleNaming", "Naming", "命名"),
        ("Primer.RuleAuthor", "Author", "作者"),
        ("Primer.RuleConsistency", "Consistency", "一致性"),
        ("Primer.RuleKnowHow", "Know-how", "专有技术"),
        ("Primer.RuleUnused", "Unused", "未使用"),
        ("Primer.NotRun", "Not run", "未执行"),
        ("Primer.CompileErrors", "Errors", "错误"),
        ("Primer.CompileWarnings", "Warnings", "警告"),
        ("Primer.CompileCompleted", "Completed", "已完成"),
        ("Primer.BlocksSummary", "{0} blocks · {1} selected · {2} shown", "{0} 个块 · 已选 {1} · 显示 {2}"),
        ("Primer.WorkspaceSummary", "{0} · {1} mapped · {2} differ", "{0} · {1} 已映射 · {2} 差异"),
        ("Primer.InspectionSummary", "Checked {0} blocks, found {1} issues.", "检查 {0} 个块，发现 {1} 个问题。"),
        ("Primer.SyncPreview", "Preview: {0} objects expected to sync · {1} already identical.", "预览：{0} 个对象需要同步，{1} 个已相同。"),
        // ---- shell -----------------------------------------------------------------
        ("App.Title",                  "TIA Portal Workbench", "TIA Portal 工作台"),
        ("Badge.NoVersion",            "TIA —", "TIA —"),
        ("Badge.Version",              "TIA {0}", "TIA {0}"),

        // ---- header actions --------------------------------------------------------
        ("Toolbar.Mock",               "Mock", "模拟"),
        ("Toolbar.Mock.Tip",           "Run against a synthetic project; no TIA Portal needed",
                                       "使用合成项目运行,无需安装 TIA Portal"),
        ("Toolbar.Headless",           "Headless", "无界面"),
        ("Toolbar.Headless.Tip",       "Start TIA Portal without its window. It cannot show the first-connect trust dialog.",
                                       "以无窗口方式启动 TIA Portal。它无法显示首次连接的信任对话框。"),
        ("Toolbar.Doctor",             "Doctor", "环境检查"),
        ("Toolbar.Doctor.Tip",         "Check every Openness precondition on this machine",
                                       "检查本机是否满足 Openness 的全部前置条件"),
        ("Toolbar.Connect",            "Connect", "连接"),
        ("Toolbar.Connect.Tip",        "Start TIA Portal, or attach to one that is already running",
                                       "启动 TIA Portal,或附加到已在运行的实例"),
        ("Toolbar.Compile",            "Compile", "编译"),
        ("Toolbar.Inspect",            "Inspect", "审查"),
        ("Toolbar.Import",             "Import…", "导入…"),


        // ---- project row -----------------------------------------------------------
        ("Project.Label",              "Project", "项目"),
        ("Project.Placeholder",        "Path to an .ap15_1 … .ap21 project file",
                                       ".ap15_1 / .ap21 项目文件的路径"),
        ("Common.Browse",              "Browse…", "浏览…"),
        ("Common.Open",                "Open", "打开"),
        ("Common.Reload",              "Refresh", "刷新"),

        // ---- sidebar ---------------------------------------------------------------
        ("Sidebar.Devices",            "Devices", "设备"),
        ("Sidebar.Empty",              "Devices will be listed here once you connect and open a project.",
                                       "连接并打开项目后\n此处将列出设备"),

        // ---- tabs ------------------------------------------------------------------
        ("Tab.Log",                    "Log", "日志"),

        // ---- blocks ----------------------------------------------------------------

        ("Blocks.Count",               "{0} block(s)", "共 {0} 个程序块"),
        ("Blocks.Selected",            "{0} of {1} selected", "已选择 {0}/{1}"),
        ("Blocks.Empty.Title",         "No project open", "尚未打开项目"),

        ("Blocks.ExportTo",            "Export to", "导出到"),
        ("Blocks.SourceFormat",        "Source text", "源文本"),
        ("Blocks.SourceFormat.Tip",    "Export source through the native Openness adapter. Mock mode uses synthetic source text.",
                                      "通过本地 Openness 适配器导出源文件。模拟模式生成示例源文本。"),
        ("Blocks.Export",              "Export", "导出"),
        ("Block.Protected",            "know-how protected", "专有技术保护"),
        ("Block.NeedsCompiling",       "needs compiling", "需要先编译"),

        // The categories TIA splits a PLC's software into, named as TIA names them.
        ("Tree.ProgramBlocks",         "Program blocks", "程序块"),
        ("Tree.DataTypes",             "PLC data types", "PLC 数据类型"),
        ("Tree.Tags",                  "PLC tags", "PLC 变量"),
        ("Tree.HmiScreens",            "Screens", "画面"),

        // ---- version control -------------------------------------------------------
        ("Vc.NoWorkspace",             "No workspace selected. Create one over your Git working tree below.",
                                       "尚未选择工作区。请在下方基于 Git 工作树创建一个。"),
        ("Vc.New",                     "New", "新建"),
        ("Vc.In",                      "in", "位于"),
        ("Vc.Create",                  "Create", "创建"),
        ("Vc.Folder.Tip",              "An existing folder — normally your Git working tree",
                                       "一个已存在的文件夹 — 通常就是你的 Git 工作树"),
        ("Vc.ShowAll",                 "Show in-sync objects", "显示已同步的对象"),
        ("Vc.Empty.Title",             "No workspace yet", "尚无工作区"),
        ("Vc.Empty.Body",              "The Version Control Interface maps the project onto a folder, one text file per object. Availability depends on the project and installed Openness capabilities.",
                                       "版本控制接口会把项目映射到一个文件夹,每个对象一个文本文件。可用性取决于项目和已安装的 Openness 功能。"),
        ("Col.State",                  "State", "状态"),
        ("Col.Object",                 "Object", "对象"),

        ("Vc.Diff.Unchanged",          "{0}: no uncommitted change in the workspace file.",
                                       "{0}:工作区文件没有未提交的改动。"),

        // ---- log -------------------------------------------------------------------
        ("Log.Title",                  "Log", "日志"),
        ("Log.Copy",                   "Copy", "复制"),
        ("Log.Clear",                  "Clear", "清空"),

        // ---- status bar ------------------------------------------------------------
        ("Status.NotConnected",        "Not connected.", "未连接"),
        ("Status.HeadlessMode",        "Headless mode", "无界面模式"),
        ("Status.MockMode",            "Mock mode", "模拟模式"),
        ("Status.Working",             "{0}…", "{0}…"),
        ("Status.CheckingEnvironment", "Checking environment", "正在检查环境"),
        ("Status.Connecting",          "Connecting to TIA Portal", "正在连接 TIA Portal"),
        ("Status.OpeningProject",      "Opening project", "正在打开项目"),
        ("Status.ReadingBlocks",       "Reading blocks of {0}", "正在读取 {0} 的程序块"),
        ("Status.Exporting",           "Exporting", "正在导出"),
        ("Status.Importing",           "Importing", "正在导入"),
        ("Status.Compiling",           "Compiling", "正在编译"),
        ("Status.Inspecting",          "Inspecting", "正在审查"),
        ("Status.SavingProject",       "Saving project", "正在保存项目"),
        ("Status.ReadingVc",           "Reading version control", "正在读取版本控制"),
        ("Status.CreatingWorkspace",   "Creating workspace", "正在创建工作区"),
        ("Status.MappingProject",      "Mapping project", "正在映射项目"),
        ("Status.ComparingWorkspace",  "Comparing with workspace", "正在与工作区比较"),
        ("Status.Synchronizing",       "Synchronizing {0}", "正在同步 {0}"),
        ("Status.EnvOk",               "Environment OK.", "环境正常。"),
        ("Status.EnvNotReady",         "Environment not ready — see the log.", "环境未就绪 — 详见日志。"),
        ("Status.Connected",           "Connected ({0}, Openness {1}).", "已连接({0},Openness {1})。"),
        ("Status.ProjectOpen",         "Project {0} open.", "项目 {0} 已打开。"),
        ("Status.BlocksIn",            "{0} block(s) in {1}.", "{1} 中共 {0} 个程序块。"),
        ("Status.Exported",            "Exported {0}/{1} to {2}", "已导出 {0}/{1} 到 {2}"),
        ("Status.ExportedFailed",      "Exported {0}/{1} to {2} ({3} failed)", "已导出 {0}/{1} 到 {2}({3} 个失败)"),
        ("Status.Imported",            "Imported {0}/{1} file(s). Not saved yet.", "已导入 {0}/{1} 个文件。尚未保存。"),
        ("Status.CompileResult",       "{0}: {1} error(s), {2} warning(s) in {3}s",
                                       "{0}:{1} 个错误,{2} 个警告,耗时 {3} 秒"),
        ("Status.InspectResult",       "{0} finding(s) over {1} block(s).", "在 {1} 个程序块中发现 {0} 处问题。"),
        ("Status.ProjectSaved",        "Project saved.", "项目已保存。"),
        ("Status.VcUnsupported",       "This project exposes no Version Control Interface in the current installation.",
                                       "当前安装环境中的该项目未提供版本控制接口。"),
        ("Status.VcNoWorkspace",       "No workspace yet. Point one at your Git working tree and create it.",
                                       "还没有工作区。请指向你的 Git 工作树并创建一个。"),
        ("Status.VcWorkspaces",        "{0} workspace(s).", "共 {0} 个工作区。"),
        ("Status.VcInSync",            "{0} mapped object(s), all in sync — nothing to commit.",
                                       "已映射 {0} 个对象,全部同步 — 无需提交。"),
        ("Status.VcDiffer",            "{0} mapped object(s), {1} differ.", "已映射 {0} 个对象,其中 {1} 个存在差异。"),
        ("Status.VcCreated",           "Workspace created. Now map the project into it.",
                                       "工作区已创建。接下来把项目映射进去。"),
        ("Status.VcMapDry",            "Dry run: {0} would be mapped, {1} already, {2} unsupported. Clear Dry run to apply.",
                                       "预演:将映射 {0} 个,已映射 {1} 个,{2} 个不支持。取消勾选“预演”才会实际执行。"),
        ("Status.VcMapApplied",        "Mapped {0}, already {1}, unsupported {2}, failed {3}.",
                                       "已映射 {0} 个,原已映射 {1} 个,不支持 {2} 个,失败 {3} 个。"),
        ("Status.VcSyncDry",           "Dry run: {0} would sync {1}, {2} already equal. Clear Dry run to apply.",
                                       "预演:将同步 {0} 个({1}),{2} 个已一致。取消勾选“预演”才会实际执行。"),
        ("Status.VcSyncApplied",       "{0} synchronized, {1} failed, {2} already equal.",
                                       "已同步 {0} 个,失败 {1} 个,{2} 个已一致。"),

        // ---- log lines -------------------------------------------------------------
        ("Log.BridgeStarted",          "bridge started ({0}).", "bridge 已启动({0})。"),
        ("Log.BridgeExited",           "bridge process exited.", "bridge 进程已退出。"),
        ("Log.EnvironmentHeader",      "--- environment ---", "--- 运行环境 ---"),
        ("Log.Installed",              "installed: V{0} {1}", "已安装:V{0} {1}"),
        ("Log.Attached",               "attached to an open project: {0}", "已附加到打开的项目:{0}"),
        ("Log.Opened",                 "opened {0} ({1})", "已打开 {0}({1})"),
        ("Log.DeviceCount",            "{0} device(s).", "共 {0} 个设备。"),
        ("Log.Failed",                 "FAILED {0}: {1}", "失败 {0}:{1}"),
        ("Log.Error",                  "error: {0}", "错误:{0}"),
        ("Log.InspectionHeader",       "--- inspection of {0} ---", "--- {0} 的审查结果 ---"),
        ("Log.WorkspaceCreated",       "created workspace {0} at {1}", "已创建工作区 {0},位置 {1}"),
        ("Log.CommitHint",             "Commit from {0}:  git add -A && git commit",
                                       "在 {0} 中提交:git add -A && git commit"),
        ("Log.PullHint",               "The project now holds the workspace's version — compile and save it.",
                                       "项目现在是工作区中的版本 — 请编译并保存。"),

        ("Actor.Title", "Human / AI", "人 / AI"),
        ("Actor.AI", "AI", "AI"),
        ("Actor.Human", "Human", "人"),
        ("Actor.Unrecorded", "Unrecorded", "未记录"),
        ("Actor.Workbench", "Workbench (human)", "工作台（人）"),
        ("Actor.McpClient", "MCP client (AI)", "MCP 客户端（AI）"),
        ("Calls.HumanOnly", "Human only", "只看人"),
        ("Calls.AiOnly", "AI only", "只看 AI"),
        ("Calls.McpSession", "MCP session hash", "MCP 会话哈希"),

        // ---- dialogs ---------------------------------------------------------------
        ("Dialog.OpenProject.Title",   "Open a TIA Portal project", "打开 TIA Portal 项目"),
        ("Dialog.OpenProject.Filter",  "TIA Portal projects|*.ap21;*.ap20;*.ap19;*.ap18;*.ap17;*.ap16;*.ap15_1|All files|*.*",
                                       "TIA Portal 项目|*.ap21;*.ap20;*.ap19;*.ap18;*.ap17;*.ap16;*.ap15_1|所有文件|*.*"),
        ("Dialog.Export.Title",        "Choose the export folder", "选择导出文件夹"),
        ("Dialog.Workspace.Title",     "Choose the workspace folder (your Git working tree)",
                                       "选择工作区文件夹(你的 Git 工作树)"),
        ("Dialog.Import.Title",        "Select blocks to import", "选择要导入的程序块"),
        ("Dialog.Import.Filter",       "Blocks and sources (*.xml;*.scl;*.db;*.udt)|*.xml;*.scl;*.db;*.udt",
                                      "程序块与源文件 (*.xml;*.scl;*.db;*.udt)|*.xml;*.scl;*.db;*.udt"),
        ("Dialog.Import.Caption",      "Import", "导入"),
        ("Dialog.Import.Text",         "Replace blocks that already exist in the project?\n\nNo  = fail on blocks that already exist (safer)\nYes = overwrite them",
                                       "是否替换项目中已存在的程序块?\n\n否 = 遇到已存在的块即失败(更安全)\n是 = 直接覆盖"),
        ("Dialog.Save.Caption",        "Save", "保存"),
        ("Dialog.Save.Text",           "Save the project to disk? This cannot be undone.",
                                       "确定把项目保存到磁盘吗?此操作不可撤销。"),
        ("Dialog.Pull.Caption",        "Restore from workspace", "从工作区恢复"),
        ("Dialog.Pull.Text",           "Read the workspace's text files back INTO the project?\n\nThis OVERWRITES blocks in the open project and cannot be undone.\nCompile and save afterwards.",
                                       "确定把工作区的文本文件读回项目吗?\n\n这会覆盖已打开项目中的程序块,且不可撤销。\n完成后请编译并保存。"),
        ("Dialog.Error.Caption",       "Unexpected error", "未预期的错误"),
        ("Dialog.Error.Details",       "Details written to {0}", "详细信息已写入 {0}"),
        .. FeaturePageCatalogue,
    ];

    public static readonly IReadOnlyDictionary<string, string> English = Build(static e => e.En);

    public static readonly IReadOnlyDictionary<string, string> Chinese = Build(static e => e.Zh);

    private static IReadOnlyDictionary<string, string> Build(Func<(string Key, string En, string Zh), string> pick)
    {
        var table = new Dictionary<string, string>(Catalogue.Length, StringComparer.Ordinal);
        foreach (var entry in Catalogue) table[entry.Key] = pick(entry);
        return table;
    }
}
