"""Ratchet historical C# comment lines and Leftovers files, independent of paths.

Categories overlap. Statement and tool-count detection are lexical heuristics,
not a C# parser or a claim that a roster count is semantically out of date.
The source/baseline helpers are also used by Check-McpText.py.
"""
import argparse
from bisect import bisect_right
from collections import Counter
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import sys
import unittest

ROOT = Path(__file__).resolve().parents[2]
BASELINE = Path('scripts/checks/comment-hygiene-baseline.json')
KINDS = ('product-version', 'old-phase', 'maintainer', 'tombstone',
         'commented-code', 'tool-count', 'leftovers-file')
PATTERNS = {
    'product-version': re.compile(r'(?<![\w.])[vV]?[23]\.(?:\d+|[xX])(?:\.(?:\d+|[xX]))*(?![\w.])'),
    'old-phase': re.compile(r'\bphase\s*\d+\b|\bsub[ -]?batch\b|子批次', re.I),
    'maintainer': re.compile(r'\bmaintainer(?:s|\b)|\basckye\b|维护者', re.I),
    'tombstone': re.compile(r'\b(?:moved|relocated|extracted)\s+to\b|已(?:移|迁)|移至|迁至', re.I),
    'tool-count': re.compile(r'\b\d+\s+tools\b|\d+\s*(?:个|条)?工具|工具(?:数|数量|共|总计)[：:为是\s]*\d+', re.I),
}
DIRECTIVE_COMMENT = re.compile(r'"(?:\\.|[^"\\])*"|//[^\n]*|/\*.*?\*/')

# Import, rather than fork, the reviewed lexer. Its tokens retain all #if arms.
spec = importlib.util.spec_from_file_location('hygiene_lexer', Path(__file__).with_name('Check-SwallowedExceptions.py'))
lexer = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = lexer
spec.loader.exec_module(lexer)


class CommentLexer(lexer.Lexer):
    """Keep comments from recursive interpolation scans as well as outer code."""
    def __init__(self, source):
        super().__init__(source)
        self.comments = []

    def scan(self, interpolation=0):
        tokens, comments = super().scan(interpolation)
        self.comments.extend(comments)
        # The base lexer treats directives as opaque. Recover trailing comments
        # without mistaking // inside a #line filename for a comment.
        for token in tokens:
            if token.kind != 'directive':
                continue
            raw = self.source[token.start:token.end]
            for match in DIRECTIVE_COMMENT.finditer(raw):
                if match[0].startswith('/'):
                    self.comments.append(lexer.Token('comment', match[0], token.start + match.start(),
                                                     token.start + match.end()))
        return tokens, comments


def source_files(root, errors, include_project=lambda project: True):
    """Yield non-generated product sources using the swallowed-catch exclusions."""
    for relative in lexer.SOURCE_ROOTS:
        directory = root / relative
        if not directory.is_dir():
            errors.append(f'missing source root: {relative}')
            continue
        for parent, dirs, names in os.walk(directory, onerror=lambda exc: errors.append(str(exc))):
            dirs[:] = sorted(name for name in dirs if name.lower() not in lexer.SKIP_DIRS
                             and not name.startswith('TiaMcp.WorkerProtocol'))
            for name in sorted(names):
                if not name.lower().endswith('.cs') or name.lower().endswith(lexer.GENERATED_SUFFIXES):
                    continue
                path = Path(parent) / name
                project = 'openness-shared' if relative == lexer.SOURCE_ROOTS[1] else path.relative_to(directory).parts[0]
                if not include_project(project):
                    continue
                try:
                    source = path.read_text(encoding='utf-8-sig')
                    header = re.match(r'\s*(?:(?://[^\n]*(?:\n|$)|/\*.*?\*/)\s*)*', source, re.S)[0]
                    if not re.search(r'<auto-generated\b', header, re.I):
                        yield path.relative_to(root).as_posix(), project, source
                except (OSError, ValueError) as exc:
                    errors.append(f'{path.relative_to(root).as_posix()}: {exc}')


def fingerprint(kind, value):
    payload = json.dumps([kind, value], ensure_ascii=False, separators=(',', ':'))
    return hashlib.sha256(payload.encode('utf-8')).hexdigest()


def commented_statement(text):
    if not text.endswith(';'):
        return False
    try:
        tokens, _ = lexer.Lexer(text).scan()
        pairs = lexer.matching_pairs(tokens)
    except (ValueError, IndexError):
        return False
    values = [token.value for token in tokens]
    if not values or values[-1] != ';':
        return False
    if values[0] in ('return', 'throw', 'break', 'continue', 'yield'):
        return True
    # Parse a simple declaration or lvalue followed by assignment, increment or
    # invocation; reject prose preceding a code example ("call F();").
    i = 0
    if len(tokens) > 2 and all(t.kind == 'identifier' for t in tokens[:2]) and values[2] == '=':
        i = 1
    if tokens[i].kind != 'identifier':
        return False
    i += 1
    while i < len(tokens):
        if values[i] in ('.', '?.') and i + 1 < len(tokens) and tokens[i + 1].kind == 'identifier':
            i += 2
        elif values[i] in ('[', '(') and i in pairs:
            closing = pairs[i]
            if values[i] == '(' and closing == len(tokens) - 2:
                return True
            i = closing + 1
        else:
            break
    return i < len(tokens) - 1 and values[i] in ('=', '+=', '-=', '??=', '++', '--')


def product_version(text):
    for match in PATTERNS['product-version'].finditer(text):
        # Native version evidence and manual section numbers must survive cleanup.
        prefix = text[:match.start()]
        native = match[0].startswith('V') and re.search(r'\b(?:FW|firmware|S7TIA|SafetySystemVersion|OrderNumber|PN|expansions)\b', text)
        if native or re.search(r'\b(?:FW|firmware|CAEX|manual|section|chapter)\s*(?:[><=]+\s*)?$', prefix, re.I):
            continue
        # Numbered Openness setup instructions are not product releases.
        if not prefix.strip() and re.match(r'\s+(?:nuget\b|Api\.)', text[match.end():], re.I):
            continue
        return True
    return False


def scan_source(source, path, project):
    scanner = CommentLexer(source)
    scanner.scan()
    newlines = [i for i, char in enumerate(source) if char == '\n']
    rows, lines = [], {}
    for comment in sorted(scanner.comments, key=lambda token: token.start):
        offset = comment.start
        for raw in comment.value.splitlines(keepends=True):
            line = bisect_right(newlines, offset) + 1
            offset += len(raw)
            text = re.sub(r'^(?:///?|/\*+|\*)\s?', '', raw.strip())
            text = re.sub(r'\s*\*/$', '', text).strip()
            lines.setdefault(line, []).append(text)
    for line, pieces in lines.items():
        text = ' '.join(pieces)
        kinds = [kind for kind, pattern in PATTERNS.items() if pattern.search(text)]
        if 'product-version' in kinds and not product_version(text):
            kinds.remove('product-version')
        # Counts of third-party client limits are not repository rosters.
        if 'tool-count' in kinds and re.search(r'\b(?:Windsurf|capped|limit|maximum)\b', text, re.I):
            kinds.remove('tool-count')
        if any(commented_statement(piece) for piece in pieces):
            kinds.append('commented-code')
        for kind in kinds:
            rows.append(dict(kind=kind, fingerprint=fingerprint(kind, re.sub(r'\s+', ' ', text)),
                             path=path, line=line, project=project))
    if 'leftovers' in Path(path).name.lower():
        # This category is deliberately a file-count budget, independent of name/content.
        rows.append(dict(kind='leftovers-file', fingerprint=fingerprint('leftovers-file', None),
                         path=path, line=1, project=project))
    return rows


def scan(root):
    rows, errors, projects = [], [], Counter()
    for path, project, source in source_files(root, errors):
        projects[project] += 1
        try:
            rows.extend(scan_source(source, path, project))
        except (ValueError, IndexError) as exc:
            errors.append(f'{path}: {exc}')
    return rows, errors, projects


def baseline_rows(rows):
    return sorted(({key: value for key, value in row.items() if key != 'project'} for row in rows),
                  key=lambda row: (row['fingerprint'], row['path'], row['line']))


def read_baseline(path, kinds):
    data = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(data, dict) or data.get('format') != 1 or not isinstance(data.get('entries'), list):
        raise ValueError(f'{path}: unsupported baseline format')
    for row in data['entries']:
        if (not isinstance(row, dict) or row.get('kind') not in kinds
                or not isinstance(row.get('fingerprint'), str)
                or not re.fullmatch(r'[0-9a-f]{64}', row['fingerprint'])
                or not isinstance(row.get('path'), str)
                or type(row.get('line')) is not int or row['line'] < 1
                or ('cjk' in row and (type(row['cjk']) is not int or row['cjk'] < 1))):
            raise ValueError(f'{path}: invalid baseline entry: {row!r}')
    return data['entries']


def write_baseline(path, current, previous, initialize=False):
    if initialize and path.exists():
        raise ValueError('--allow-growth is only permitted when creating a reviewed initial baseline')
    added, _ = lexer.difference(current, previous)
    if added and not initialize:
        raise ValueError(f'refusing baseline growth: {len(added)} new/changed entries')
    data = dict(format=1, fingerprint='sha256 of category and normalized comment line/literal; '
                'Leftovers is a file count; paths/lines are informational; multiplicity is retained', entries=current)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n', encoding='utf-8', newline='\n')


def check_baseline(rows, errors, path, kinds, update=False, allow_growth=False):
    current = baseline_rows(rows)
    try:
        previous = [] if update and allow_growth and not path.exists() else read_baseline(path, kinds)
        added, removed = lexer.difference(current, previous)
        if update and not errors:
            write_baseline(path, current, previous, allow_growth)
            print(f'Wrote {len(current)} baseline entries to {path}.')
        else:
            errors.extend(f'{row["path"]}:{row["line"]}: new/changed {row["kind"]} {row["fingerprint"]}' for row in added)
        print(f'Baseline: {len(current)} current, {len(added)} added, {len(removed)} disappeared '
              '(--update-baseline retains only current entries).')
    except (OSError, ValueError) as exc:
        errors.append(str(exc))
    for error in errors:
        print('[FAIL] ' + error)
    print(f'Check: {len(errors)} issue(s).')
    return bool(errors)


def print_inventory(rows, projects):
    print('Project | files | ' + ' | '.join(KINDS))
    for project in sorted(projects):
        counts = Counter(row['kind'] for row in rows if row['project'] == project)
        print(f'{project} | {projects[project]} | ' + ' | '.join(str(counts[kind]) for kind in KINDS))
    counts = Counter(row['kind'] for row in rows)
    print(f'Total: {sum(projects.values())} files; ' + ', '.join(f'{kind}={counts[kind]}' for kind in KINDS))


def arguments(description, baseline):
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('--root', type=Path, default=ROOT)
    parser.add_argument('--baseline', type=Path, help=f'default: <root>/{baseline.as_posix()}')
    parser.add_argument('--update-baseline', action='store_true', help='retain only existing current entries')
    parser.add_argument('--allow-growth', action='store_true', help='reviewed first initialization only; refuses an existing file')
    parser.add_argument('--self-test', action='store_true')
    args = parser.parse_args()
    if args.allow_growth and not args.update_baseline:
        parser.error('--allow-growth requires --update-baseline')
    return args


class SelfTests(unittest.TestCase):
    def rows(self, source, path='sample.cs'):
        return scan_source(source, path, 'sample')

    def test_categories(self):
        fixtures = {'product-version': '// 2.7.41: fixed\n/* v3.x compatibility */',
                    'old-phase': '// Phase 6 sub-batch 2\n// sub batch 3',
                    'maintainer': '// The maintainer requested this\n// 维护者原话',
                    'tombstone': '// moved to Other.cs\n/* 已迁至 Other */',
                    'commented-code': '// group?.Blocks.ForEach(b => F(b));\n/* var x = 1; */',
                    'tool-count': '// full roster: 212 tools\n// 共488个工具'}
        for kind, source in fixtures.items():
            with self.subTest(kind=kind):
                self.assertEqual([kind, kind], [row['kind'] for row in self.rows(source)])
        self.assertEqual(['leftovers-file'], [row['kind'] for row in self.rows('', 'NewLeftovers.cs')])

    def test_strings_are_not_comments(self):
        source = '''var a = "// 2.1.0: Phase 2 maintainer moved to X;";
            var b = @"/* 3.0: ""maintainer"" */";
            var c = $"// Phase 4 {F("// 2.0")}";
            var d = $$"""// 2.0 {{F("/* 3.0 */")}}"""; var e = '/';'''
        self.assertEqual([], self.rows(source))

    def test_all_branches_and_interpolation_comments(self):
        source = '''#if V20 // 2.0: old
            // Phase 2
            #else
            /* Phase 3 */
            #endif
            var s = $"{F(/* 3.1: old */ 1)}";'''
        self.assertEqual(Counter({'product-version': 2, 'old-phase': 2}), Counter(r['kind'] for r in self.rows(source)))
        self.assertEqual([], self.rows('#line 1 "https://host/2.0/source.cs"'))

    def test_statement_heuristic(self):
        for text in ('return false;', 'throw new Exception("x");', 'group = (T)group.Parent;',
                     'F();', 'x++;', 'a[0] = 1;'):
            self.assertTrue(commented_statement(text), text)
        for text in ('The engine calls F();', 'Some prose;', 'Example: F();', 'Version 2.0', 'call F();'):
            self.assertFalse(commented_statement(text), text)

    def test_overlap_line_units_and_native_versions(self):
        rows = self.rows('/* Phase 2 (2.7.0): maintainer\n * moved to X\n */')
        self.assertEqual(4, len(rows))
        self.assertEqual([1, 1, 1, 2], [r['line'] for r in rows])
        self.assertEqual([], self.rows('// TIA V20 / PLCSIM V21\n// Windsurf is capped at 100 tools'))
        self.assertEqual([], self.rows('// FW >= 2.9\n// S7TIA V2.0\n// CAEX 2.15\n// manual 3.2.3\n// 2.1 nuget package'))
        self.assertEqual(1, len(self.rows('// 2.7.53: tested FW V2.9')))
        self.assertEqual(1, len(self.rows('// V3.1.0: old')))
        before = self.rows('/* 2.0 old */ Work();')
        after = self.rows('/* 2.0 old */ Work(); /* 3.0 new */')
        self.assertEqual(1, len(after))
        self.assertNotEqual(before[0]['fingerprint'], after[0]['fingerprint'])

    def test_multiset_move_and_shrink(self):
        previous = baseline_rows(self.rows('// 2.0: old'))
        moved = baseline_rows(self.rows('\n// 2.0: old', 'other/project.cs'))
        self.assertEqual(([], []), lexer.difference(moved, previous))
        self.assertEqual((previous, []), lexer.difference(previous * 2, previous))
        with lexer.scratch_directory() as root:
            path = root / 'baseline.json'
            write_baseline(path, previous, [], True)
            before = path.read_bytes()
            for rows, initialize in ((previous * 2, False), ([], True), (self.rows('// 3.0: new'), False)):
                with self.assertRaises(ValueError):
                    write_baseline(path, rows, previous, initialize)
                self.assertEqual(before, path.read_bytes())
            write_baseline(path, [], previous)
            self.assertEqual([], read_baseline(path, KINDS))

    def test_exclusions_and_missing_root(self):
        with lexer.scratch_directory() as root:
            for relative in lexer.SOURCE_ROOTS:
                (root / relative).mkdir(parents=True)
            base = root / lexer.SOURCE_ROOTS[0]
            for name in ('P/A.cs', 'P/bin/A.cs', 'P/obj/A.cs', 'P/bin-v20/A.cs', 'P/obj-v20/A.cs',
                         'P/Generated/A.cs', 'P/A.g.cs', 'P/A.g.i.cs', 'P/A.generated.cs',
                         'P/A.designer.cs', 'TiaMcp.WorkerProtocol.Core/A.cs'):
                path = base / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text('// 2.0: old', encoding='utf-8')
            (base / 'P/Auto.cs').write_text('// <auto-generated/>\n// 3.0: old', encoding='utf-8')
            rows, errors, projects = scan(root)
            self.assertEqual((1, [], 1), (len(rows), errors, sum(projects.values())))
            self.assertEqual(3, len(scan(root / 'missing')[1]))

    def test_invalid_baseline_and_lexer_failure(self):
        with lexer.scratch_directory() as root:
            path = root / 'baseline.json'
            for data in ([], {'format': 2, 'entries': []}, {'format': 1, 'entries': [{}]}):
                path.write_text(json.dumps(data), encoding='utf-8')
                with self.assertRaises(ValueError):
                    read_baseline(path, KINDS)
        with self.assertRaises(ValueError):
            self.rows('/* unterminated')


def main():
    args = arguments(__doc__, BASELINE)
    if args.self_test:
        return not unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(SelfTests)).wasSuccessful()
    rows, errors, projects = scan(args.root)
    print_inventory(rows, projects)
    return check_baseline(rows, errors, args.baseline or args.root / BASELINE, KINDS,
                          args.update_baseline, args.allow_growth)


if __name__ == '__main__':
    sys.exit(main())
