"""Locate C# declarations by name, independently of the engine's file layout.

This is a lexical source-check helper, not a C# compiler. Reuse the repository's
lexer so comments, literals and conditional branches cannot truncate a member.
Missing or ambiguous declarations fail closed; callers must identify overloads.
"""
import importlib.util
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
ENGINE = Path('src/Engine')
spec = importlib.util.spec_from_file_location('source_contract_lexer',
                                            Path(__file__).with_name('Check-SwallowedExceptions.py'))
lexer = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = lexer
spec.loader.exec_module(lexer)


def block_after(source, marker):
    """Extract a marked block without relying on the following member/comment."""
    if source.count(marker) != 1:
        raise AssertionError(f'Expected one block marker: {marker}')
    offset = source.index(marker) + len(marker)
    tokens, _ = lexer.Lexer(source).scan()
    opening = next(i for i, token in enumerate(tokens) if token.start >= offset and token.value == '{')
    closing = lexer.matching_pairs(tokens)[opening]
    return source[tokens[opening].start:tokens[closing].end]


class EngineSources:
    def __init__(self, root=ROOT):
        self.directory = root / ENGINE
        self.sources = {}
        self.parsed = {}
        for path in sorted(self.directory.rglob('*.cs')):
            relative = path.relative_to(self.directory)
            if any(part.lower() in lexer.SKIP_DIRS for part in relative.parts):
                continue
            if path.name.lower().endswith(lexer.GENERATED_SUFFIXES):
                continue
            text = path.read_text(encoding='utf-8-sig')
            if '<auto-generated' not in text[:2048].lower():
                self.sources[path] = text
        # Ported declarations remain compiled into transitional engine metadata,
        # but their implementation and execution owner live in Foundation.
        for name in ('HardwareAddressTools.cs', 'HardwareToolContract.cs'):
            path = root / 'src/Shared' / name
            if path.exists(): self.sources[path] = path.read_text(encoding='utf-8-sig')
        if not self.sources:
            raise AssertionError(f'No engine sources in {self.directory}')

    def all_text(self):
        return '\n'.join(self.sources.values())

    def _parse(self, path):
        if path not in self.parsed:
            text = self.sources[path]
            tokens, comments = lexer.Lexer(text).scan()
            masked = list(text)
            for token in [*comments, *(t for t in tokens if t.kind in ('literal', 'directive'))]:
                masked[token.start:token.end] = ['\n' if c == '\n' else ' ' for c in text[token.start:token.end]]
            self.parsed[path] = (tokens, lexer.matching_pairs(tokens), ''.join(masked),
                                 {t.start: i for i, t in enumerate(tokens)})
        return self.parsed[path]

    def type_text(self, name):
        """Return every partial declaration of a named type, wherever it lives."""
        found = []
        pattern = re.compile(r'\b(?:class|struct|interface)\s+' + re.escape(name) + r'\b[^{};]*\{')
        for path, text in self.sources.items():
            if name not in text:
                continue
            tokens, pairs, masked, starts = self._parse(path)
            for match in pattern.finditer(masked):
                end = tokens[pairs[starts[match.end() - 1]]].end
                found.append(text[match.start():end])
        if not found:
            raise AssertionError(f'Type {name}: no declarations found')
        return '\n'.join(found)

    def member(self, name, *, signature=None, owner=None, tool=None, body_only=False):
        """Return one complete method; signature is a substring of its declaration.

        owner disambiguates unrelated types, tool selects an attributed MCP entry
        point (or its implementation). Neither selection depends on a file path.
        """
        found = []
        pattern = re.compile(r'\b(?:public|private|internal|protected)\s+'
                             r'[\w\s<>,.?\[\]:]*?\b' + re.escape(name) + r'\s*\(')
        for path, text in self.sources.items():
            if name not in text:
                continue
            tokens, pairs, masked, starts = self._parse(path)
            for match in pattern.finditer(masked):
                opening = starts[match.end() - 1]
                closing = pairs[opening]
                declaration = text[match.start():tokens[closing].end]
                if signature is not None and signature not in declaration:
                    continue
                if owner is not None:
                    types = re.finditer(r'\b(?:class|struct)\s+(\w+)\b[^{};]*\{', masked)
                    enclosing = [m for m in types if m.end() <= match.start() < tokens[pairs[starts[m.end() - 1]]].end]
                    if not enclosing or enclosing[-1][1] != owner:
                        continue
                # Attributes immediately preceding the declaration, ignoring comments.
                prefix = masked[:match.start()].rstrip()
                attributes = ''
                reverse_pairs = {end: start for start, end in pairs.items()}
                while prefix.endswith(']'):
                    end = starts[len(prefix) - 1]
                    start = tokens[reverse_pairs[end]].start
                    attributes = text[start:len(prefix)] + attributes
                    prefix = masked[:start].rstrip()
                is_tool = bool(re.search(r'\bMcpServerTool(?:Attribute)?\s*\(', attributes))
                if tool is not None and is_tool != tool:
                    continue
                start = closing + 1
                while tokens[start].kind == 'directive':
                    start += 1
                if tokens[start].value == '{':
                    end = pairs[start]
                elif tokens[start].value == '=>':
                    end = start + 1
                    while tokens[end].value != ';':
                        end = pairs.get(end, end) + 1
                else:
                    continue  # Interface/partial declaration without an implementation.
                if tool is False and tokens[start].value == '=>':
                    # Migration-period forwarders share the moved method's name but are not implementations:
                    # attribute-less static CLI forwarders on McpServer and kernel forwarders into a service.
                    types = re.finditer(r'\b(?:class|struct)\s+(\w+)\b[^{};]*\{', masked)
                    enclosing = [m for m in types if m.end() <= match.start() < tokens[pairs[starts[m.end() - 1]]].end]
                    body = text[tokens[start].start:tokens[end].end]
                    if ('EngineServices.Get' in body or
                            (enclosing and enclosing[-1][1] == 'McpServer' and re.search(r'\bstatic\b', declaration))):
                        continue
                begin = tokens[start].start if body_only else match.start()
                found.append((path, text[begin:tokens[end].end]))
        if len(found) != 1:
            locations = ', '.join(str(path.relative_to(self.directory.parent.parent)) for path, _ in found)
            raise AssertionError(f'Member {name}: expected one implementation, found {len(found)} ({locations})')
        return found[0][1]
