"""Self-tests for move-independent, fail-closed source member lookup."""
import unittest
from engine_sources import ENGINE, EngineSources, block_after, lexer


class EngineSourceTests(unittest.TestCase):
    def setUp(self):
        self.scratch = lexer.scratch_directory()
        self.root = self.scratch.__enter__()
        self.add('Original.cs', '''namespace Demo {
class Service {
    // public void Decoy() { }
    public string Read(string text = "}") {
        var literal = @"public void Decoy() { }";
        var interpolated = $"{new { Name = "}" }}";
        /* } */ return text;
    }
    public string Read(int count) => count.ToString();
    [McpServerTool(Name = "Read")]
    public string Tool() => Read(1);
    class Nested { public void Read() { } }
}
}''')

    def tearDown(self):
        self.scratch.__exit__(None, None, None)

    def add(self, relative, text):
        path = self.root / ENGINE / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding='utf-8-sig')
        return path

    def test_member_survives_move_and_preserves_utf8(self):
        original = self.root / ENGINE / 'Original.cs'
        before = EngineSources(self.root).member('Read', signature='string text')
        moved = self.root / ENGINE / 'Services/Nested/Renamed.cs'
        moved.parent.mkdir(parents=True)
        original.rename(moved)
        self.assertEqual(before, EngineSources(self.root).member('Read', signature='string text'))
        self.assertTrue(before.endswith('return text;\n    }'))
        self.add('Utf8.cs', 'class Utf8 { public string Label() => "中文"; }')
        self.assertIn('中文', EngineSources(self.root).member('Label'))

    def test_missing_and_ambiguous_members_fail(self):
        sources = EngineSources(self.root)
        for name in ('Missing', 'Decoy', 'Read'):
            with self.assertRaises(AssertionError):
                sources.member(name)
        self.add('Duplicate.cs', 'class Other { public string Tool() => "duplicate"; }')
        with self.assertRaises(AssertionError):
            EngineSources(self.root).member('Tool')

    def test_overloads_owner_and_tool_attribute(self):
        sources = EngineSources(self.root)
        self.assertEqual('public string Read(int count) => count.ToString();',
                         sources.member('Read', signature='int count', owner='Service'))
        self.assertEqual('public void Read() { }', sources.member('Read', owner='Nested'))
        self.assertEqual('=> Read(1);', sources.member('Tool', tool=True, body_only=True))
        with self.assertRaises(AssertionError):
            sources.member('Tool', tool=False)
        source = 'try { Call(); } catch { if (true) { Log("}"); } throw; } Later();'
        self.assertEqual('{ if (true) { Log("}"); } throw; }', block_after(source, 'catch'))
        with self.assertRaises(AssertionError):
            block_after(source, 'absent')

    def test_generated_and_build_sources_are_excluded(self):
        for path in ('bin/Bad.cs', 'obj-v20/Bad.cs', 'Generated/Bad.cs', 'Other.g.cs'):
            self.add(path, 'class Bad { public void Tool() { } }')
        self.add('Auto.cs', '// <auto-generated/>\nclass Bad { public void Tool() { } }')
        self.assertIn('=> Read(1);', EngineSources(self.root).member('Tool'))

    def test_partial_types_and_preprocessor_braces(self):
        self.add('Branch.cs', '''partial class Branch {
public void Conditional() {
#if ONE
    if (true) {
#else
    if (false) {
#endif
    }
}
}''')
        self.add('Elsewhere.cs', 'partial class Branch { public void Second() { } }')
        sources = EngineSources(self.root)
        self.assertIn('#else', sources.member('Conditional'))
        self.assertEqual(2, sources.type_text('Branch').count('class Branch'))
        with self.assertRaises(AssertionError):
            sources.type_text('Missing')


if __name__ == '__main__':
    unittest.main()
