<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>V21</RootNamespace>
    <TiaMajor>21</TiaMajor>
    <SiemensBaseAssembly>Siemens.Engineering.Base</SiemensBaseAssembly>
    <AssemblyName>V21</AssemblyName>
  </PropertyGroup>
  <Import Project="../NativeTests.props" />
</Project>
