using System.Text;
using System.Text.RegularExpressions;

namespace TiaMcp.BuildCommon;

// Lexical, move-independent lookup; missing or ambiguous declarations fail closed.
public sealed class EngineSources
{
    private sealed record Parsed(IReadOnlyList<Token> Tokens, IReadOnlyDictionary<int, int> Pairs, string Masked, Dictionary<int, int> Starts);
    private readonly string directory;
    private readonly Dictionary<string, string> sources = [];
    private readonly Dictionary<string, Parsed> parsed = [];

    public EngineSources(string? root = null)
    {
        directory = Path.Combine(root ?? Repository.FindRoot(), "src", "Engine");
        foreach (var path in Directory.Exists(directory) ? Directory.EnumerateFiles(directory, "*.cs", SearchOption.AllDirectories).Order(Comparer<string>.Create(ComparePaths)) : Enumerable.Empty<string>())
        {
            var relative = Path.GetRelativePath(directory, path);
            if (relative.Split(Path.DirectorySeparatorChar).Any(CSharpLexer.SkipDirs.Contains)) continue;
            if (CSharpLexer.GeneratedSuffixes.Any(suffix => path.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))) continue;
            var text = Repository.ReadSource(path);
            var headerLength = text.EnumerateRunes().Take(2048).Sum(rune => rune.Utf16SequenceLength);
            if (!text[..headerLength].Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)) sources[path] = text;
        }
        if (sources.Count == 0) throw new ArgumentException("No engine sources in " + directory);
    }

    public string AllText() => string.Join('\n', sources.Values);

    private static int ComparePaths(string first, string second)
    {
        // pathlib compares path components, with case folding on Windows.
        var left = first.Split(Path.DirectorySeparatorChar);
        var right = second.Split(Path.DirectorySeparatorChar);
        for (var i = 0; i < Math.Min(left.Length, right.Length); i++)
        {
            var a = OperatingSystem.IsWindows() ? left[i].ToLowerInvariant() : left[i];
            var b = OperatingSystem.IsWindows() ? right[i].ToLowerInvariant() : right[i];
            var comparison = PythonStringComparer.Instance.Compare(a, b);
            if (comparison != 0) return comparison;
        }
        return left.Length.CompareTo(right.Length);
    }

    private Parsed Parse(string path)
    {
        if (!parsed.TryGetValue(path, out var value))
        {
            var text = sources[path];
            var (tokens, comments) = new CSharpLexer(text).Scan();
            var masked = text.ToCharArray();
            foreach (var token in comments.Concat(tokens.Where(t => t.Kind is "literal" or "directive")))
                for (var i = token.OffsetStart; i < token.OffsetEnd; i++) masked[i] = text[i] == '\n' ? '\n' : ' ';
            value = new Parsed(tokens, MatchingPairs.Find(tokens), new string(masked), tokens.Select((t, i) => (t.OffsetStart, i)).ToDictionary(t => t.OffsetStart, t => t.i));
            parsed[path] = value;
        }
        return value;
    }

    public string TypeText(string name)
    {
        var found = new List<string>();
        var pattern = new Regex(@"\b(?:class|struct|interface)\s+" + Regex.Escape(name) + @"\b[^{};]*\{");
        foreach (var (path, text) in sources)
        {
            if (!text.Contains(name, StringComparison.Ordinal)) continue;
            var p = Parse(path);
            foreach (Match match in pattern.Matches(p.Masked))
            {
                var end = p.Tokens[p.Pairs[p.Starts[match.Index + match.Length - 1]]].OffsetEnd;
                found.Add(text[match.Index..end]);
            }
        }
        if (found.Count == 0) throw new ArgumentException($"Type {name}: no declarations found");
        return string.Join('\n', found);
    }

    private static string? Owner(Parsed p, int offset)
    {
        var enclosing = Regex.Matches(p.Masked, @"\b(?:class|struct)\s+(\w+)\b[^{};]*\{").Cast<Match>()
            .Where(m => m.Index + m.Length <= offset && offset < p.Tokens[p.Pairs[p.Starts[m.Index + m.Length - 1]]].OffsetEnd).LastOrDefault();
        return enclosing?.Groups[1].Value;
    }

    public string Member(string name, string? signature = null, string? owner = null, bool? tool = null, bool bodyOnly = false)
    {
        var found = new List<(string Path, string Text)>();
        var pattern = new Regex(@"\b(?:public|private|internal|protected)\s+[\w\s<>,.?\[\]:]*?\b" + Regex.Escape(name) + @"\s*\(");
        foreach (var (path, text) in sources)
        {
            if (!text.Contains(name, StringComparison.Ordinal)) continue;
            var p = Parse(path);
            foreach (Match match in pattern.Matches(p.Masked))
            {
                var opening = p.Starts[match.Index + match.Length - 1];
                var closing = p.Pairs[opening];
                var declaration = text[match.Index..p.Tokens[closing].OffsetEnd];
                if (signature is not null && !declaration.Contains(signature, StringComparison.Ordinal)) continue;
                if (owner is not null && Owner(p, match.Index) != owner) continue;
                var prefix = p.Masked[..match.Index].TrimEnd();
                var attributes = "";
                // Multiple conditional openings can share an ending; Python's reverse map retains the last one.
                var reverse = new Dictionary<int, int>();
                foreach (var (startPair, endPair) in p.Pairs) reverse[endPair] = startPair;
                while (prefix.EndsWith(']'))
                {
                    var endAttribute = p.Starts[prefix.Length - 1];
                    var startAttribute = p.Tokens[reverse[endAttribute]].OffsetStart;
                    attributes = text[startAttribute..prefix.Length] + attributes;
                    prefix = p.Masked[..startAttribute].TrimEnd();
                }
                var isTool = Regex.IsMatch(attributes, @"\bMcpServerTool(?:Attribute)?\s*\(");
                if (tool.HasValue && isTool != tool.Value) continue;
                var start = closing + 1;
                while (p.Tokens[start].Kind == "directive") start++;
                int end;
                if (p.Tokens[start].Value == "{") end = p.Pairs[start];
                else if (p.Tokens[start].Value == "=>")
                {
                    end = start + 1;
                    while (p.Tokens[end].Value != ";") end = p.Pairs.GetValueOrDefault(end, end) + 1;
                }
                else continue;
                if (tool is false && p.Tokens[start].Value == "=>")
                {
                    var body = text[p.Tokens[start].OffsetStart..p.Tokens[end].OffsetEnd];
                    if (body.Contains("EngineServices.Get", StringComparison.Ordinal) || Owner(p, match.Index) == "McpServer" && Regex.IsMatch(declaration, @"\bstatic\b")) continue;
                }
                var begin = bodyOnly ? p.Tokens[start].OffsetStart : match.Index;
                found.Add((path, text[begin..p.Tokens[end].OffsetEnd]));
            }
        }
        if (found.Count != 1)
            throw new ArgumentException($"Member {name}: expected one implementation, found {found.Count} ({string.Join(", ", found.Select(f => Path.GetRelativePath(directory, f.Path)))})");
        return found[0].Text;
    }

    public static string BlockAfter(string source, string marker)
    {
        var start = source.IndexOf(marker, StringComparison.Ordinal);
        if (marker.Length == 0 || start < 0 || source.IndexOf(marker, start + marker.Length, StringComparison.Ordinal) >= 0)
            throw new ArgumentException("Expected one block marker: " + marker);
        var offset = start + marker.Length;
        var (tokens, _) = new CSharpLexer(source).Scan();
        var opening = Enumerable.Range(0, tokens.Count).First(i => tokens[i].OffsetStart >= offset && tokens[i].Value == "{");
        var closing = MatchingPairs.Find(tokens)[opening];
        return source[tokens[opening].OffsetStart..tokens[closing].OffsetEnd];
    }
}
