using System;
using ModelContextProtocol.Protocol;
using TiaMcp.Logic.V4;
using TiaMcp.Logic.V4.Domain;
using System.ComponentModel;
using ModelContextProtocol.Server;
using TiaMcpServer.Siemens.Services;
namespace TiaMcpServer.ModelContextProtocol
{
    [McpServerToolType]
    internal sealed class V20OptionsTools
    {
        private readonly V20OptionsService _v20Options;

        public V20OptionsTools(V20OptionsService v20Options) => _v20Options = v20Options;

        [McpServerTool(Name = "ManageSinumerikArchive"), Description("[L2][Hardware][WRITE] V20 SINUMERIK Project.HwUtilities archive/retrieve/fAddressArchive (.dsf). Exact device/item paths are Arrays. archive mode OnlyHardware/HardwareAndAllProgramBlocks; F-address archive selects productive and modified PLC items. Optional comment/author/password; passwords are not logged. dryRun defaults true. Existing output files refused; outputs hashed. Retrieve inserts a device and returns its name, without save. Requires SINUMERIK option; supplied V21 SDK unsupported. Native behaviorPolicy=current; V4 native acceptance is pending.")]
        public CallToolResult ManageSinumerikArchive([Description("archive | retrieve | fAddressArchive. Operation name from the supported actions in the tool description.")] string action, [Description("Absolute input/output path on the MCP server, with the documented extension.")] string filePath, [Description("Array of exact device-group/device names.")] string[] devicePath = null!, [Description("Array of exact PLC device-item names below the selected device.")] string[] itemPath = null!, [Description("Array of exact modified PLC device-group/device names.")] string[] modifiedDevicePath = null!, [Description("Array selecting the modified PLC item for F-address archive.")] string[] modifiedItemPath = null!, [Description("For archives OnlyHardware | HardwareAndAllProgramBlocks; for SINUMERIK safety None | NcSI | DbSI.")] string mode = "HardwareAndAllProgramBlocks", [Description("Optional archive comment.")] string comment = "", [Description("Optional archive author.")] string author = "", [Description("Optional archive password; passed as SecureString and never logged.")] string password = "", [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true)
            => OptionalPackageContract.Run("ManageSinumerikArchive", !dryRun, () => _v20Options.ManageSinumerikArchive(action, filePath, V4Json.Serialize(devicePath ?? Array.Empty<string>()), V4Json.Serialize(itemPath ?? Array.Empty<string>()), V4Json.Serialize(modifiedDevicePath ?? Array.Empty<string>()), V4Json.Serialize(modifiedItemPath ?? Array.Empty<string>()), mode, comment, author, password, dryRun));

        [McpServerTool(Name = "ImportSinumerikAlarmTexts"), Description("[L2][PLC-Software][WRITE] V20 SINUMERIK NCU Device.GetService<SinumerikAlarmTextProvider>().AlarmTextImporter.ImportAlarmTexts. devicePath exact device path array; files array of absolute .ts/.csv files on server. DB2 alarm texts can replace existing contents; project languages must be active. Default dryRun=true. Reports native completion, not unverified content fidelity. No save; requires SINUMERIK option; supplied V21 SDK unsupported. Native behaviorPolicy=current; V4 native acceptance is pending.")]
        public CallToolResult ImportSinumerikAlarmTexts([Description("Array of exact device-group/device names.")] string[] devicePath, [Description("Array of 1..200 existing absolute .ts/.csv alarm-text files.")] string[] files, [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true)
            => OptionalPackageContract.Run("ImportSinumerikAlarmTexts", !dryRun, () => _v20Options.ImportSinumerikAlarmTexts(V4Json.Serialize(devicePath ?? Array.Empty<string>()), V4Json.Serialize(files), dryRun));

        [McpServerTool(Name = "ManageSinumerikSafetyMode"), Description("[L2][Safety][WRITE] V20 SINUMERIK NCU SafetyModeProvider: read CurrentMode or set None/NcSI/DbSI. Exact devicePath array. Set requires dryRun=false and confirmSafetyChange=true; native API enforces NCU offline/configuration eligibility and resulting mode is read back. Mode changes affect safety/telegram engineering; no automatic save/compile/download. Default action=read. Requires SINUMERIK option; supplied V21 SDK unsupported. Native behaviorPolicy=current; V4 native acceptance is pending.")]
        public CallToolResult ManageSinumerikSafetyMode([Description("Array of exact device-group/device names.")] string[] devicePath, [Description("read | set. Operation name from the supported actions in the tool description.")] string action = "read", [Description("For archives OnlyHardware | HardwareAndAllProgramBlocks; for SINUMERIK safety None | NcSI | DbSI.")] string mode = "", [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true, [Description("Must be true with dryRun=false for a safety-mode write.")] bool confirmSafetyChange = false)
            => OptionalPackageContract.Run("ManageSinumerikSafetyMode", !dryRun && action != "read", () => _v20Options.ManageSinumerikSafetyMode(V4Json.Serialize(devicePath ?? Array.Empty<string>()), action, mode, dryRun, confirmSafetyChange));

        [McpServerTool(Name = "InitializeSimotionScripting"), Description("[L2][Hardware][WRITE] V20 Project SimotionProvider.Initialize scripting bootstrap; dryRun=true only checks provider. Actual call returns the native initialization string without executing it or running external SCOUT scripts. Requires SIMOTION SCOUT TIA. Supplied V21 SDK unsupported. No project save or controller access. Native behaviorPolicy=current; V4 native acceptance is pending.")]
        public CallToolResult InitializeSimotionScripting([Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true) => OptionalPackageContract.Run("InitializeSimotionScripting", !dryRun, () => _v20Options.InitializeSimotionScripting(dryRun));

        [McpServerTool(Name = "ExportScadaData"), Description("[L2][PLC-Software][READ] V20 ScadaExportProvider.Export PLC configuration to an absolute ZIP path on server. softwarePath empty selects project; otherwise one exact PLC. Requires SIMATIC SCADA Export for TIA Portal option. Default dryRun=true; existing file refused and resulting nonempty ZIP hashed. Does not deploy WinCC runtime. Supplied V21 SDK unsupported. Native behaviorPolicy=current; V4 native acceptance is pending.")]
        public CallToolResult ExportScadaData([Description("Absolute input/output path on the MCP server, with the documented extension.")] string filePath, [Description("Exact PLC software name/path; empty selects project only where documented.")] string softwarePath = "", [Description("true previews without invoking the native mutation/export; false executes.")] bool dryRun = true) => OptionalPackageContract.Run("ExportScadaData", !dryRun, () => _v20Options.ExportScadaData(filePath, softwarePath, dryRun));
    }
}
